def hmac_sha256(key: bytes, message: bytes) -> bytes: ...
def hmac_sha512(key: bytes, message: bytes) -> bytes: ...
def hmac(algorithm: str, secret: str, data: str, encoding: str) -> str: ...
def hash(algorithm: str, data: str, encoding: str) -> str: ...
def hash_digest(algorithm: str, data: str, encoding: str) -> str: ...
