import { StarfishHttpError, ConflictError } from '@drakkar.software/starfish-client'
import { NodeHttpError } from '../../transport/rest.js'
import type { SeedDerivation } from './options.js'
import { AutomationActionFailedError, AutomationTimeoutError } from '../../protocol/orchestration/createAutomation.js'

export type OctoBotErrorCode =
  | 'config'
  | 'unreachable'
  | 'timeout'
  | 'unauthorized'
  | 'http'
  | 'conflict'
  | 'action_failed'
  | 'action_timeout'
  | 'aborted'
  | 'forbidden_collection'

/** Base class for every error this package throws. Every method that can
 *  fail throws one of these (or lets an `AbortError` DOMException through
 *  unwrapped, per the platform convention). Switch on `code` rather than
 *  `instanceof` when the check has to survive across a duplicated package
 *  instance (a monorepo hoisting quirk, a bundler that doesn't dedupe). */
export class OctoBotError extends Error {
  readonly code: OctoBotErrorCode
  override readonly cause?: unknown
  constructor(code: OctoBotErrorCode, message: string, cause?: unknown) {
    super(message)
    this.name = 'OctoBotError'
    this.code = code
    this.cause = cause
  }
}

/** Bad `ConnectOptions` — an unparseable `url`, or a `node.*` call made
 *  without the `basicAuth` credentials it requires. */
export class OctoBotConfigError extends OctoBotError {
  constructor(message: string) {
    super('config', message)
    this.name = 'OctoBotConfigError'
  }
}

/** The node could not be reached at all — offline, wrong port, timed out, or
 *  the connect-time abort fired. */
export class OctoBotConnectionError extends OctoBotError {
  constructor(code: 'unreachable' | 'timeout' | 'aborted', message: string, cause?: unknown) {
    super(code, message, cause)
    this.name = 'OctoBotConnectionError'
  }
}

/** The node answered, but did not authorize this wallet. Carries what the
 *  seed actually derived to, so the message can name the mismatch instead of
 *  just saying "unauthorized". */
export class OctoBotAuthError extends OctoBotError {
  readonly address: string
  readonly userId: string
  readonly derivation: SeedDerivation
  constructor(address: string, userId: string, derivation: SeedDerivation) {
    super(
      'unauthorized',
      `the node did not authorize ${address} (derived under '${derivation}'). ` +
        `If this seed phrase was generated by an app using a non-standard derivation, ` +
        `try seedDerivation: 'auto' or the other explicit value.`,
    )
    this.name = 'OctoBotAuthError'
    this.address = address
    this.userId = userId
    this.derivation = derivation
  }
}

/** A node REST call (`client.node.*`) answered with a non-2xx status. */
export class OctoBotHttpError extends OctoBotError {
  readonly status: number
  constructor(status: number, cause?: unknown) {
    super('http', `Node request failed: HTTP ${status}`, cause)
    this.name = 'OctoBotHttpError'
    this.status = status
  }
}

/** A document push raced another writer's push — the `baseHash` you pushed
 *  against is no longer the server's current hash. Pull again and retry. */
export class OctoBotConflictError extends OctoBotError {
  readonly serverHash: string | null
  constructor(serverHash: string | null, cause?: unknown, message = 'push conflict: the document changed since it was last pulled') {
    super('conflict', message, cause)
    this.name = 'OctoBotConflictError'
    this.serverHash = serverHash
  }
}

/** The node executed a queued action and rejected it. Not retriable by
 *  resubmitting the same configuration unchanged. */
export class OctoBotActionError extends OctoBotError {
  readonly phase?: string
  readonly detail: string | null
  constructor(detail: string | null, phase?: string, cause?: unknown) {
    super('action_failed', `action failed${detail ? `: ${detail}` : ''}`, cause)
    this.name = 'OctoBotActionError'
    this.phase = phase
    this.detail = detail
  }
}

/** `ActionHandle.settled()` gave up waiting — the node never confirmed
 *  within the timeout budget. Not necessarily a failure; the action may
 *  still complete. */
export class OctoBotTimeoutError extends OctoBotError {
  readonly phase?: string
  constructor(phase?: string, cause?: unknown) {
    super('action_timeout', 'timed out waiting for the node to confirm', cause)
    this.name = 'OctoBotTimeoutError'
    this.phase = phase
  }
}

/** A read-only session tried to read/write a collection its pairing grant
 *  doesn't cover — thrown client-side, before any network request, by
 *  `ClientSession.collectionEncryptor()`. This is not merely a courtesy: the
 *  node does not yet enforce a cap's collection scope itself (every
 *  collection is currently `readRoles=["self"], writeRoles=["self"]`, which
 *  a device cap always satisfies regardless of its `scope`), so this
 *  client-side check is presently the ONLY thing keeping a read-only session
 *  inside its granted collections. */
export class OctoBotScopeError extends OctoBotError {
  readonly collection: string
  constructor(collection: string) {
    super('forbidden_collection', `read-only session: no key granted for collection "${collection}"`)
    this.name = 'OctoBotScopeError'
    this.collection = collection
  }
}

export function isOctoBotError(e: unknown): e is OctoBotError {
  return e instanceof OctoBotError
}

/** Translate a raw transport/orchestration error into the public
 *  `OctoBotError` hierarchy. Does NOT touch an `AbortError` — see
 *  `rethrowAsOctoBotError` below, which every `client.*` method's catch
 *  actually calls. */
export function toOctoBotError(err: unknown): OctoBotError {
  if (err instanceof OctoBotError) return err
  if (err instanceof AutomationActionFailedError) return new OctoBotActionError(err.detail, err.phase, err)
  if (err instanceof AutomationTimeoutError) return new OctoBotTimeoutError(err.phase, err)
  if (err instanceof ConflictError) {
    // The shipped starfish-client exposes the server's authoritative hash
    // as `.currentHash`, not `.serverHash` — reading the wrong field name
    // meant `OctoBotConflictError.serverHash`, the documented retry hint,
    // was silently always null.
    return new OctoBotConflictError(err.currentHash || null, err)
  }
  if (err instanceof StarfishHttpError) {
    if (err.status === 401 || err.status === 403) {
      return new OctoBotError('unauthorized', `sync request rejected: HTTP ${err.status}`, err)
    }
    return new OctoBotError('http', `sync request failed: HTTP ${err.status}`, err)
  }
  if (err instanceof NodeHttpError) return new OctoBotHttpError(err.status, err)
  // A base OctoBotError here would make `instanceof OctoBotConnectionError`
  // false on the path most callers actually hit (anything that isn't a
  // recognized typed error, i.e. "could not reach the node at all") —
  // README.md documents that class for exactly this case.
  return new OctoBotConnectionError('unreachable', err instanceof Error ? err.message : String(err), err)
}

/** What every `client.*` method's `catch` block calls. Lets an `AbortError`
 *  DOMException through unwrapped (the platform convention a caller's own
 *  `signal` handling already expects) and wraps everything else as an
 *  `OctoBotError`. */
export function rethrowAsOctoBotError(err: unknown): never {
  if (err instanceof DOMException && err.name === 'AbortError') throw err
  throw toOctoBotError(err)
}
