import type { RustBridge } from "./types"

let bridge: RustBridge | null = null

const WASM_REQUIRED_EXPORTS = [
  "hmac", "hash", "hmac_sha256", "hmac_sha256_hex",
  "hmac_sha512", "hmac_sha512_hex",
  "random_bytes_hex", "random_bytes",
  "buffer_to_hex", "buffer_from_hex", "buffer_to_base64", "buffer_from_base64", "buffer_byte_length",
] as const

export async function loadWasm(): Promise<RustBridge | null> {
  if (bridge) return bridge
  try {
    // Generated by wasm-pack
    const mod = await import("./pkg/octobot_edge_wasm.js")
    await mod.default()

    // Validate all required exports exist
    for (const fn of WASM_REQUIRED_EXPORTS) {
      if (typeof mod[fn] !== "function") {
        console.warn(`[edge] WASM module missing export: ${fn}`)
        return null
      }
    }

    // wasm-pack exports use snake_case; map to camelCase RustBridge interface
    bridge = {
      hmac: mod.hmac,
      hash: mod.hash,
      hmacSha256: mod.hmac_sha256,
      hmacSha256Hex: mod.hmac_sha256_hex,
      hmacSha512: mod.hmac_sha512,
      hmacSha512Hex: mod.hmac_sha512_hex,
      randomBytesHex: mod.random_bytes_hex,
      randomBytes: mod.random_bytes,
      bufferToHex: mod.buffer_to_hex,
      bufferFromHex: mod.buffer_from_hex,
      bufferToBase64: mod.buffer_to_base64,
      bufferFromBase64: mod.buffer_from_base64,
      bufferByteLength: mod.buffer_byte_length,
    }
    return bridge
  } catch (err) {
    console.warn("[edge] Failed to load WASM bridge:", err)
    return null
  }
}
