# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AccountStatusMessage(str, Enum):
    """
    AccountStatusMessage
    """

    """
    allowed enum values
    """
    PENDING_VALIDATION = 'pending_validation'
    VALID = 'valid'
    INVALID_API_KEYS = 'invalid_api_keys'
    MISSING_API_TRADING_RIGHTS = 'missing_api_trading_rights'
    REVOKE_API_WITHDRAWAL_RIGHTS = 'revoke_api_withdrawal_rights'
    INVALID_API_IP_WHITELIST = 'invalid_api_ip_whitelist'
    INTERNAL_SERVER_ERROR = 'internal_server_error'
    ACCOUNT_TOO_OLD = 'account_too_old'
    INCOMPATIBLE_ACCOUNT_REFERRAL = 'incompatible_account_referral'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AccountStatusMessage from a JSON string"""
        return cls(json.loads(json_str))


