# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from octobot_protocol.models.asset_account import AssetAccount
from octobot_protocol.models.bank_account import BankAccount
from octobot_protocol.models.blockchain_account import BlockchainAccount
from octobot_protocol.models.broker_account import BrokerAccount
from octobot_protocol.models.exchange_account import ExchangeAccount
from octobot_protocol.models.generic_account import GenericAccount
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

ACCOUNTSPECIFICS_ONE_OF_SCHEMAS = ["AssetAccount", "BankAccount", "BlockchainAccount", "BrokerAccount", "ExchangeAccount", "GenericAccount"]

class AccountSpecifics(BaseModel):
    """
    AccountSpecifics
    """
    # data type: ExchangeAccount
    oneof_schema_1_validator: Optional[ExchangeAccount] = None
    # data type: BlockchainAccount
    oneof_schema_2_validator: Optional[BlockchainAccount] = None
    # data type: GenericAccount
    oneof_schema_3_validator: Optional[GenericAccount] = None
    # data type: BrokerAccount
    oneof_schema_4_validator: Optional[BrokerAccount] = None
    # data type: BankAccount
    oneof_schema_5_validator: Optional[BankAccount] = None
    # data type: AssetAccount
    oneof_schema_6_validator: Optional[AssetAccount] = None
    actual_instance: Optional[Union[AssetAccount, BankAccount, BlockchainAccount, BrokerAccount, ExchangeAccount, GenericAccount]] = None
    one_of_schemas: Set[str] = { "AssetAccount", "BankAccount", "BlockchainAccount", "BrokerAccount", "ExchangeAccount", "GenericAccount" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = AccountSpecifics.model_construct()
        error_messages = []
        match = 0
        # validate data type: ExchangeAccount
        if not isinstance(v, ExchangeAccount):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExchangeAccount`")
        else:
            match += 1
        # validate data type: BlockchainAccount
        if not isinstance(v, BlockchainAccount):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BlockchainAccount`")
        else:
            match += 1
        # validate data type: GenericAccount
        if not isinstance(v, GenericAccount):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GenericAccount`")
        else:
            match += 1
        # validate data type: BrokerAccount
        if not isinstance(v, BrokerAccount):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BrokerAccount`")
        else:
            match += 1
        # validate data type: BankAccount
        if not isinstance(v, BankAccount):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BankAccount`")
        else:
            match += 1
        # validate data type: AssetAccount
        if not isinstance(v, AssetAccount):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AssetAccount`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in AccountSpecifics with oneOf schemas: AssetAccount, BankAccount, BlockchainAccount, BrokerAccount, ExchangeAccount, GenericAccount. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in AccountSpecifics with oneOf schemas: AssetAccount, BankAccount, BlockchainAccount, BrokerAccount, ExchangeAccount, GenericAccount. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # use oneOf discriminator to lookup the data type
        _data_type = json.loads(json_str).get("account_type")
        if not _data_type:
            raise ValueError("Failed to lookup data type from the field `account_type` in the input.")

        # check if data type is `AssetAccount`
        if _data_type == "asset":
            instance.actual_instance = AssetAccount.from_json(json_str)
            return instance

        # check if data type is `BankAccount`
        if _data_type == "bank":
            instance.actual_instance = BankAccount.from_json(json_str)
            return instance

        # check if data type is `BlockchainAccount`
        if _data_type == "blockchain":
            instance.actual_instance = BlockchainAccount.from_json(json_str)
            return instance

        # check if data type is `BrokerAccount`
        if _data_type == "broker":
            instance.actual_instance = BrokerAccount.from_json(json_str)
            return instance

        # check if data type is `ExchangeAccount`
        if _data_type == "exchange":
            instance.actual_instance = ExchangeAccount.from_json(json_str)
            return instance

        # check if data type is `GenericAccount`
        if _data_type == "generic":
            instance.actual_instance = GenericAccount.from_json(json_str)
            return instance

        # deserialize data into ExchangeAccount
        try:
            instance.actual_instance = ExchangeAccount.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into BlockchainAccount
        try:
            instance.actual_instance = BlockchainAccount.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GenericAccount
        try:
            instance.actual_instance = GenericAccount.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into BrokerAccount
        try:
            instance.actual_instance = BrokerAccount.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into BankAccount
        try:
            instance.actual_instance = BankAccount.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AssetAccount
        try:
            instance.actual_instance = AssetAccount.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into AccountSpecifics with oneOf schemas: AssetAccount, BankAccount, BlockchainAccount, BrokerAccount, ExchangeAccount, GenericAccount. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into AccountSpecifics with oneOf schemas: AssetAccount, BankAccount, BlockchainAccount, BrokerAccount, ExchangeAccount, GenericAccount. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], AssetAccount, BankAccount, BlockchainAccount, BrokerAccount, ExchangeAccount, GenericAccount]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


