# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ActionConfigurationType(str, Enum):
    """
    ActionConfigurationType
    """

    """
    allowed enum values
    """
    MARKET_MAKING = 'market_making'
    DCA = 'dca'
    INDEX = 'index'
    GRID = 'grid'
    COPY = 'copy'
    GENERIC_PROCESS = 'generic_process'
    GENERIC_WORKFLOW = 'generic_workflow'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ActionConfigurationType from a JSON string"""
        return cls(json.loads(json_str))


