# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from octobot_protocol.models.copied_asset import CopiedAsset
from octobot_protocol.models.order import Order
from octobot_protocol.models.position import Position
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CopiedAccount(BaseModel):
    """
    CopiedAccount
    """ # noqa: E501
    version: StrictStr
    updated_at: Union[StrictFloat, StrictInt]
    copied_assets: List[CopiedAsset]
    orders: Optional[List[Order]] = None
    positions: Optional[List[Position]] = None
    historical_snapshots: Optional[List[CopiedAccount]] = None
    __properties: ClassVar[List[str]] = ["version", "updated_at", "copied_assets", "orders", "positions", "historical_snapshots"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CopiedAccount from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in copied_assets (list)
        _items = []
        if self.copied_assets:
            for _item_copied_assets in self.copied_assets:
                if _item_copied_assets:
                    _items.append(_item_copied_assets.to_dict())
            _dict['copied_assets'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in orders (list)
        _items = []
        if self.orders:
            for _item_orders in self.orders:
                if _item_orders:
                    _items.append(_item_orders.to_dict())
            _dict['orders'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in positions (list)
        _items = []
        if self.positions:
            for _item_positions in self.positions:
                if _item_positions:
                    _items.append(_item_positions.to_dict())
            _dict['positions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in historical_snapshots (list)
        _items = []
        if self.historical_snapshots:
            for _item_historical_snapshots in self.historical_snapshots:
                if _item_historical_snapshots:
                    _items.append(_item_historical_snapshots.to_dict())
            _dict['historical_snapshots'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CopiedAccount from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "version": obj.get("version"),
            "updated_at": obj.get("updated_at"),
            "copied_assets": [CopiedAsset.from_dict(_item) for _item in obj["copied_assets"]] if obj.get("copied_assets") is not None else None,
            "orders": [Order.from_dict(_item) for _item in obj["orders"]] if obj.get("orders") is not None else None,
            "positions": [Position.from_dict(_item) for _item in obj["positions"]] if obj.get("positions") is not None else None,
            "historical_snapshots": [CopiedAccount.from_dict(_item) for _item in obj["historical_snapshots"]] if obj.get("historical_snapshots") is not None else None
        })
        return _obj

# TODO: Rewrite to not use raise_errors
CopiedAccount.model_rebuild(raise_errors=False)

