# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from octobot_protocol.models.action_configuration_type import ActionConfigurationType
from octobot_protocol.models.evaluator_configuration import EvaluatorConfiguration
from octobot_protocol.models.strategy_evaluator_configuration import StrategyEvaluatorConfiguration
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DCAConfiguration(BaseModel):
    """
    DCAConfiguration
    """ # noqa: E501
    configuration_type: ActionConfigurationType = Field(description="dca")
    symbols: List[StrictStr]
    entry_order_amount: StrictStr = Field(description="Amout to buy, can be in %t, %s, in q, in base, etc")
    exit_limit_orders_price_percent: Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]
    entry_limit_orders_price_percent: Union[Annotated[float, Field(le=100, strict=True, ge=0)], Annotated[int, Field(le=100, strict=True, ge=0)]]
    secondary_entry_orders_count: Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]
    secondary_entry_orders_amount: StrictStr = Field(description="Amout to buy, can be in %t, %s, in q, in base, etc")
    secondary_entry_orders_price_percent: Union[Annotated[float, Field(le=100, strict=True, ge=0)], Annotated[int, Field(le=100, strict=True, ge=0)]]
    enable_stop_loss: Optional[StrictBool] = False
    stop_loss_price_discount_percent: Optional[Union[Annotated[float, Field(le=100, strict=True, ge=0)], Annotated[int, Field(le=100, strict=True, ge=0)]]] = 10
    trigger_mode: Optional[StrictStr] = 'Maximum evaluators signals based'
    use_init_entry_orders: Optional[StrictBool] = True
    max_asset_holding_percent: Optional[Union[Annotated[float, Field(le=100, strict=True, ge=0)], Annotated[int, Field(le=100, strict=True, ge=0)]]] = 50
    strategies: List[StrategyEvaluatorConfiguration]
    evaluators: List[EvaluatorConfiguration]
    __properties: ClassVar[List[str]] = ["configuration_type", "symbols", "entry_order_amount", "exit_limit_orders_price_percent", "entry_limit_orders_price_percent", "secondary_entry_orders_count", "secondary_entry_orders_amount", "secondary_entry_orders_price_percent", "enable_stop_loss", "stop_loss_price_discount_percent", "trigger_mode", "use_init_entry_orders", "max_asset_holding_percent", "strategies", "evaluators"]

    @field_validator('trigger_mode')
    def trigger_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Maximum evaluators signals based', 'Time based', 'Always trigger long']):
            raise ValueError("must be one of enum values ('Maximum evaluators signals based', 'Time based', 'Always trigger long')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DCAConfiguration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in strategies (list)
        _items = []
        if self.strategies:
            for _item_strategies in self.strategies:
                if _item_strategies:
                    _items.append(_item_strategies.to_dict())
            _dict['strategies'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in evaluators (list)
        _items = []
        if self.evaluators:
            for _item_evaluators in self.evaluators:
                if _item_evaluators:
                    _items.append(_item_evaluators.to_dict())
            _dict['evaluators'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DCAConfiguration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "configuration_type": obj.get("configuration_type"),
            "symbols": obj.get("symbols"),
            "entry_order_amount": obj.get("entry_order_amount"),
            "exit_limit_orders_price_percent": obj.get("exit_limit_orders_price_percent"),
            "entry_limit_orders_price_percent": obj.get("entry_limit_orders_price_percent"),
            "secondary_entry_orders_count": obj.get("secondary_entry_orders_count") if obj.get("secondary_entry_orders_count") is not None else 0,
            "secondary_entry_orders_amount": obj.get("secondary_entry_orders_amount") if obj.get("secondary_entry_orders_amount") is not None else '0%t',
            "secondary_entry_orders_price_percent": obj.get("secondary_entry_orders_price_percent") if obj.get("secondary_entry_orders_price_percent") is not None else 10,
            "enable_stop_loss": obj.get("enable_stop_loss") if obj.get("enable_stop_loss") is not None else False,
            "stop_loss_price_discount_percent": obj.get("stop_loss_price_discount_percent") if obj.get("stop_loss_price_discount_percent") is not None else 10,
            "trigger_mode": obj.get("trigger_mode") if obj.get("trigger_mode") is not None else 'Maximum evaluators signals based',
            "use_init_entry_orders": obj.get("use_init_entry_orders") if obj.get("use_init_entry_orders") is not None else True,
            "max_asset_holding_percent": obj.get("max_asset_holding_percent") if obj.get("max_asset_holding_percent") is not None else 50,
            "strategies": [StrategyEvaluatorConfiguration.from_dict(_item) for _item in obj["strategies"]] if obj.get("strategies") is not None else None,
            "evaluators": [EvaluatorConfiguration.from_dict(_item) for _item in obj["evaluators"]] if obj.get("evaluators") is not None else None
        })
        return _obj


