# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from octobot_protocol.models.account import Account
from octobot_protocol.models.account_trading_with_account_id import AccountTradingWithAccountId
from octobot_protocol.models.automation_state import AutomationState
from octobot_protocol.models.exchange_config import ExchangeConfig
from octobot_protocol.models.strategy import Strategy
from octobot_protocol.models.user_action import UserAction
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Debug(BaseModel):
    """
    Debug view of all automations and user actions
    """ # noqa: E501
    automations: List[AutomationState]
    user_actions: List[UserAction]
    accounts: Optional[List[Account]] = None
    exchange_configs: Optional[List[ExchangeConfig]] = None
    account_tradings: Optional[List[AccountTradingWithAccountId]] = None
    local_strategies: Optional[List[Strategy]] = None
    __properties: ClassVar[List[str]] = ["automations", "user_actions", "accounts", "exchange_configs", "account_tradings", "local_strategies"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Debug from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in automations (list)
        _items = []
        if self.automations:
            for _item_automations in self.automations:
                if _item_automations:
                    _items.append(_item_automations.to_dict())
            _dict['automations'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in user_actions (list)
        _items = []
        if self.user_actions:
            for _item_user_actions in self.user_actions:
                if _item_user_actions:
                    _items.append(_item_user_actions.to_dict())
            _dict['user_actions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in accounts (list)
        _items = []
        if self.accounts:
            for _item_accounts in self.accounts:
                if _item_accounts:
                    _items.append(_item_accounts.to_dict())
            _dict['accounts'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in exchange_configs (list)
        _items = []
        if self.exchange_configs:
            for _item_exchange_configs in self.exchange_configs:
                if _item_exchange_configs:
                    _items.append(_item_exchange_configs.to_dict())
            _dict['exchange_configs'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in account_tradings (list)
        _items = []
        if self.account_tradings:
            for _item_account_tradings in self.account_tradings:
                if _item_account_tradings:
                    _items.append(_item_account_tradings.to_dict())
            _dict['account_tradings'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in local_strategies (list)
        _items = []
        if self.local_strategies:
            for _item_local_strategies in self.local_strategies:
                if _item_local_strategies:
                    _items.append(_item_local_strategies.to_dict())
            _dict['local_strategies'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Debug from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "automations": [AutomationState.from_dict(_item) for _item in obj["automations"]] if obj.get("automations") is not None else None,
            "user_actions": [UserAction.from_dict(_item) for _item in obj["user_actions"]] if obj.get("user_actions") is not None else None,
            "accounts": [Account.from_dict(_item) for _item in obj["accounts"]] if obj.get("accounts") is not None else None,
            "exchange_configs": [ExchangeConfig.from_dict(_item) for _item in obj["exchange_configs"]] if obj.get("exchange_configs") is not None else None,
            "account_tradings": [AccountTradingWithAccountId.from_dict(_item) for _item in obj["account_tradings"]] if obj.get("account_tradings") is not None else None,
            "local_strategies": [Strategy.from_dict(_item) for _item in obj["local_strategies"]] if obj.get("local_strategies") is not None else None
        })
        return _obj


