# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from octobot_protocol.models.dsl_parameter_default_value import DslParameterDefaultValue
from octobot_protocol.models.dsl_parameter_option import DslParameterOption
from octobot_protocol.models.dsl_value_type import DslValueType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DslParameter(BaseModel):
    """
    Configurable parameter on a DSL keyword.
    """ # noqa: E501
    name: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Unique within this keyword.")
    label: StrictStr
    value_type: DslValueType
    description: Optional[StrictStr] = None
    default_value: Optional[DslParameterDefaultValue] = None
    minimum: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Only for parameter_type=number.")
    maximum: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Only for parameter_type=number.")
    step: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Only for parameter_type=number.")
    options: Optional[List[DslParameterOption]] = Field(default=None, description="Allowed choices for value_type=text or value_type=time_frame.")
    required: Optional[StrictBool] = None
    multiple: Optional[StrictBool] = Field(default=None, description="Accepts more than one value of this parameter.")
    primary: Optional[StrictBool] = Field(default=None, description="Prefer in compact editors.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["name", "label", "value_type", "description", "default_value", "minimum", "maximum", "step", "options", "required", "multiple", "primary"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DslParameter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of default_value
        if self.default_value:
            _dict['default_value'] = self.default_value.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in options (list)
        _items = []
        if self.options:
            for _item_options in self.options:
                if _item_options:
                    _items.append(_item_options.to_dict())
            _dict['options'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DslParameter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "label": obj.get("label"),
            "value_type": obj.get("value_type"),
            "description": obj.get("description"),
            "default_value": DslParameterDefaultValue.from_dict(obj["default_value"]) if obj.get("default_value") is not None else None,
            "minimum": obj.get("minimum"),
            "maximum": obj.get("maximum"),
            "step": obj.get("step"),
            "options": [DslParameterOption.from_dict(_item) for _item in obj["options"]] if obj.get("options") is not None else None,
            "required": obj.get("required"),
            "multiple": obj.get("multiple"),
            "primary": obj.get("primary")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


