# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from typing_extensions import Annotated
from octobot_protocol.models.action_configuration_type import ActionConfigurationType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GridConfiguration(BaseModel):
    """
    GridConfiguration
    """ # noqa: E501
    configuration_type: ActionConfigurationType = Field(description="grid")
    symbol: StrictStr
    spread: Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]] = Field(description="Price difference between the closest buy and sell orders. Denominated in the quote currency (600 for a 600 USDT spread on BTC/USDT).")
    increment: Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]] = Field(description="Price difference between two orders of the same side. Denominated in the quote currency (200 for a 200 USDT spread on BTC/USDT).")
    buy_count: Union[Annotated[float, Field(strict=True, ge=1)], Annotated[int, Field(strict=True, ge=1)]] = Field(description="Number of initial buy orders to create. Make sure to have enough funds to create that many orders.")
    sell_count: Union[Annotated[float, Field(strict=True, ge=1)], Annotated[int, Field(strict=True, ge=1)]] = Field(description="Number of initial sell orders to create. Make sure to have enough funds to create that many orders.")
    enable_trailing_up: StrictBool
    enable_trailing_down: StrictBool
    order_by_order_trailing: StrictBool
    __properties: ClassVar[List[str]] = ["configuration_type", "symbol", "spread", "increment", "buy_count", "sell_count", "enable_trailing_up", "enable_trailing_down", "order_by_order_trailing"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GridConfiguration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GridConfiguration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "configuration_type": obj.get("configuration_type"),
            "symbol": obj.get("symbol"),
            "spread": obj.get("spread"),
            "increment": obj.get("increment"),
            "buy_count": obj.get("buy_count"),
            "sell_count": obj.get("sell_count"),
            "enable_trailing_up": obj.get("enable_trailing_up") if obj.get("enable_trailing_up") is not None else True,
            "enable_trailing_down": obj.get("enable_trailing_down") if obj.get("enable_trailing_down") is not None else False,
            "order_by_order_trailing": obj.get("order_by_order_trailing") if obj.get("order_by_order_trailing") is not None else True
        })
        return _obj


