# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Union
from typing_extensions import Annotated
from octobot_protocol.models.action_configuration_type import ActionConfigurationType
from octobot_protocol.models.index_coin import IndexCoin
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class IndexConfiguration(BaseModel):
    """
    IndexConfiguration
    """ # noqa: E501
    configuration_type: ActionConfigurationType = Field(description="index")
    coins: List[IndexCoin]
    rebalance_trigger_min_percent: Union[Annotated[float, Field(le=100, strict=True, ge=0)], Annotated[int, Field(le=100, strict=True, ge=0)]]
    __properties: ClassVar[List[str]] = ["configuration_type", "coins", "rebalance_trigger_min_percent"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IndexConfiguration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in coins (list)
        _items = []
        if self.coins:
            for _item_coins in self.coins:
                if _item_coins:
                    _items.append(_item_coins.to_dict())
            _dict['coins'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IndexConfiguration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "configuration_type": obj.get("configuration_type"),
            "coins": [IndexCoin.from_dict(_item) for _item in obj["coins"]] if obj.get("coins") is not None else None,
            "rebalance_trigger_min_percent": obj.get("rebalance_trigger_min_percent")
        })
        return _obj


