# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from octobot_protocol.models.market_making_funds_distribution import MarketMakingFundsDistribution
from octobot_protocol.models.market_making_hedging_engine import MarketMakingHedgingEngine
from octobot_protocol.models.market_making_order_book_depth import MarketMakingOrderBookDepth
from octobot_protocol.models.market_making_orders_distribution import MarketMakingOrdersDistribution
from octobot_protocol.models.market_making_reference_pair import MarketMakingReferencePair
from octobot_protocol.models.market_making_scheduled_volume import MarketMakingScheduledVolume
from octobot_protocol.models.market_making_stop_conditions import MarketMakingStopConditions
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MarketMakingSymbolConfiguration(BaseModel):
    """
    MarketMakingSymbolConfiguration
    """ # noqa: E501
    trading_pair: StrictStr
    reference_price: Annotated[List[MarketMakingReferencePair], Field(min_length=1)]
    min_spread: Union[Annotated[float, Field(strict=True, gt=0)], Annotated[int, Field(strict=True, gt=0)]] = Field(description="Minimum spread as a percentage (e.g. 0.5 for 0.5%).")
    max_spread: Union[Annotated[float, Field(strict=True, gt=0)], Annotated[int, Field(strict=True, gt=0)]] = Field(description="Maximum spread as a percentage.")
    order_book_depth: Optional[MarketMakingOrderBookDepth] = None
    scheduled_volume: Optional[MarketMakingScheduledVolume] = None
    stop_conditions: Optional[MarketMakingStopConditions] = None
    bids_count: Union[Annotated[float, Field(strict=True, ge=1)], Annotated[int, Field(strict=True, ge=1)]]
    asks_count: Union[Annotated[float, Field(strict=True, ge=1)], Annotated[int, Field(strict=True, ge=1)]]
    orders_distribution: MarketMakingOrdersDistribution
    funds_distribution: MarketMakingFundsDistribution
    exchange: StrictStr
    max_base_budget: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="0 means unlimited when supported.")
    max_quote_budget: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="0 means unlimited when supported.")
    min_base_budget: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = None
    min_quote_budget: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = None
    hedging_engine: Optional[MarketMakingHedgingEngine] = None
    __properties: ClassVar[List[str]] = ["trading_pair", "reference_price", "min_spread", "max_spread", "order_book_depth", "scheduled_volume", "stop_conditions", "bids_count", "asks_count", "orders_distribution", "funds_distribution", "exchange", "max_base_budget", "max_quote_budget", "min_base_budget", "min_quote_budget", "hedging_engine"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MarketMakingSymbolConfiguration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in reference_price (list)
        _items = []
        if self.reference_price:
            for _item_reference_price in self.reference_price:
                if _item_reference_price:
                    _items.append(_item_reference_price.to_dict())
            _dict['reference_price'] = _items
        # override the default output from pydantic by calling `to_dict()` of order_book_depth
        if self.order_book_depth:
            _dict['order_book_depth'] = self.order_book_depth.to_dict()
        # override the default output from pydantic by calling `to_dict()` of scheduled_volume
        if self.scheduled_volume:
            _dict['scheduled_volume'] = self.scheduled_volume.to_dict()
        # override the default output from pydantic by calling `to_dict()` of stop_conditions
        if self.stop_conditions:
            _dict['stop_conditions'] = self.stop_conditions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of hedging_engine
        if self.hedging_engine:
            _dict['hedging_engine'] = self.hedging_engine.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MarketMakingSymbolConfiguration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "trading_pair": obj.get("trading_pair"),
            "reference_price": [MarketMakingReferencePair.from_dict(_item) for _item in obj["reference_price"]] if obj.get("reference_price") is not None else None,
            "min_spread": obj.get("min_spread"),
            "max_spread": obj.get("max_spread"),
            "order_book_depth": MarketMakingOrderBookDepth.from_dict(obj["order_book_depth"]) if obj.get("order_book_depth") is not None else None,
            "scheduled_volume": MarketMakingScheduledVolume.from_dict(obj["scheduled_volume"]) if obj.get("scheduled_volume") is not None else None,
            "stop_conditions": MarketMakingStopConditions.from_dict(obj["stop_conditions"]) if obj.get("stop_conditions") is not None else None,
            "bids_count": obj.get("bids_count"),
            "asks_count": obj.get("asks_count"),
            "orders_distribution": obj.get("orders_distribution"),
            "funds_distribution": obj.get("funds_distribution"),
            "exchange": obj.get("exchange"),
            "max_base_budget": obj.get("max_base_budget"),
            "max_quote_budget": obj.get("max_quote_budget"),
            "min_base_budget": obj.get("min_base_budget"),
            "min_quote_budget": obj.get("min_quote_budget"),
            "hedging_engine": MarketMakingHedgingEngine.from_dict(obj["hedging_engine"]) if obj.get("hedging_engine") is not None else None
        })
        return _obj


