# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MarketMakingHedgingEngine(BaseModel):
    """
    Optional cross-exchange hedging configuration.
    """ # noqa: E501
    average_price_counted_minutes: Optional[Union[Annotated[float, Field(strict=True, ge=1)], Annotated[int, Field(strict=True, ge=1)]]] = 60
    hedging_engine_type: Optional[StrictStr] = None
    hedging_exchange: Optional[StrictStr] = None
    hedging_max_loss_threshold: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = 0
    hedging_profit_threshold: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = 0
    max_negative_percent_price_change: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = 0
    max_positive_percent_price_change: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = 0
    __properties: ClassVar[List[str]] = ["average_price_counted_minutes", "hedging_engine_type", "hedging_exchange", "hedging_max_loss_threshold", "hedging_profit_threshold", "max_negative_percent_price_change", "max_positive_percent_price_change"]

    @field_validator('hedging_engine_type')
    def hedging_engine_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['spot', 'perpetual_futures']):
            raise ValueError("must be one of enum values ('spot', 'perpetual_futures')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MarketMakingHedgingEngine from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MarketMakingHedgingEngine from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "average_price_counted_minutes": obj.get("average_price_counted_minutes") if obj.get("average_price_counted_minutes") is not None else 60,
            "hedging_engine_type": obj.get("hedging_engine_type"),
            "hedging_exchange": obj.get("hedging_exchange"),
            "hedging_max_loss_threshold": obj.get("hedging_max_loss_threshold") if obj.get("hedging_max_loss_threshold") is not None else 0,
            "hedging_profit_threshold": obj.get("hedging_profit_threshold") if obj.get("hedging_profit_threshold") is not None else 0,
            "max_negative_percent_price_change": obj.get("max_negative_percent_price_change") if obj.get("max_negative_percent_price_change") is not None else 0,
            "max_positive_percent_price_change": obj.get("max_positive_percent_price_change") if obj.get("max_positive_percent_price_change") is not None else 0
        })
        return _obj


