# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from octobot_protocol.models.cancel_policy import CancelPolicy
from octobot_protocol.models.order_group import OrderGroup
from octobot_protocol.models.order_status import OrderStatus
from octobot_protocol.models.order_type import OrderType
from octobot_protocol.models.side import Side
from octobot_protocol.models.trailing_profile import TrailingProfile
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Order(BaseModel):
    """
    Order
    """ # noqa: E501
    id: StrictStr
    symbol: StrictStr
    price: Union[StrictFloat, StrictInt]
    quantity: Union[StrictFloat, StrictInt]
    filled: Union[StrictFloat, StrictInt]
    exchange_id: StrictStr
    side: Side
    type: OrderType
    trigger_above: Optional[StrictBool] = None
    reduce_only: Optional[StrictBool] = None
    is_active: Optional[StrictBool] = None
    status: OrderStatus
    created_at: datetime
    entries: Optional[List[StrictStr]] = None
    update_with_triggering_order_fees: Optional[StrictBool] = None
    order_group: Optional[OrderGroup] = None
    trailing_profile: Optional[TrailingProfile] = None
    cancel_policy: Optional[CancelPolicy] = None
    chained_orders: Optional[List[Order]] = None
    __properties: ClassVar[List[str]] = ["id", "symbol", "price", "quantity", "filled", "exchange_id", "side", "type", "trigger_above", "reduce_only", "is_active", "status", "created_at", "entries", "update_with_triggering_order_fees", "order_group", "trailing_profile", "cancel_policy", "chained_orders"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Order from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of order_group
        if self.order_group:
            _dict['order_group'] = self.order_group.to_dict()
        # override the default output from pydantic by calling `to_dict()` of trailing_profile
        if self.trailing_profile:
            _dict['trailing_profile'] = self.trailing_profile.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cancel_policy
        if self.cancel_policy:
            _dict['cancel_policy'] = self.cancel_policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in chained_orders (list)
        _items = []
        if self.chained_orders:
            for _item_chained_orders in self.chained_orders:
                if _item_chained_orders:
                    _items.append(_item_chained_orders.to_dict())
            _dict['chained_orders'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Order from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "symbol": obj.get("symbol"),
            "price": obj.get("price"),
            "quantity": obj.get("quantity"),
            "filled": obj.get("filled"),
            "exchange_id": obj.get("exchange_id"),
            "side": obj.get("side"),
            "type": obj.get("type"),
            "trigger_above": obj.get("trigger_above"),
            "reduce_only": obj.get("reduce_only"),
            "is_active": obj.get("is_active"),
            "status": obj.get("status"),
            "created_at": obj.get("created_at"),
            "entries": obj.get("entries"),
            "update_with_triggering_order_fees": obj.get("update_with_triggering_order_fees"),
            "order_group": OrderGroup.from_dict(obj["order_group"]) if obj.get("order_group") is not None else None,
            "trailing_profile": TrailingProfile.from_dict(obj["trailing_profile"]) if obj.get("trailing_profile") is not None else None,
            "cancel_policy": CancelPolicy.from_dict(obj["cancel_policy"]) if obj.get("cancel_policy") is not None else None,
            "chained_orders": [Order.from_dict(_item) for _item in obj["chained_orders"]] if obj.get("chained_orders") is not None else None
        })
        return _obj

# TODO: Rewrite to not use raise_errors
Order.model_rebuild(raise_errors=False)

