# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from octobot_protocol.models.user_action_configuration import UserActionConfiguration
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ProposedActionEntry(BaseModel):
    """
    One built-but-unsent action inside a proposal. after: 'previous-confirmed' marks an action that must not be appended until the prior entry in the array has been confirmed by the node (e.g. automation_create's strategy_create -> automation_create race). A privileged executor must honor this ordering; a read-only proposer never appends anything itself, so it just carries the constraint as data.
    """ # noqa: E501
    configuration: UserActionConfiguration
    after: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["configuration", "after"]

    @field_validator('after')
    def after_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['previous-confirmed']):
            raise ValueError("must be one of enum values ('previous-confirmed')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProposedActionEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of configuration
        if self.configuration:
            _dict['configuration'] = self.configuration.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProposedActionEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "configuration": UserActionConfiguration.from_dict(obj["configuration"]) if obj.get("configuration") is not None else None,
            "after": obj.get("after")
        })
        return _obj


