# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class UserActionType(str, Enum):
    """
    UserActionType
    """

    """
    allowed enum values
    """
    AUTOMATION_CREATE = 'automation_create'
    AUTOMATION_EDIT = 'automation_edit'
    AUTOMATION_STOP = 'automation_stop'
    ACCOUNT_CREATE = 'account_create'
    ACCOUNT_EDIT = 'account_edit'
    ACCOUNT_DELETE = 'account_delete'
    ACCOUNTS_REFRESH = 'accounts_refresh'
    EXCHANGE_CONFIG_CREATE = 'exchange_config_create'
    EXCHANGE_CONFIG_EDIT = 'exchange_config_edit'
    EXCHANGE_CONFIG_DELETE = 'exchange_config_delete'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UserActionType from a JSON string"""
        return cls(json.loads(json_str))


