import decimal

import octobot_trading.personal_data as personal_data


def minimal_order_amount(symbol):
    return BYBIT_SYMBOLS_LIMIT_MIN_AMOUNT_EXTRACT[symbol]


def max_digits(symbol):
    return BYBIT_SYMBOLS_AMOUNT_MAX_DIGITS_EXTRACT[symbol]


def adapt_digits(symbol, value):
    if value is not None:
        return personal_data.decimal_trunc_with_n_decimal_digits(
            decimal.Decimal(str(value)),
            decimal.Decimal(str(max_digits(symbol))),
            truncate=True
        )
    return value


# todo remove when symbol market status in backtesting data files
# extract from nov 2 2022
BYBIT_SYMBOLS_LIMIT_MIN_AMOUNT_EXTRACT = {
    "1INCH/USDT:USDT": 0.1, "AAVE/USDT:USDT": 0.01, "ACH/USDT:USDT": 10.0, "ADA/USD:ADA": 1.0, "ADA/USDT:USDT": 1.0,
    "AGLD/USDT:USDT": 0.1, "AKRO/USDT:USDT": 100.0, "ALGO/USDT:USDT": 0.1, "ALICE/USDT:USDT": 0.1,
    "ALPHA/USDT:USDT": 1.0,
    "ANKR/USDT:USDT": 1.0, "ANT/USDT:USDT": 0.1, "APE/USDT:USDT": 0.1, "API3/USDT:USDT": 0.1, "APT/USDT:USDT": 0.01,
    "ARPA/USDT:USDT": 10.0, "AR/USDT:USDT": 0.1, "ASTR/USDT:USDT": 1.0, "ATOM/USDT:USDT": 0.1, "AUDIO/USDT:USDT": 0.1,
    "AVAX/USDT:USDT": 0.1, "AXS/USDT:USDT": 0.1, "BAKE/USDT:USDT": 0.1, "BAL/USDT:USDT": 0.01, "BAND/USDT:USDT": 0.1,
    "BAT/USDT:USDT": 0.1, "BCH/USDT:USDT": 0.01, "BEL/USDT:USDT": 1.0, "BICO/USDT:USDT": 0.1, "BIT/USD:BIT": 1.0,
    "BIT/USDT:USDT": 0.1, "BLZ/USDT:USDT": 1.0, "BNB/USDT:USDT": 0.01, "BNX/USDT:USDT": 0.01, "BOBA/USDT:USDT": 0.1,
    "BSV/USDT:USDT": 0.01, "BSW/USDT:USDT": 1.0, "BTC/USD:BTC": 1.0, "BTC/USDT:USDT": 0.001, "C98/USDT:USDT": 0.1,
    "CEEK/USDT:USDT": 1.0, "CELO/USDT:USDT": 0.1, "CELR/USDT:USDT": 1.0, "CHR/USDT:USDT": 0.1, "CHZ/USDT:USDT": 1.0,
    "CKB/USDT:USDT": 10.0, "COMP/USDT:USDT": 0.01, "COTI/USDT:USDT": 1.0, "CREAM/USDT:USDT": 0.01, "CRO/USDT:USDT": 1.0,
    "CRV/USDT:USDT": 0.1, "CTC/USDT:USDT": 1.0, "CTK/USDT:USDT": 0.1, "CTSI/USDT:USDT": 1.0, "CVC/USDT:USDT": 1.0,
    "CVX/USDT:USDT": 0.01, "DAR/USDT:USDT": 0.1, "DASH/USDT:USDT": 0.01, "DENT/USDT:USDT": 100.0, "DGB/USDT:USDT": 10.0,
    "DODO/USDT:USDT": 1.0, "DOGE/USDT:USDT": 1.0, "DOT/USD:DOT": 1.0, "DOT/USDT:USDT": 0.1, "DUSK/USDT:USDT": 1.0,
    "DYDX/USDT:USDT": 0.1, "EGLD/USDT:USDT": 0.01, "ENJ/USDT:USDT": 0.1, "ENS/USDT:USDT": 0.1, "EOS/USD:EOS": 1.0,
    "EOS/USDT:USDT": 0.1, "ETC/USDT:USDT": 0.1, "ETH/USD:ETH": 1.0, "ETH/USDT:USDT": 0.01, "ETHW/USDT:USDT": 0.01,
    "FIL/USDT:USDT": 0.1, "FITFI/USDT:USDT": 1.0, "FLM/USDT:USDT": 1.0, "FLOW/USDT:USDT": 0.1, "FTM/USDT:USDT": 1.0,
    "FTT/USDT:USDT": 0.1, "FXS/USDT:USDT": 0.01, "GALA/USDT:USDT": 1.0, "GAL/USDT:USDT": 0.01, "GLMR/USDT:USDT": 0.1,
    "GMT/USDT:USDT": 1.0, "GMX/USDT:USDT": 0.01, "GRT/USDT:USDT": 0.1, "GTC/USDT:USDT": 0.1, "HBAR/USDT:USDT": 1.0,
    "HNT/USDT:USDT": 0.01, "HOT/USDT:USDT": 100.0, "ICP/USDT:USDT": 0.1, "ICX/USDT:USDT": 1.0, "ILV/USDT:USDT": 0.01,
    "IMX/USDT:USDT": 0.1, "INJ/USDT:USDT": 0.1, "IOST/USDT:USDT": 1.0, "IOTA/USDT:USDT": 0.1, "IOTX/USDT:USDT": 1.0,
    "JASMY/USDT:USDT": 1.0, "JST/USDT:USDT": 10.0, "KAVA/USDT:USDT": 0.1, "KDA/USDT:USDT": 0.1, "KLAY/USDT:USDT": 0.1,
    "KNC/USDT:USDT": 0.1, "KSM/USDT:USDT": 0.01, "LDO/USDT:USDT": 0.1, "LINA/USDT:USDT": 10.0, "LINK/USDT:USDT": 0.1,
    "LIT/USDT:USDT": 0.1, "LOOKS/USDT:USDT": 0.1, "LPT/USDT:USDT": 0.1, "LRC/USDT:USDT": 0.1, "LTC/USD:LTC": 1.0,
    "LTC/USDT:USDT": 0.1, "LUNA2/USDT:USDT": 0.1, "MANA/USD:MANA": 1.0, "MANA/USDT:USDT": 0.1, "MASK/USDT:USDT": 0.1,
    "MATIC/USDT:USDT": 1.0, "MINA/USDT:USDT": 0.1, "MKR/USDT:USDT": 0.001, "MTL/USDT:USDT": 0.1, "NEAR/USDT:USDT": 0.1,
    "NEO/USDT:USDT": 0.01, "OCEAN/USDT:USDT": 1.0, "OGN/USDT:USDT": 1.0, "OMG/USDT:USDT": 0.1, "ONE/USDT:USDT": 1.0,
    "ONT/USDT:USDT": 1.0, "OP/USDT:USDT": 0.1, "PAXG/USDT:USDT": 0.001, "PEOPLE/USDT:USDT": 1.0, "QTUM/USDT:USDT": 0.1,
    "RAY/USDT:USDT": 0.1, "REEF/USDT:USDT": 10.0, "REN/USDT:USDT": 0.1, "REQ/USDT:USDT": 1.0, "RNDR/USDT:USDT": 0.1,
    "ROSE/USDT:USDT": 1.0, "RSR/USDT:USDT": 10.0, "RSS3/USDT:USDT": 1.0, "RUNE/USDT:USDT": 0.1, "RVN/USDT:USDT": 1.0,
    "SAND/USDT:USDT": 1.0, "SCRT/USDT:USDT": 0.1, "SC/USDT:USDT": 10.0, "SFP/USDT:USDT": 0.1, "SKL/USDT:USDT": 1.0,
    "SLP/USDT:USDT": 10.0, "SNX/USDT:USDT": 0.1, "SOL/USD:SOL": 1.0, "SOL/USDT:USDT": 0.1, "SPELL/USDT:USDT": 10.0,
    "SRM/USDT:USDT": 0.1, "STG/USDT:USDT": 0.1, "STMX/USDT:USDT": 10.0, "STORJ/USDT:USDT": 0.1, "STX/USDT:USDT": 0.1,
    "SUN/USDT:USDT": 10.0, "SUSHI/USDT:USDT": 0.1, "SXP/USDT:USDT": 0.1, "THETA/USDT:USDT": 0.1, "TLM/USDT:USDT": 1.0,
    "TOMO/USDT:USDT": 0.1, "TRB/USDT:USDT": 0.01, "TRX/USDT:USDT": 1.0, "UNFI/USDT:USDT": 0.1, "UNI/USDT:USDT": 0.1,
    "USDC/USDT:USDT": 0.1, "VET/USDT:USDT": 1.0, "WAVES/USDT:USDT": 0.1, "WOO/USDT:USDT": 0.1, "XCN/USDT:USDT": 10.0,
    "XEM/USDT:USDT": 1.0, "XLM/USDT:USDT": 1.0, "XMR/USDT:USDT": 0.01, "XNO/USDT:USDT": 1.0, "XRP/USD:XRP": 1.0,
    "XRP/USDT:USDT": 1.0, "XTZ/USDT:USDT": 0.1, "YFI/USDT:USDT": 0.0001, "YGG/USDT:USDT": 0.1, "ZEC/USDT:USDT": 0.01,
    "ZEN/USDT:USDT": 0.1, "ZIL/USDT:USDT": 10.0, "ZRX/USDT:USDT": 1.0, "BTC/USD:USDC": 0.001, "ETC/USD:USDC": 0.1,
    "MATIC/USD:USDC": 1.0, "OP/USD:USDC": 1.0, "ETH/USD:USDC": 0.01, "GMT/USD:USDC": 1.0, "ADA/USD:USDC": 1.0,
    "AVAX/USD:USDC": 0.01, "SOL/USD:USDC": 0.1, "XRP/USD:USDC": 1.0, "SAND/USD:USDC": 1.0, "APE/USD:USDC": 0.1,
    "SWEAT/USD:USDC": 100.0, "ATOM/USD:USDC": 0.1, "EOS/USD:USDC": 0.1, "CHZ/USD:USDC": 1.0, "NEAR/USD:USDC": 0.1,
    "BNB/USD:USDC": 0.01, "LDO/USD:USDC": 0.1, "LUNA/USD:USDC": 0.1, "APT/USD:USDC": 0.01}

BYBIT_SYMBOLS_AMOUNT_MAX_DIGITS_EXTRACT = {
    "1INCH/USDT:USDT": 1, "AAVE/USDT:USDT": 2, "ACH/USDT:USDT": 1,
    "ADA/USD:ADA": 0, "ADA/USDT:USDT": 0, "AGLD/USDT:USDT": 1,
    "AKRO/USDT:USDT": 2, "ALGO/USDT:USDT": 1, "ALICE/USDT:USDT": 1,
    "ALPHA/USDT:USDT": 0, "ANKR/USDT:USDT": 0, "ANT/USDT:USDT": 1,
    "APE/USDT:USDT": 1, "API3/USDT:USDT": 1, "APT/USDT:USDT": 2,
    "ARPA/USDT:USDT": 1, "AR/USDT:USDT": 1, "ASTR/USDT:USDT": 0,
    "ATOM/USDT:USDT": 1, "AUDIO/USDT:USDT": 1, "AVAX/USDT:USDT": 1,
    "AXS/USDT:USDT": 1, "BAKE/USDT:USDT": 1, "BAL/USDT:USDT": 2,
    "BAND/USDT:USDT": 1, "BAT/USDT:USDT": 1, "BCH/USDT:USDT": 2,
    "BEL/USDT:USDT": 0, "BICO/USDT:USDT": 1, "BIT/USD:BIT": 0,
    "BIT/USDT:USDT": 1, "BLZ/USDT:USDT": 0, "BNB/USDT:USDT": 2,
    "BNX/USDT:USDT": 2, "BOBA/USDT:USDT": 1, "BSV/USDT:USDT": 2,
    "BSW/USDT:USDT": 0, "BTC/USD:BTC": 0, "BTC/USDT:USDT": 3, "C98/USDT:USDT": 1,
    "CEEK/USDT:USDT": 0, "CELO/USDT:USDT": 1, "CELR/USDT:USDT": 0,
    "CHR/USDT:USDT": 1, "CHZ/USDT:USDT": 0, "CKB/USDT:USDT": 1,
    "COMP/USDT:USDT": 2, "COTI/USDT:USDT": 0, "CREAM/USDT:USDT": 2,
    "CRO/USDT:USDT": 0, "CRV/USDT:USDT": 1, "CTC/USDT:USDT": 0,
    "CTK/USDT:USDT": 1, "CTSI/USDT:USDT": 0, "CVC/USDT:USDT": 0,
    "CVX/USDT:USDT": 2, "DAR/USDT:USDT": 1, "DASH/USDT:USDT": 2,
    "DENT/USDT:USDT": 2, "DGB/USDT:USDT": 1, "DODO/USDT:USDT": 0,
    "DOGE/USDT:USDT": 0, "DOT/USD:DOT": 0, "DOT/USDT:USDT": 1,
    "DUSK/USDT:USDT": 0, "DYDX/USDT:USDT": 1, "EGLD/USDT:USDT": 2,
    "ENJ/USDT:USDT": 1, "ENS/USDT:USDT": 1, "EOS/USD:EOS": 0, "EOS/USDT:USDT": 1,
    "ETC/USDT:USDT": 1, "ETH/USD:ETH": 0, "ETH/USDT:USDT": 2,
    "ETHW/USDT:USDT": 2, "FIL/USDT:USDT": 1, "FITFI/USDT:USDT": 0,
    "FLM/USDT:USDT": 0, "FLOW/USDT:USDT": 1, "FTM/USDT:USDT": 0,
    "FTT/USDT:USDT": 1, "FXS/USDT:USDT": 2, "GALA/USDT:USDT": 0,
    "GAL/USDT:USDT": 2, "GLMR/USDT:USDT": 1, "GMT/USDT:USDT": 0,
    "GMX/USDT:USDT": 2, "GRT/USDT:USDT": 1, "GTC/USDT:USDT": 1,
    "HBAR/USDT:USDT": 0, "HNT/USDT:USDT": 2, "HOT/USDT:USDT": 2,
    "ICP/USDT:USDT": 1, "ICX/USDT:USDT": 0, "ILV/USDT:USDT": 2,
    "IMX/USDT:USDT": 1, "INJ/USDT:USDT": 1, "IOST/USDT:USDT": 0,
    "IOTA/USDT:USDT": 1, "IOTX/USDT:USDT": 0, "JASMY/USDT:USDT": 0,
    "JST/USDT:USDT": 1, "KAVA/USDT:USDT": 1, "KDA/USDT:USDT": 1,
    "KLAY/USDT:USDT": 1, "KNC/USDT:USDT": 1, "KSM/USDT:USDT": 2,
    "LDO/USDT:USDT": 1, "LINA/USDT:USDT": 1, "LINK/USDT:USDT": 1,
    "LIT/USDT:USDT": 1, "LOOKS/USDT:USDT": 1, "LPT/USDT:USDT": 1,
    "LRC/USDT:USDT": 1, "LTC/USD:LTC": 0, "LTC/USDT:USDT": 1,
    "LUNA2/USDT:USDT": 1, "MANA/USD:MANA": 0, "MANA/USDT:USDT": 1,
    "MASK/USDT:USDT": 1, "MATIC/USDT:USDT": 0, "MINA/USDT:USDT": 1,
    "MKR/USDT:USDT": 3, "MTL/USDT:USDT": 1, "NEAR/USDT:USDT": 1,
    "NEO/USDT:USDT": 2, "OCEAN/USDT:USDT": 0, "OGN/USDT:USDT": 0,
    "OMG/USDT:USDT": 1, "ONE/USDT:USDT": 0, "ONT/USDT:USDT": 0,
    "OP/USDT:USDT": 1, "PAXG/USDT:USDT": 3, "PEOPLE/USDT:USDT": 0,
    "QTUM/USDT:USDT": 1, "RAY/USDT:USDT": 1, "REEF/USDT:USDT": 1,
    "REN/USDT:USDT": 1, "REQ/USDT:USDT": 0, "RNDR/USDT:USDT": 1,
    "ROSE/USDT:USDT": 0, "RSR/USDT:USDT": 1, "RSS3/USDT:USDT": 0,
    "RUNE/USDT:USDT": 1, "RVN/USDT:USDT": 0, "SAND/USDT:USDT": 0,
    "SCRT/USDT:USDT": 1, "SC/USDT:USDT": 1, "SFP/USDT:USDT": 1,
    "SKL/USDT:USDT": 0, "SLP/USDT:USDT": 1, "SNX/USDT:USDT": 1, "SOL/USD:SOL": 0,
    "SOL/USDT:USDT": 1, "SPELL/USDT:USDT": 1, "SRM/USDT:USDT": 1,
    "STG/USDT:USDT": 1, "STMX/USDT:USDT": 1, "STORJ/USDT:USDT": 1,
    "STX/USDT:USDT": 1, "SUN/USDT:USDT": 1, "SUSHI/USDT:USDT": 1,
    "SXP/USDT:USDT": 1, "THETA/USDT:USDT": 1, "TLM/USDT:USDT": 0,
    "TOMO/USDT:USDT": 1, "TRB/USDT:USDT": 2, "TRX/USDT:USDT": 0,
    "UNFI/USDT:USDT": 1, "UNI/USDT:USDT": 1, "USDC/USDT:USDT": 1,
    "VET/USDT:USDT": 0, "WAVES/USDT:USDT": 1, "WOO/USDT:USDT": 1,
    "XCN/USDT:USDT": 1, "XEM/USDT:USDT": 0, "XLM/USDT:USDT": 0,
    "XMR/USDT:USDT": 2, "XNO/USDT:USDT": 0, "XRP/USD:XRP": 0, "XRP/USDT:USDT": 0,
    "XTZ/USDT:USDT": 1, "YFI/USDT:USDT": 4, "YGG/USDT:USDT": 1,
    "ZEC/USDT:USDT": 2, "ZEN/USDT:USDT": 1, "ZIL/USDT:USDT": 1,
    "ZRX/USDT:USDT": 0, "BTC/USD:USDC": 3, "ETC/USD:USDC": 1,
    "MATIC/USD:USDC": 0, "OP/USD:USDC": 0, "ETH/USD:USDC": 2, "GMT/USD:USDC": 0,
    "ADA/USD:USDC": 0, "AVAX/USD:USDC": 2, "SOL/USD:USDC": 1, "XRP/USD:USDC": 0,
    "SAND/USD:USDC": 0, "APE/USD:USDC": 1, "SWEAT/USD:USDC": 2,
    "ATOM/USD:USDC": 1, "EOS/USD:USDC": 1, "CHZ/USD:USDC": 0, "NEAR/USD:USDC": 1,
    "BNB/USD:USDC": 2, "LDO/USD:USDC": 1, "LUNA/USD:USDC": 1, "APT/USD:USDC": 2}
