---
kind: pipeline
name: tests-python3.8-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: tests
  image: python:3.8
  environment:
    OCTOBOT_PYPI_URL:
      from_secret: OCTOBOT_PYPI_URL
    DRONE_CLEANED_BRANCH: $${DRONE_SOURCE_BRANCH////_}
  commands:
    - pip install --extra-index-url $OCTOBOT_PYPI_URL --prefer-binary -r dev_requirements.txt -r requirements.txt
    - mkdir user
    - cp ./octobot/config/default_config.json ./user/config.json
    - TENTACLES_URL_SUBCATEGORY=dev/ TENTACLES_URL_TAG=$DRONE_CLEANED_BRANCH python3 start.py tentacles -q --install --all || python3 start.py tentacles --install --all
    - python3 setup.py install
    - pytest --cov=. --cov-config=.coveragerc --durations=0 -rw tests
    - pytest tentacles

---
kind: pipeline
name: tests-python3.8-arm32

platform:
  os: linux
  arch: arm

steps:
- name: tests
  image: python:3.8
  environment:
    OCTOBOT_PYPI_URL:
      from_secret: OCTOBOT_PYPI_URL
    DRONE_CLEANED_BRANCH: $${DRONE_SOURCE_BRANCH////_}
  commands:
    - pip install --extra-index-url https://www.piwheels.org/simple --extra-index-url $OCTOBOT_PYPI_URL --prefer-binary -r dev_requirements.txt -r requirements.txt
    - mkdir user
    - cp ./octobot/config/default_config.json ./user/config.json
    - TENTACLES_URL_SUBCATEGORY=dev/ TENTACLES_URL_TAG=$DRONE_CLEANED_BRANCH python3 start.py tentacles -q --install --all || python3 start.py tentacles --install --all
    - python3 setup.py install
    - pytest --cov=. --cov-config=.coveragerc --durations=0 -rw tests
    - pytest tentacles

---
kind: pipeline
name: deploy-python3.8-arm64

workspace:
  base: /project

platform:
  os: linux
  arch: arm64

steps:
- name: pypi_publish
  pull: always
  image: drakkarsoftware/pypi-builder:python-3.8-manylinux-aarch64
  environment:
    PYPI_USERNAME:
      from_secret: pypi_username
    PYPI_PASSWORD:
      from_secret: pypi_password
  when:
    event:
      - tag
    repo:
      - Drakkar-Software/OctoBot
