version: "3"

services:
  octobot:
    image: drakkarsoftware/octobot:stable
    volumes:
       - ./logs:/octobot/logs
       - ./backtesting:/octobot/backtesting
       - ./tentacles:/octobot/tentacles
       - ./user:/octobot/user
    ports:
       - 80:5001
    restart: always
