version: "3"

services:
  octobot:
    image: drakkarsoftware/octobot:stable
    volumes:
       - ./logs:/octobot/logs
       - ./backtesting:/octobot/backtesting
       - ./tentacles:/octobot/tentacles
       - ./user:/octobot/user
    ports:
       - ${NODE_PORT:-8000}:8000
       - ${PORT:-80}:${PORT:-5001}
       - ${CHILD_WEB_PORTS:-5001-5010}:5001-5010
    restart: always
  
  watchtower:
    image: containrrr/watchtower
    restart: always
    command: --cleanup --include-restarting
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
