---
apiVersion: v1
kind: Service
metadata:
  name: octobot-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
  selector:
    app: octobot
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: octobot-backtesting
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: octobot-tentacles
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: octobot-user
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: octobot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: octobot
  template:
    metadata:
      labels:
        app: octobot
    spec:
      containers:
      - name: octobot
        image: drakkarsoftware/octobot:stable
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        livenessProbe:
          tcpSocket:
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts:
        - mountPath: /octobot/logs
          name: logs
        - mountPath: /octobot/backtesting
          name: backtesting
        - mountPath: /octobot/tentacles
          name: tentacles
        - mountPath: /octobot/user
          name: user
      volumes:
      - name: logs
        emptyDir: {}
      - name: backtesting
        persistentVolumeClaim:
          claimName: octobot-backtesting
      - name: tentacles
        persistentVolumeClaim:
          claimName: octobot-tentacles
      - name: user
        persistentVolumeClaim:
          claimName: octobot-user
