services:
  octobot:
    public: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TENTACLES_URL_TAG=${OKTETO_GIT_BRANCH////_}
    replicas: 1
    ports:
      - 5001
    resources:
      cpu: 1
      memory: 3Gi
      storage: 1Gi
    volumes:
      - /octobot/user
      - /octobot/tentacles
