services:
  octobot:
    public: true
    image: $DOCKER_IMAGE
    environment:
      - TENTACLES_REPOSITORY=$TENTACLES_REPOSITORY
      - TENTACLES_URL_TAG=$TENTACLES_URL_TAG
    replicas: 1
    ports:
      - 5001
    resources:
      cpu: 1
      memory: 3Gi
      storage: 1Gi
    volumes:
      - /octobot/user
      - /octobot/tentacles
