packages:
  - "packages/commons/octobot-commons-ts"
  - "packages/protocol"
  - "packages/protocol/octobot-protocol-ts"
  - "packages/trading/octobot-trading-ts"
  - "packages/node/octobot-node-ts"
  - "packages/flow/octobot-flow-ts"
