import React, {type ReactNode} from 'react';
import Translate, {translate} from '@docusaurus/Translate';
import {
  LandingLayout,
  Hero,
  Section,
  StepList,
  FAQ,
  CTABand,
  TradingViewWidget,
  type Step,
} from '@site/src/components/landing';
import {
  FaqJsonLd,
  BreadcrumbsJsonLd,
  type FaqJsonLdItem,
} from '@site/src/components/seo';
import GlassCard from '@site/src/components/GlassCard';
import type {Cryptocurrency} from '../types';
import shared from '../styles.module.css';

/*
 * Per-coin DCA bot page — programmatic route /<slug>-dca-bot.
 *
 * Generated by the octobot-programmatic-pages plugin, gated on `crypto.whatIs`
 * (same gate as what-is-<slug>). Structurally distinct from the per-coin
 * trading-bot page: it is built around the recurring-buy idea — a setup
 * step list, the asset primer, a live chart and a DCA-focused FAQ — rather
 * than a strategy grid. No slug collision: exchanges do not emit -dca-bot.
 */

const CLOUD = 'https://www.octobot.cloud';

interface CoinDcaBotData {
  crypto: Cryptocurrency;
}

export default function CoinDcaBot({
  data,
}: {
  data: CoinDcaBotData;
}): ReactNode {
  const {crypto} = data;

  const steps: Step[] = [
    {
      title: translate({
        id: 'programmatic.coinDcaBot.steps.connect.title',
        message: 'Connect your exchange',
        description: 'DCA step title',
      }),
      description: translate(
        {
          id: 'programmatic.coinDcaBot.steps.connect.description',
          message:
            'Add a trade-only API key. Your {symbol} stays on your own exchange account — OctoBot never holds it.',
          description: 'DCA step description; {symbol} is the ticker',
        },
        {symbol: crypto.symbol},
      ),
    },
    {
      title: translate({
        id: 'programmatic.coinDcaBot.steps.schedule.title',
        message: 'Set amount and interval',
        description: 'DCA step title',
      }),
      description: translate(
        {
          id: 'programmatic.coinDcaBot.steps.schedule.description',
          message:
            'Choose how much {name} to buy and how often — hourly, daily, weekly, or your own cadence.',
          description: 'DCA step description; {name} is the coin name',
        },
        {name: crypto.name},
      ),
    },
    {
      title: translate({
        id: 'programmatic.coinDcaBot.steps.run.title',
        message: 'Let it run',
        description: 'DCA step title',
      }),
      description: translate(
        {
          id: 'programmatic.coinDcaBot.steps.run.description',
          message:
            'The bot places every {symbol} buy on time and logs each fill. Pause or adjust it whenever you want.',
          description: 'DCA step description; {symbol} is the ticker',
        },
        {symbol: crypto.symbol},
      ),
    },
  ];

  const faqItems: FaqJsonLdItem[] = [
    {
      question: translate(
        {
          id: 'programmatic.coinDcaBot.faq.what.question',
          message: 'What is a {name} DCA bot?',
          description: 'FAQ question; {name} is the coin name',
        },
        {name: crypto.name},
      ),
      answer: translate(
        {
          id: 'programmatic.coinDcaBot.faq.what.answer',
          message:
            'It is an automation that buys a fixed amount of {name} ({symbol}) at a fixed interval, so your average entry price no longer depends on when you remember to buy.',
          description:
            'FAQ answer; {name} is the coin name, {symbol} the ticker',
        },
        {name: crypto.name, symbol: crypto.symbol},
      ),
    },
    {
      question: translate({
        id: 'programmatic.coinDcaBot.faq.free.question',
        message: 'Is it free?',
        description: 'FAQ question',
      }),
      answer: translate({
        id: 'programmatic.coinDcaBot.faq.free.answer',
        message:
          'OctoBot is open source and free to self-host. You only ever pay your exchange its normal trading fees on each buy.',
        description: 'FAQ answer',
      }),
    },
    {
      question: translate(
        {
          id: 'programmatic.coinDcaBot.faq.change.question',
          message: 'Can I change or stop the schedule later?',
          description: 'FAQ question',
        },
      ),
      answer: translate(
        {
          id: 'programmatic.coinDcaBot.faq.change.answer',
          message:
            'Yes. The amount, interval and pair are all editable at any time, and the {name} bot can be paused without losing its history.',
          description: 'FAQ answer; {name} is the coin name',
        },
        {name: crypto.name},
      ),
    },
  ];

  const title = translate(
    {
      id: 'programmatic.coinDcaBot.layout.title',
      message: '{name} DCA bot',
      description: 'Page title; {name} is the coin name',
    },
    {name: crypto.name},
  );

  return (
    <LandingLayout
      title={title}
      description={translate(
        {
          id: 'programmatic.coinDcaBot.layout.description',
          message:
            'Dollar-cost average into {name} ({symbol}) with OctoBot — schedule recurring {symbol} buys and keep full custody of your funds.',
          description:
            'Page meta description; {name} is the coin name, {symbol} the ticker',
        },
        {name: crypto.name, symbol: crypto.symbol},
      )}>
      <FaqJsonLd items={faqItems} />
      <BreadcrumbsJsonLd
        trail={[{name: title, path: `/${crypto.slug}-dca-bot`}]}
      />
      <div className={shared.gridVeil} aria-hidden="true" />

      <Hero
        eyebrow={translate(
          {
            id: 'programmatic.coinDcaBot.hero.eyebrow',
            message: '{name} DCA bot',
            description: 'Hero eyebrow; {name} is the coin name',
          },
          {name: crypto.name},
        )}
        title={
          <Translate
            id="programmatic.coinDcaBot.hero.title"
            description="Hero title; {name} is a styled span with the coin name"
            values={{
              name: <span className="ng-text-gradient">{crypto.name}</span>,
            }}>
            {'Dollar-cost average into {name}'}
          </Translate>
        }
        subtitle={translate(
          {
            id: 'programmatic.coinDcaBot.hero.subtitle',
            message:
              'A {name} DCA bot places the same recurring buy for you, on schedule — so your average {symbol} entry price stops depending on timing. OctoBot runs it on your own exchange account.',
            description:
              'Hero subtitle; {name} is the coin name, {symbol} the ticker',
          },
          {name: crypto.name, symbol: crypto.symbol},
        )}
        actions={[
          {
            label: translate(
              {
                id: 'programmatic.coinDcaBot.hero.action.start',
                message: 'Start {symbol} DCA',
                description: 'Hero CTA label; {symbol} is the ticker',
              },
              {symbol: crypto.symbol},
            ),
            to: CLOUD,
          },
          {
            label: translate({
              id: 'programmatic.coinDcaBot.hero.action.guides',
              message: 'Read the guides',
              description: 'Hero secondary CTA label',
            }),
            to: '/guides/octobot',
            variant: 'ghost',
          },
        ]}
        meta={[
          {label: crypto.symbol, dot: true},
          {
            label: translate({
              id: 'programmatic.coinDcaBot.hero.meta.recurring',
              message: 'Recurring buys',
              description: 'Hero meta label',
            }),
          },
          {
            label: translate({
              id: 'programmatic.coinDcaBot.hero.meta.selfCustody',
              message: 'Self-custody',
              description: 'Hero meta label',
            }),
          },
        ]}
      />

      <Section
        eyebrow={translate({
          id: 'programmatic.coinDcaBot.how.eyebrow',
          message: 'How it works',
          description: 'Section eyebrow',
        })}
        title={translate(
          {
            id: 'programmatic.coinDcaBot.how.title',
            message: 'Set up {name} recurring buys in three steps',
            description: 'Section title; {name} is the coin name',
          },
          {name: crypto.name},
        )}>
        <StepList steps={steps} />
      </Section>

      <Section
        align="left"
        eyebrow={translate({
          id: 'programmatic.coinDcaBot.about.eyebrow',
          message: 'About the asset',
          description: 'Section eyebrow',
        })}
        title={translate(
          {
            id: 'programmatic.coinDcaBot.about.title',
            message: 'What is {name}?',
            description: 'Section title; {name} is the coin name',
          },
          {name: crypto.name},
        )}
        lead={translate({
          id: 'programmatic.coinDcaBot.about.lead',
          message: 'A quick primer on the asset you would be accumulating.',
          description: 'Section lead',
        })}>
        <GlassCard variant="strong" padded className={shared.panel}>
          <p className={shared.prose}>{crypto.whatIs}</p>
        </GlassCard>
      </Section>

      <Section
        eyebrow={translate({
          id: 'programmatic.coinDcaBot.price.eyebrow',
          message: 'Market',
          description: 'Section eyebrow',
        })}
        title={translate(
          {
            id: 'programmatic.coinDcaBot.price.title',
            message: '{name} price history',
            description: 'Section title; {name} is the coin name',
          },
          {name: crypto.name},
        )}
        lead={translate(
          {
            id: 'programmatic.coinDcaBot.price.lead',
            message:
              'The {symbol}/USDT market your recurring buys would average into.',
            description: 'Section lead; {symbol} is the ticker',
          },
          {symbol: crypto.symbol},
        )}>
        <div className={shared.chart}>
          <TradingViewWidget symbol={`BINANCE:${crypto.symbol}USDT`} />
        </div>
      </Section>

      <Section
        eyebrow={translate({
          id: 'programmatic.coinDcaBot.faq.eyebrow',
          message: 'FAQ',
          description: 'Section eyebrow',
        })}
        title={translate(
          {
            id: 'programmatic.coinDcaBot.faq.title',
            message: '{name} DCA bot FAQ',
            description: 'Section title; {name} is the coin name',
          },
          {name: crypto.name},
        )}>
        <FAQ items={faqItems} />
      </Section>

      <CTABand
        title={
          <Translate
            id="programmatic.coinDcaBot.cta.title"
            description="CTA band title; {name} is the coin name, {schedule} a styled span"
            values={{
              name: crypto.name,
              schedule: (
                <span className="ng-text-frost">
                  <Translate
                    id="programmatic.coinDcaBot.cta.titleSchedule"
                    description="CTA band title accent">
                    on a schedule.
                  </Translate>
                </span>
              ),
            }}>
            {'Buy {name} {schedule}'}
          </Translate>
        }
        description={translate(
          {
            id: 'programmatic.coinDcaBot.cta.description',
            message:
              'Create a free OctoBot, connect your exchange and schedule your first {name} buy.',
            description: 'CTA band description; {name} is the coin name',
          },
          {name: crypto.name},
        )}
        actions={[
          {
            label: translate({
              id: 'programmatic.coinDcaBot.cta.action.start',
              message: 'Get started',
              description: 'CTA band label',
            }),
            to: CLOUD,
          },
          {
            label: translate(
              {
                id: 'programmatic.coinDcaBot.cta.action.tradingBot',
                message: '{symbol} trading bot',
                description: 'CTA band secondary label; {symbol} is the ticker',
              },
              {symbol: crypto.symbol},
            ),
            to: `/${crypto.slug}-trading-bot`,
            variant: 'ghost',
          },
        ]}
      />
    </LandingLayout>
  );
}
