# Shared helpers for OctoBot Cursor Cloud shell scripts.
# shellcheck shell=bash

cloud_lib_init() {
    local script_name="$1"
    CLOUD_SCRIPT_NAME="$script_name"
    set -euo pipefail
    CLOUD_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    REPO_ROOT="$(cd "${CLOUD_LIB_DIR}/.." && pwd)"
    cd "${REPO_ROOT}"
    CLOUD_PROFILE="${OCTOBOT_CLOUD_PROFILE:-ci-tentacles}"
    CLOUD_LAST_LOG_TAIL=""
    trap 'cloud_err_trap' ERR
}

log_step() {
    local step_id="$1"
    local message="$2"
    echo "==> [${step_id}] ${message}"
}

die() {
    local step_id="$1"
    local message="$2"
    echo "OCTOBOT_CLOUD_FAILED script=${CLOUD_SCRIPT_NAME} step=${step_id} profile=${CLOUD_PROFILE} message=${message}" >&2
    if [[ -n "${CLOUD_LAST_LOG_TAIL}" && -f "${CLOUD_LAST_LOG_TAIL}" ]]; then
        echo "--- last command output (tail) ---" >&2
        tail -n 30 "${CLOUD_LAST_LOG_TAIL}" >&2 || true
    fi
    exit 1
}

cloud_err_trap() {
    local step_id="${CLOUD_TRAP_STEP:-ERR}"
    die "${step_id}" "command failed: ${BASH_COMMAND}"
}

cloud_profile_includes_layer() {
    local layer="$1"
    case "${CLOUD_PROFILE}" in
        package-only)
            [[ "${layer}" == "L1" || "${layer}" == "L2" || "${layer}" == "L3" ]] && return 0
            return 1
            ;;
        ci-tentacles)
            [[ "${layer}" == "L6" ]] && return 1
            return 0
            ;;
        ui-node-web)
            return 0
            ;;
        *)
            die "INIT" "unknown OCTOBOT_CLOUD_PROFILE=${CLOUD_PROFILE}"
            ;;
    esac
}

cloud_write_env_files() {
    log_step "ENV_FILES" "Writing .cursor/env.sh and .cursor/pythonpath.sh"
    cat >"${REPO_ROOT}/.cursor/env.sh" <<EOF
# Generated by cloud-install.sh — source before Python, OctoBot, pytest
export OCTOBOT_REPO_ROOT="${REPO_ROOT}"
export OCTOBOT_CLOUD_VENV="${REPO_ROOT}/.cursor/venv"
export PATH="\${OCTOBOT_CLOUD_VENV}/bin:\${PATH}"
export DISABLE_SENTRY=True
EOF
    cat >"${REPO_ROOT}/.cursor/pythonpath.sh" <<'EOF'
# For packages/node, packages/flow, packages/copy tests from repo root (matches CI)
export PYTHONPATH=".:${PYTHONPATH:-}"
EOF
}

cloud_tentacles_pack_and_install() {
    log_step "TENTACLES_PACK" "OctoBot tentacles pack from packages/tentacles"
    mkdir -p "${REPO_ROOT}/output"
    export ALLOW_UNSIGNED_TENTACLES=true
    # shellcheck disable=SC1091
    source "${REPO_ROOT}/.cursor/env.sh"
    # -p is package filename only; default output_dir is output/ (see main.yml tentacles install)
    OctoBot tentacles -d packages/tentacles -p any_platform.zip
    log_step "TENTACLES_INSTALL" "OctoBot tentacles install to repo root"
    OctoBot tentacles --install --location output/any_platform.zip --all
}

cloud_npm_client_build() {
    log_step "L4" "npm ci and build octobot_client_ts"
    npm ci
    npm run build -w packages/client/octobot_client_ts
}

cloud_node_web_interface_build() {
    local ui_dir="${REPO_ROOT}/packages/tentacles/Services/Interfaces/node_web_interface"
    log_step "L6" "npm ci and build node_web_interface"
    (cd "${ui_dir}" && npm ci && npm run build)
}
