/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* AccountAuthActionResultErrorMessage
*/
export type AccountAuthActionResultErrorMessage = 'account_auth_not_found' | 'invalid_configuration' | 'duplicate_item' | 'internal_error'
