/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountStatus } from '../models/AccountStatus';
import { AccountStatusMessage } from '../models/AccountStatusMessage';

/**
* AccountState
*/
export class AccountState {
    'status': AccountStatus;
    'message'?: AccountStatusMessage;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "AccountStatus",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "AccountStatusMessage",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AccountState.attributeTypeMap;
    }

    public constructor() {
    }
}


