/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Order } from '../models/Order';
import { Position } from '../models/Position';
import { Trade } from '../models/Trade';

/**
* AccountTrading
*/
export class AccountTrading {
    'updated_at': string;
    'orders'?: Array<Order>;
    'trades'?: Array<Trade>;
    'positions'?: Array<Position>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "updated_at",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "orders",
            "baseName": "orders",
            "type": "Array<Order>",
            "format": ""
        },
        {
            "name": "trades",
            "baseName": "trades",
            "type": "Array<Trade>",
            "format": ""
        },
        {
            "name": "positions",
            "baseName": "positions",
            "type": "Array<Position>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AccountTrading.attributeTypeMap;
    }

    public constructor() {
    }
}
