/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* AccountStatusMessage
*/
export type AccountStatusMessage = 'pending_validation' | 'valid' | 'invalid_api_keys' | 'missing_api_trading_rights' | 'revoke_api_withdrawal_rights' | 'invalid_api_ip_whitelist' | 'internal_server_error' | 'account_too_old' | 'incompatible_account_referral'
