/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* AccountAuthentication
*/
export class AccountAuthentication {
    'id': string;
    'updated_at'?: string;
    'api_key'?: string;
    'api_secret'?: string;
    'api_passphrase'?: string;
    'public_key'?: string;
    'private_key'?: string;
    'seed_phrase'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "updated_at",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "api_key",
            "baseName": "api_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "api_secret",
            "baseName": "api_secret",
            "type": "string",
            "format": ""
        },
        {
            "name": "api_passphrase",
            "baseName": "api_passphrase",
            "type": "string",
            "format": ""
        },
        {
            "name": "public_key",
            "baseName": "public_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "private_key",
            "baseName": "private_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "seed_phrase",
            "baseName": "seed_phrase",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AccountAuthentication.attributeTypeMap;
    }

    public constructor() {
    }
}
