/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Active order swap strategy class name (mirrors octobot_trading active_order_swap_strategy_factory).
*/
export type ActiveOrderSwapStrategyType = 'StopFirstActiveOrderSwapStrategy' | 'TakeProfitFirstActiveOrderSwapStrategy'
