/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ActiveOrderSwapStrategyType } from '../models/ActiveOrderSwapStrategyType';

/**
* ActiveOrderSwapStrategy
*/
export class ActiveOrderSwapStrategy {
    'type': ActiveOrderSwapStrategyType;
    'trigger_price_configuration'?: any;
    'timeout'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ActiveOrderSwapStrategyType",
            "format": ""
        },
        {
            "name": "trigger_price_configuration",
            "baseName": "trigger_price_configuration",
            "type": "any",
            "format": ""
        },
        {
            "name": "timeout",
            "baseName": "timeout",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ActiveOrderSwapStrategy.attributeTypeMap;
    }

    public constructor() {
    }
}


