/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountType } from '../models/AccountType';

/**
* A manually-entered, single tracked non-liquid asset (a watch, a car, real estate, and similar).
*/
export class AssetAccount {
    /**
    * asset
    */
    'account_type': 'asset';
    'asset_type'?: string;
    'cost_basis'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "account_type",
            "baseName": "account_type",
            "type": "AccountType",
            "format": ""
        },
        {
            "name": "asset_type",
            "baseName": "asset_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "cost_basis",
            "baseName": "cost_basis",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AssetAccount.attributeTypeMap;
    }

    public constructor() {
    }
}


