/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* AutomationActionResultErrorMessage
*/
export type AutomationActionResultErrorMessage = 'automation_not_found' | 'invalid_configuration' | 'invalid_automation_id' | 'strategy_not_found' | 'strategy_version_not_found' | 'unknown_trading_type' | 'ambiguous_trading_type' | 'ambiguous_exchange_config' | 'account_not_found' | 'account_authentication_details_not_found' | 'internal_error'
