/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Action } from '../models/Action';
import { AutomationMetadata } from '../models/AutomationMetadata';
import { DetailedAssetsForTradingType } from '../models/DetailedAssetsForTradingType';
import { OrderSummary } from '../models/OrderSummary';
import { PositionSummary } from '../models/PositionSummary';
import { TradeSummary } from '../models/TradeSummary';
import { WorkflowStatus } from '../models/WorkflowStatus';

/**
* AutomationState
*/
export class AutomationState {
    'id': string;
    'status': WorkflowStatus;
    'error'?: string;
    'error_message'?: string;
    'metadata': AutomationMetadata;
    'actions'?: Array<Action>;
    'priority_actions'?: Array<Action>;
    'exchanges'?: Array<string>;
    'exchange_account_ids'?: Array<string>;
    'assets'?: Array<DetailedAssetsForTradingType>;
    'orders'?: Array<OrderSummary>;
    'trades'?: Array<TradeSummary>;
    'positions'?: Array<PositionSummary>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "WorkflowStatus",
            "format": ""
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string",
            "format": ""
        },
        {
            "name": "error_message",
            "baseName": "error_message",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "AutomationMetadata",
            "format": ""
        },
        {
            "name": "actions",
            "baseName": "actions",
            "type": "Array<Action>",
            "format": ""
        },
        {
            "name": "priority_actions",
            "baseName": "priority_actions",
            "type": "Array<Action>",
            "format": ""
        },
        {
            "name": "exchanges",
            "baseName": "exchanges",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "exchange_account_ids",
            "baseName": "exchange_account_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "assets",
            "baseName": "assets",
            "type": "Array<DetailedAssetsForTradingType>",
            "format": ""
        },
        {
            "name": "orders",
            "baseName": "orders",
            "type": "Array<OrderSummary>",
            "format": ""
        },
        {
            "name": "trades",
            "baseName": "trades",
            "type": "Array<TradeSummary>",
            "format": ""
        },
        {
            "name": "positions",
            "baseName": "positions",
            "type": "Array<PositionSummary>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AutomationState.attributeTypeMap;
    }

    public constructor() {
    }
}


