/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountType } from '../models/AccountType';

/**
* A cash/deposit account, always manually entered, never live-synced.
*/
export class BankAccount {
    /**
    * bank
    */
    'account_type': 'bank';
    'institution'?: string;
    'currency'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "account_type",
            "baseName": "account_type",
            "type": "AccountType",
            "format": ""
        },
        {
            "name": "institution",
            "baseName": "institution",
            "type": "string",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BankAccount.attributeTypeMap;
    }

    public constructor() {
    }
}


