/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountType } from '../models/AccountType';

/**
* BlockchainAccount
*/
export class BlockchainAccount {
    /**
    * blockchain
    */
    'account_type': 'blockchain';
    'blockchain': string;
    'network'?: string;
    'public_key'?: string;
    'private_key'?: string;
    'passphrase'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "account_type",
            "baseName": "account_type",
            "type": "AccountType",
            "format": ""
        },
        {
            "name": "blockchain",
            "baseName": "blockchain",
            "type": "string",
            "format": ""
        },
        {
            "name": "network",
            "baseName": "network",
            "type": "string",
            "format": ""
        },
        {
            "name": "public_key",
            "baseName": "public_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "private_key",
            "baseName": "private_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "passphrase",
            "baseName": "passphrase",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BlockchainAccount.attributeTypeMap;
    }

    public constructor() {
    }
}


