/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CopiedAsset } from '../models/CopiedAsset';
import { Order } from '../models/Order';
import { Position } from '../models/Position';

/**
* CopiedAccount
*/
export class CopiedAccount {
    'version': string;
    'updated_at': number;
    'copied_assets': Array<CopiedAsset>;
    'orders'?: Array<Order>;
    'positions'?: Array<Position>;
    'historical_snapshots'?: Array<CopiedAccount>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "updated_at",
            "baseName": "updated_at",
            "type": "number",
            "format": ""
        },
        {
            "name": "copied_assets",
            "baseName": "copied_assets",
            "type": "Array<CopiedAsset>",
            "format": ""
        },
        {
            "name": "orders",
            "baseName": "orders",
            "type": "Array<Order>",
            "format": ""
        },
        {
            "name": "positions",
            "baseName": "positions",
            "type": "Array<Position>",
            "format": ""
        },
        {
            "name": "historical_snapshots",
            "baseName": "historical_snapshots",
            "type": "Array<CopiedAccount>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CopiedAccount.attributeTypeMap;
    }

    public constructor() {
    }
}
