/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* CopyConfiguration
*/
export class CopyConfiguration {
    'configuration_type': CopyConfigurationConfigurationTypeEnum;
    'strategy_id': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "configuration_type",
            "baseName": "configuration_type",
            "type": "CopyConfigurationConfigurationTypeEnum",
            "format": ""
        },
        {
            "name": "strategy_id",
            "baseName": "strategy_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CopyConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}

export type CopyConfigurationConfigurationTypeEnum = 'CopyConfiguration'

