/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Account } from '../models/Account';

/**
* CreateAccountConfiguration
*/
export class CreateAccountConfiguration {
    'action_type': CreateAccountConfigurationActionTypeEnum;
    'configuration': Account;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action_type",
            "baseName": "action_type",
            "type": "CreateAccountConfigurationActionTypeEnum",
            "format": ""
        },
        {
            "name": "configuration",
            "baseName": "configuration",
            "type": "Account",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateAccountConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}

export type CreateAccountConfigurationActionTypeEnum = 'account_create'

