/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AutomationConfiguration } from '../models/AutomationConfiguration';

/**
* CreateAutomationConfiguration
*/
export class CreateAutomationConfiguration {
    'action_type': CreateAutomationConfigurationActionTypeEnum;
    'configuration': AutomationConfiguration;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action_type",
            "baseName": "action_type",
            "type": "CreateAutomationConfigurationActionTypeEnum",
            "format": ""
        },
        {
            "name": "configuration",
            "baseName": "configuration",
            "type": "AutomationConfiguration",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateAutomationConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}

export type CreateAutomationConfigurationActionTypeEnum = 'automation_create'

