/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountAuthentication } from '../models/AccountAuthentication';
import { UserActionType } from '../models/UserActionType';

/**
* CreateAccountAuthConfiguration
*/
export class CreateAccountAuthConfiguration {
    /**
    * account_auth_create
    */
    'action_type': 'account_auth_create';
    'configuration': AccountAuthentication;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action_type",
            "baseName": "action_type",
            "type": "UserActionType",
            "format": ""
        },
        {
            "name": "configuration",
            "baseName": "configuration",
            "type": "AccountAuthentication",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateAccountAuthConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}


