/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EvaluatorConfiguration } from '../models/EvaluatorConfiguration';
import { TimeFrame } from '../models/TimeFrame';

/**
* DCAConfiguration
*/
export class DCAConfiguration {
    'configuration_type': DCAConfigurationConfigurationTypeEnum;
    'symbols': Array<string>;
    'buy_orders_count': number;
    'percent_amount_per_buy_order': number;
    'profit_target_percent': number;
    'buy_order_price_discount_percent': number;
    'enable_stop_loss': boolean;
    'stop_loss_price_discount_percent': number;
    'trigger_mode': DCAConfigurationTriggerModeEnum;
    'use_init_entry_orders': boolean;
    'time_frames': Array<TimeFrame>;
    'evaluators': Array<EvaluatorConfiguration>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "configuration_type",
            "baseName": "configuration_type",
            "type": "DCAConfigurationConfigurationTypeEnum",
            "format": ""
        },
        {
            "name": "symbols",
            "baseName": "symbols",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "buy_orders_count",
            "baseName": "buy_orders_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "percent_amount_per_buy_order",
            "baseName": "percent_amount_per_buy_order",
            "type": "number",
            "format": ""
        },
        {
            "name": "profit_target_percent",
            "baseName": "profit_target_percent",
            "type": "number",
            "format": ""
        },
        {
            "name": "buy_order_price_discount_percent",
            "baseName": "buy_order_price_discount_percent",
            "type": "number",
            "format": ""
        },
        {
            "name": "enable_stop_loss",
            "baseName": "enable_stop_loss",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "stop_loss_price_discount_percent",
            "baseName": "stop_loss_price_discount_percent",
            "type": "number",
            "format": ""
        },
        {
            "name": "trigger_mode",
            "baseName": "trigger_mode",
            "type": "DCAConfigurationTriggerModeEnum",
            "format": ""
        },
        {
            "name": "use_init_entry_orders",
            "baseName": "use_init_entry_orders",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "time_frames",
            "baseName": "time_frames",
            "type": "Array<TimeFrame>",
            "format": ""
        },
        {
            "name": "evaluators",
            "baseName": "evaluators",
            "type": "Array<EvaluatorConfiguration>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DCAConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}

export type DCAConfigurationConfigurationTypeEnum = 'DCAConfiguration'
export type DCAConfigurationTriggerModeEnum = 'Maximum evaluators signals based' | 'Time based'

