/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Must match parameter_type; for select/time_frame must be one of options[].value.
*/
/**
 * @type DslParameterDefaultValue
 * Type
 * @export
 */
export type DslParameterDefaultValue = boolean | number | string;

/**
* @type DslParameterDefaultValueClass
    * Must match parameter_type; for select/time_frame must be one of options[].value.
* @export
*/
export class DslParameterDefaultValueClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}


