/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DslParameterDefaultValue } from '../models/DslParameterDefaultValue';
import { DslParameterOption } from '../models/DslParameterOption';
import { DslValueType } from '../models/DslValueType';

/**
* Configurable parameter on a DSL keyword.
*/
export class DslParameter {
    /**
    * Unique within this keyword.
    */
    'name': string;
    'label': string;
    'value_type': DslValueType;
    'description'?: string;
    'default_value'?: DslParameterDefaultValue;
    /**
    * Only for parameter_type=number.
    */
    'minimum'?: number;
    /**
    * Only for parameter_type=number.
    */
    'maximum'?: number;
    /**
    * Only for parameter_type=number.
    */
    'step'?: number;
    /**
    * Allowed choices for value_type=text or value_type=time_frame.
    */
    'options'?: Array<DslParameterOption>;
    'required'?: boolean;
    /**
    * Accepts more than one value of this parameter.
    */
    'multiple'?: boolean;
    /**
    * Prefer in compact editors.
    */
    'primary'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        },
        {
            "name": "value_type",
            "baseName": "value_type",
            "type": "DslValueType",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "default_value",
            "baseName": "default_value",
            "type": "DslParameterDefaultValue",
            "format": ""
        },
        {
            "name": "minimum",
            "baseName": "minimum",
            "type": "number",
            "format": ""
        },
        {
            "name": "maximum",
            "baseName": "maximum",
            "type": "number",
            "format": ""
        },
        {
            "name": "step",
            "baseName": "step",
            "type": "number",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "Array<DslParameterOption>",
            "format": ""
        },
        {
            "name": "required",
            "baseName": "required",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "multiple",
            "baseName": "multiple",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "primary",
            "baseName": "primary",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DslParameter.attributeTypeMap;
    }

    public constructor() {
    }
}


