/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Account } from '../models/Account';
import { UserActionType } from '../models/UserActionType';

/**
* EditAccountConfiguration
*/
export class EditAccountConfiguration {
    /**
    * account_edit
    */
    'action_type': 'account_edit';
    'id': string;
    'configuration'?: Account;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action_type",
            "baseName": "action_type",
            "type": "UserActionType",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "configuration",
            "baseName": "configuration",
            "type": "Account",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EditAccountConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}


