/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EvaluatorType } from '../models/EvaluatorType';

/**
* EMAMomentumEvaluatorConfiguration
*/
export class EMAMomentumEvaluatorConfiguration {
    /**
    * EMAMomentumEvaluator
    */
    'configuration_type': 'EMAMomentumEvaluator';
    'period_length': number;
    'price_threshold_percent': number;
    'reverse_signal': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "configuration_type",
            "baseName": "configuration_type",
            "type": "EvaluatorType",
            "format": ""
        },
        {
            "name": "period_length",
            "baseName": "period_length",
            "type": "number",
            "format": ""
        },
        {
            "name": "price_threshold_percent",
            "baseName": "price_threshold_percent",
            "type": "number",
            "format": ""
        },
        {
            "name": "reverse_signal",
            "baseName": "reverse_signal",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EMAMomentumEvaluatorConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}


