/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ExchangeSupportStatus } from '../models/ExchangeSupportStatus';
import { TradingType } from '../models/TradingType';

/**
* ExchangeAvailability
*/
export class ExchangeAvailability {
    'internal_name': string;
    'name': string;
    'logo'?: string;
    'available_trading_types': Array<TradingType>;
    'support_type'?: ExchangeSupportStatus;
    'sandboxable'?: boolean;
    'broker_enabled'?: boolean;
    'register_url'?: string;
    'api_url'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "internal_name",
            "baseName": "internal_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "logo",
            "baseName": "logo",
            "type": "string",
            "format": ""
        },
        {
            "name": "available_trading_types",
            "baseName": "available_trading_types",
            "type": "Array<TradingType>",
            "format": ""
        },
        {
            "name": "support_type",
            "baseName": "support_type",
            "type": "ExchangeSupportStatus",
            "format": ""
        },
        {
            "name": "sandboxable",
            "baseName": "sandboxable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "broker_enabled",
            "baseName": "broker_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "register_url",
            "baseName": "register_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "api_url",
            "baseName": "api_url",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ExchangeAvailability.attributeTypeMap;
    }

    public constructor() {
    }
}


