/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountType } from '../models/AccountType';

/**
* A centralized or DEX trading account, live-synced via a provider connection.
*/
export class ExchangeAccount {
    /**
    * exchange
    */
    'account_type': 'exchange';
    'remote_account_id': string;
    'exchange_config_ids': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "account_type",
            "baseName": "account_type",
            "type": "AccountType",
            "format": ""
        },
        {
            "name": "remote_account_id",
            "baseName": "remote_account_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "exchange_config_ids",
            "baseName": "exchange_config_ids",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ExchangeAccount.attributeTypeMap;
    }

    public constructor() {
    }
}


