/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountType } from '../models/AccountType';
import { Asset } from '../models/Asset';

/**
* GenericAccount
*/
export class GenericAccount {
    /**
    * generic
    */
    'account_type': AccountType;
    'assets'?: Array<Asset>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "account_type",
            "baseName": "account_type",
            "type": "AccountType",
            "format": ""
        },
        {
            "name": "assets",
            "baseName": "assets",
            "type": "Array<Asset>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GenericAccount.attributeTypeMap;
    }

    public constructor() {
    }
}


