/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HistoricalAssetValue } from '../models/HistoricalAssetValue';
import { TradingType } from '../models/TradingType';

/**
* HistoricalAssetsForTradingType
*/
export class HistoricalAssetsForTradingType {
    'trading_type': TradingType;
    'assets': Array<HistoricalAssetValue>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "trading_type",
            "baseName": "trading_type",
            "type": "TradingType",
            "format": ""
        },
        {
            "name": "assets",
            "baseName": "assets",
            "type": "Array<HistoricalAssetValue>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return HistoricalAssetsForTradingType.attributeTypeMap;
    }

    public constructor() {
    }
}


