/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ActionConfigurationType } from '../models/ActionConfigurationType';
import { IndexCoin } from '../models/IndexCoin';

/**
* IndexConfiguration
*/
export class IndexConfiguration {
    /**
    * index
    */
    'configuration_type': 'index';
    'coins': Array<IndexCoin>;
    'rebalance_trigger_min_percent': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "configuration_type",
            "baseName": "configuration_type",
            "type": "ActionConfigurationType",
            "format": ""
        },
        {
            "name": "coins",
            "baseName": "coins",
            "type": "Array<IndexCoin>",
            "format": ""
        },
        {
            "name": "rebalance_trigger_min_percent",
            "baseName": "rebalance_trigger_min_percent",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IndexConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}


