/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ActionConfigurationType } from '../models/ActionConfigurationType';
import { MarketMakingSymbolConfiguration } from '../models/MarketMakingSymbolConfiguration';

/**
* Per-symbol market making parameters.
*/
export class MarketMakingConfiguration {
    /**
    * market_making
    */
    'configuration_type': 'market_making';
    'pair_settings': Array<MarketMakingSymbolConfiguration>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "configuration_type",
            "baseName": "configuration_type",
            "type": "ActionConfigurationType",
            "format": ""
        },
        {
            "name": "pair_settings",
            "baseName": "pair_settings",
            "type": "Array<MarketMakingSymbolConfiguration>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MarketMakingConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}


