/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Scheduled volume order sizing and timing in quote currency.
*/
export class MarketMakingScheduledVolume {
    'min_amount': number;
    'max_amount': number;
    'min_interval_seconds': number;
    'max_interval_seconds': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "min_amount",
            "baseName": "min_amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "max_amount",
            "baseName": "max_amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "min_interval_seconds",
            "baseName": "min_interval_seconds",
            "type": "number",
            "format": ""
        },
        {
            "name": "max_interval_seconds",
            "baseName": "max_interval_seconds",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MarketMakingScheduledVolume.attributeTypeMap;
    }

    public constructor() {
    }
}
