/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CancelPolicy } from '../models/CancelPolicy';
import { OrderGroup } from '../models/OrderGroup';
import { OrderStatus } from '../models/OrderStatus';
import { OrderType } from '../models/OrderType';
import { Side } from '../models/Side';
import { TrailingProfile } from '../models/TrailingProfile';

/**
* Order
*/
export class Order {
    'id': string;
    'symbol': string;
    'price': number;
    'quantity': number;
    'filled': number;
    'exchange_id': string;
    'side': Side;
    'type': OrderType;
    'trigger_above'?: boolean;
    'reduce_only'?: boolean;
    'is_active'?: boolean;
    'status': OrderStatus;
    'created_at': string;
    'entries'?: Array<string>;
    'update_with_triggering_order_fees'?: boolean;
    'order_group'?: OrderGroup;
    'trailing_profile'?: TrailingProfile;
    'cancel_policy'?: CancelPolicy;
    'chained_orders'?: Array<Order>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "string",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": ""
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "filled",
            "baseName": "filled",
            "type": "number",
            "format": ""
        },
        {
            "name": "exchange_id",
            "baseName": "exchange_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "side",
            "baseName": "side",
            "type": "Side",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "OrderType",
            "format": ""
        },
        {
            "name": "trigger_above",
            "baseName": "trigger_above",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "reduce_only",
            "baseName": "reduce_only",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "is_active",
            "baseName": "is_active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "OrderStatus",
            "format": ""
        },
        {
            "name": "created_at",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "entries",
            "baseName": "entries",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "update_with_triggering_order_fees",
            "baseName": "update_with_triggering_order_fees",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "order_group",
            "baseName": "order_group",
            "type": "OrderGroup",
            "format": ""
        },
        {
            "name": "trailing_profile",
            "baseName": "trailing_profile",
            "type": "TrailingProfile",
            "format": ""
        },
        {
            "name": "cancel_policy",
            "baseName": "cancel_policy",
            "type": "CancelPolicy",
            "format": ""
        },
        {
            "name": "chained_orders",
            "baseName": "chained_orders",
            "type": "Array<Order>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Order.attributeTypeMap;
    }

    public constructor() {
    }
}


