/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Lifecycle state of an order.
*/
export type OrderStatus = 'pending_creation' | 'open' | 'partially_filled' | 'filled' | 'canceled' | 'canceling' | 'closed' | 'expired' | 'rejected' | 'unknown'
