/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HistoricalAssetsForTradingType } from '../models/HistoricalAssetsForTradingType';

/**
* PortfolioHistoricalValue
*/
export class PortfolioHistoricalValue {
    'timestamp': string;
    'total': number;
    'assets'?: Array<HistoricalAssetsForTradingType>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": ""
        },
        {
            "name": "assets",
            "baseName": "assets",
            "type": "Array<HistoricalAssetsForTradingType>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PortfolioHistoricalValue.attributeTypeMap;
    }

    public constructor() {
    }
}
