/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PositionStatus } from '../models/PositionStatus';
import { Side } from '../models/Side';

/**
* Position
*/
export class Position {
    'id': string;
    'symbol': string;
    'side': Side;
    'quantity': number;
    'entry_price': number;
    'mark_price': number;
    'liquidation_price': number;
    'status': PositionStatus;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "string",
            "format": ""
        },
        {
            "name": "side",
            "baseName": "side",
            "type": "Side",
            "format": ""
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "entry_price",
            "baseName": "entry_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "mark_price",
            "baseName": "mark_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "liquidation_price",
            "baseName": "liquidation_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "PositionStatus",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Position.attributeTypeMap;
    }

    public constructor() {
    }
}


