/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* RefreshAccountsConfiguration
*/
export class RefreshAccountsConfiguration {
    'action_type': RefreshAccountsConfigurationActionTypeEnum;
    'account_ids'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action_type",
            "baseName": "action_type",
            "type": "RefreshAccountsConfigurationActionTypeEnum",
            "format": ""
        },
        {
            "name": "account_ids",
            "baseName": "account_ids",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RefreshAccountsConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}

export type RefreshAccountsConfigurationActionTypeEnum = 'accounts_refresh'

