/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EvaluatorType } from '../models/EvaluatorType';

/**
* RSIMomentumEvaluatorConfiguration
*/
export class RSIMomentumEvaluatorConfiguration {
    /**
    * RSIMomentumEvaluator
    */
    'configuration_type': 'RSIMomentumEvaluator';
    'period_length': number;
    'short_threshold': number;
    'long_threshold': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "configuration_type",
            "baseName": "configuration_type",
            "type": "EvaluatorType",
            "format": ""
        },
        {
            "name": "period_length",
            "baseName": "period_length",
            "type": "number",
            "format": ""
        },
        {
            "name": "short_threshold",
            "baseName": "short_threshold",
            "type": "number",
            "format": ""
        },
        {
            "name": "long_threshold",
            "baseName": "long_threshold",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RSIMomentumEvaluatorConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}


