/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* SignalPriorityActionExecutionResult
*/
export class SignalPriorityActionExecutionResult {
    'priority_action_id': string;
    'error_status'?: string;
    'error_message'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "priority_action_id",
            "baseName": "priority_action_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "error_status",
            "baseName": "error_status",
            "type": "string",
            "format": ""
        },
        {
            "name": "error_message",
            "baseName": "error_message",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SignalPriorityActionExecutionResult.attributeTypeMap;
    }

    public constructor() {
    }
}
