/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Optional payload associated with the signal type
*/
/**
 * @type SignalAutomationConfigurationSignalPayload
 * Type
 * @export
 */
export type SignalAutomationConfigurationSignalPayload = Array<any> | any;

/**
* @type SignalAutomationConfigurationSignalPayloadClass
    * Optional payload associated with the signal type
* @export
*/
export class SignalAutomationConfigurationSignalPayloadClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

