/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Optional payload associated with signal_type. Schema stays generic; see description for wire shapes. When signal_type is actions: a single action object, an array of action objects, or an object with an actions array. Each action object may use signal (param=val string, JSON signal string, or value resolved to DSL), a bare signal dict containing the flow signal key (e.g. SIGNAL), or dsl_script with id for direct DSL passthrough without resolution. Optional fields: id (default generated when using signal), await_execution_result (default true). signal is resolved to DSL; dsl_script is executed as-is. When signal_type is trading_signal: a trading-signal dict or one-element array. forced_trigger ignores payload.
*/
/**
 * @type SignalAutomationConfigurationSignalPayload
 * Type
 * @export
 */
export type SignalAutomationConfigurationSignalPayload = Array<any> | any;

/**
* @type SignalAutomationConfigurationSignalPayloadClass
    * Optional payload associated with signal_type. Schema stays generic; see description for wire shapes. When signal_type is actions: a single action object, an array of action objects, or an object with an actions array. Each action object may use signal (param=val string, JSON signal string, or value resolved to DSL), a bare signal dict containing the flow signal key (e.g. SIGNAL), or dsl_script with id for direct DSL passthrough without resolution. Optional fields: id (default generated when using signal), await_execution_result (default true). signal is resolved to DSL; dsl_script is executed as-is. When signal_type is trading_signal: a trading-signal dict or one-element array. forced_trigger ignores payload.
* @export
*/
export class SignalAutomationConfigurationSignalPayloadClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

