/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TimeFrame } from '../models/TimeFrame';

/**
* StrategyEvaluatorConfiguration
*/
export class StrategyEvaluatorConfiguration {
    /**
    * Strategy evaluator tentacle class name, e.g. SimpleStrategyEvaluator
    */
    'name': string;
    'config': { [key: string]: any; };
    'time_frames': Array<TimeFrame>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "config",
            "baseName": "config",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "time_frames",
            "baseName": "time_frames",
            "type": "Array<TimeFrame>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StrategyEvaluatorConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}
