/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CopyConfiguration } from '../models/CopyConfiguration';
import { GenericProcessConfiguration } from '../models/GenericProcessConfiguration';
import { GenericWorkflowConfiguration } from '../models/GenericWorkflowConfiguration';
import { MarketMakingConfiguration } from '../models/MarketMakingConfiguration';
import { TradingTentaclesConfiguration } from '../models/TradingTentaclesConfiguration';

/**
 * @type StrategyConfiguration
 * Type
 * @export
 */
export type StrategyConfiguration = CopyConfiguration | GenericProcessConfiguration | GenericWorkflowConfiguration | MarketMakingConfiguration | TradingTentaclesConfiguration;

/**
* @type StrategyConfigurationClass
* @export
*/
export class StrategyConfigurationClass {
    static readonly discriminator: string | undefined = "configuration_type";

    static readonly mapping: {[index: string]: string} | undefined = {
        "CopyConfiguration": "CopyConfiguration",
        "GenericProcessConfiguration": "GenericProcessConfiguration",
        "GenericWorkflowConfiguration": "GenericWorkflowConfiguration",
        "MarketMakingConfiguration": "MarketMakingConfiguration",
        "TradingTentaclesConfiguration": "TradingTentaclesConfiguration",
    };
}




