/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountActionResult } from '../models/AccountActionResult';
import { AccountAuthActionResult } from '../models/AccountAuthActionResult';
import { AutomationActionResult } from '../models/AutomationActionResult';
import { ExchangeConfigActionResult } from '../models/ExchangeConfigActionResult';
import { StrategyActionResult } from '../models/StrategyActionResult';

/**
 * @type UserActionResult
 * Type
 * @export
 */
export type UserActionResult = AccountActionResult | AccountAuthActionResult | AutomationActionResult | ExchangeConfigActionResult | StrategyActionResult;

/**
* @type UserActionResultClass
* @export
*/
export class UserActionResultClass {
    static readonly discriminator: string | undefined = "result_type";

    static readonly mapping: {[index: string]: string} | undefined = {
        "account": "AccountActionResult",
        "account_auth": "AccountAuthActionResult",
        "automation": "AutomationActionResult",
        "exchange_config": "ExchangeConfigActionResult",
        "strategy": "StrategyActionResult",
    };
}




