/**
 * OctoBot protocol types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AutomationState } from '../models/AutomationState';
import { UserAction } from '../models/UserAction';

/**
* UserDataState
*/
export class UserDataState {
    'version': string;
    'automations'?: Array<AutomationState>;
    'user_actions'?: Array<UserAction>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "automations",
            "baseName": "automations",
            "type": "Array<AutomationState>",
            "format": ""
        },
        {
            "name": "user_actions",
            "baseName": "user_actions",
            "type": "Array<UserAction>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserDataState.attributeTypeMap;
    }

    public constructor() {
    }
}
