# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.simple_strategy_evaluator_configuration import SimpleStrategyEvaluatorConfiguration

class TestSimpleStrategyEvaluatorConfiguration(unittest.TestCase):
    """SimpleStrategyEvaluatorConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SimpleStrategyEvaluatorConfiguration:
        """Test SimpleStrategyEvaluatorConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SimpleStrategyEvaluatorConfiguration`
        """
        model = SimpleStrategyEvaluatorConfiguration()
        if include_optional:
            return SimpleStrategyEvaluatorConfiguration(
                configuration_type = 'SimpleStrategyEvaluator'
            )
        else:
            return SimpleStrategyEvaluatorConfiguration(
                configuration_type = 'SimpleStrategyEvaluator',
        )
        """

    def testSimpleStrategyEvaluatorConfiguration(self):
        """Test SimpleStrategyEvaluatorConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
