# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.index_coin import IndexCoin

class TestIndexCoin(unittest.TestCase):
    """IndexCoin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IndexCoin:
        """Test IndexCoin
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IndexCoin`
        """
        model = IndexCoin()
        if include_optional:
            return IndexCoin(
                name = '',
                ratio = 0
            )
        else:
            return IndexCoin(
                name = '',
                ratio = 0,
        )
        """

    def testIndexCoin(self):
        """Test IndexCoin"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
