# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.copied_asset import CopiedAsset

class TestCopiedAsset(unittest.TestCase):
    """CopiedAsset unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CopiedAsset:
        """Test CopiedAsset
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CopiedAsset`
        """
        model = CopiedAsset()
        if include_optional:
            return CopiedAsset(
                name = '',
                total = 1.337,
                available = 1.337,
                ratio = 1.337
            )
        else:
            return CopiedAsset(
                name = '',
                total = 1.337,
                available = 1.337,
                ratio = 1.337,
        )
        """

    def testCopiedAsset(self):
        """Test CopiedAsset"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
