# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.signal_automation_configuration import SignalAutomationConfiguration

class TestSignalAutomationConfiguration(unittest.TestCase):
    """SignalAutomationConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignalAutomationConfiguration:
        """Test SignalAutomationConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignalAutomationConfiguration`
        """
        model = SignalAutomationConfiguration()
        if include_optional:
            return SignalAutomationConfiguration(
                action_type = 'automation_create',
                automation_id = '',
                signal_type = 'actions',
                signal_payload = None
            )
        else:
            return SignalAutomationConfiguration(
                action_type = 'automation_create',
                automation_id = '',
                signal_type = 'actions',
        )
        """

    def testSignalAutomationConfiguration(self):
        """Test SignalAutomationConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
