# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.generic_account import GenericAccount

class TestGenericAccount(unittest.TestCase):
    """GenericAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenericAccount:
        """Test GenericAccount
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenericAccount`
        """
        model = GenericAccount()
        if include_optional:
            return GenericAccount(
                account_type = 'generic'
            )
        else:
            return GenericAccount(
                account_type = 'generic',
        )
        """

    def testGenericAccount(self):
        """Test GenericAccount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
