# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.rsi_momentum_evaluator_configuration import RSIMomentumEvaluatorConfiguration

class TestRSIMomentumEvaluatorConfiguration(unittest.TestCase):
    """RSIMomentumEvaluatorConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RSIMomentumEvaluatorConfiguration:
        """Test RSIMomentumEvaluatorConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RSIMomentumEvaluatorConfiguration`
        """
        model = RSIMomentumEvaluatorConfiguration()
        if include_optional:
            return RSIMomentumEvaluatorConfiguration(
                configuration_type = 'RSIMomentumEvaluator',
                period_length = 1,
                short_threshold = 0,
                long_threshold = 0,
                trend_change_identifier = True
            )
        else:
            return RSIMomentumEvaluatorConfiguration(
                configuration_type = 'RSIMomentumEvaluator',
                period_length = 1,
                short_threshold = 0,
                long_threshold = 0,
        )
        """

    def testRSIMomentumEvaluatorConfiguration(self):
        """Test RSIMomentumEvaluatorConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
