# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.create_account_configuration import CreateAccountConfiguration

class TestCreateAccountConfiguration(unittest.TestCase):
    """CreateAccountConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAccountConfiguration:
        """Test CreateAccountConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAccountConfiguration`
        """
        model = CreateAccountConfiguration()
        if include_optional:
            return CreateAccountConfiguration(
                action_type = 'automation_create',
                configuration = octobot_protocol.models.account.Account(
                    id = '', 
                    account_type = 'GENERIC', 
                    name = '', 
                    is_simulated = True, 
                    description = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    exchange_account = null, 
                    blockchain_account = null, 
                    generic_account = null, )
            )
        else:
            return CreateAccountConfiguration(
                action_type = 'automation_create',
                configuration = octobot_protocol.models.account.Account(
                    id = '', 
                    account_type = 'GENERIC', 
                    name = '', 
                    is_simulated = True, 
                    description = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    exchange_account = null, 
                    blockchain_account = null, 
                    generic_account = null, ),
        )
        """

    def testCreateAccountConfiguration(self):
        """Test CreateAccountConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
