# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.exchange_config import ExchangeConfig

class TestExchangeConfig(unittest.TestCase):
    """ExchangeConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExchangeConfig:
        """Test ExchangeConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExchangeConfig`
        """
        model = ExchangeConfig()
        if include_optional:
            return ExchangeConfig(
                id = '',
                name = '',
                exchange = '',
                sandboxed = True,
                url = '',
                dex_config = octobot_protocol.models.dex_config.DEXConfig(
                    chain_id = '', 
                    dex_id = '', 
                    base_token_addresses = [
                        ''
                        ], 
                    quote_token_addresses = [
                        ''
                        ], )
            )
        else:
            return ExchangeConfig(
                id = '',
                name = '',
                exchange = '',
                sandboxed = True,
        )
        """

    def testExchangeConfig(self):
        """Test ExchangeConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
