# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.evaluator_configuration import EvaluatorConfiguration

class TestEvaluatorConfiguration(unittest.TestCase):
    """EvaluatorConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EvaluatorConfiguration:
        """Test EvaluatorConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EvaluatorConfiguration`
        """
        model = EvaluatorConfiguration()
        if include_optional:
            return EvaluatorConfiguration(
                name = '',
                config = { },
                symbols = [
                    ''
                    ],
                include_in_construction_candle = True
            )
        else:
            return EvaluatorConfiguration(
                name = '',
                config = { },
                symbols = [
                    ''
                    ],
        )
        """

    def testEvaluatorConfiguration(self):
        """Test EvaluatorConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
