# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.account_specifics import AccountSpecifics

class TestAccountSpecifics(unittest.TestCase):
    """AccountSpecifics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountSpecifics:
        """Test AccountSpecifics
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountSpecifics`
        """
        model = AccountSpecifics()
        if include_optional:
            return AccountSpecifics(
                account_type = 'generic',
                remote_account_id = '',
                exchange_config_ids = [
                    ''
                    ],
                blockchain = '',
                network = ''
            )
        else:
            return AccountSpecifics(
                account_type = 'generic',
                remote_account_id = '',
                exchange_config_ids = [
                    ''
                    ],
                blockchain = '',
        )
        """

    def testAccountSpecifics(self):
        """Test AccountSpecifics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
