# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.evaluator_type import EvaluatorType

class TestEvaluatorType(unittest.TestCase):
    """EvaluatorType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEvaluatorType(self):
        """Test EvaluatorType"""
        # inst = EvaluatorType()

if __name__ == '__main__':
    unittest.main()
