# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.detailed_asset import DetailedAsset

class TestDetailedAsset(unittest.TestCase):
    """DetailedAsset unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DetailedAsset:
        """Test DetailedAsset
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DetailedAsset`
        """
        model = DetailedAsset()
        if include_optional:
            return DetailedAsset(
                symbol = '',
                total = 1.337,
                available = 1.337
            )
        else:
            return DetailedAsset(
                symbol = '',
                total = 1.337,
                available = 1.337,
        )
        """

    def testDetailedAsset(self):
        """Test DetailedAsset"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
