# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.market_making_order_book_depth import MarketMakingOrderBookDepth

class TestMarketMakingOrderBookDepth(unittest.TestCase):
    """MarketMakingOrderBookDepth unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarketMakingOrderBookDepth:
        """Test MarketMakingOrderBookDepth
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarketMakingOrderBookDepth`
        """
        model = MarketMakingOrderBookDepth()
        if include_optional:
            return MarketMakingOrderBookDepth(
                cumulated_volume_percent = 0,
                percent_daily_trading_volume = 0
            )
        else:
            return MarketMakingOrderBookDepth(
                cumulated_volume_percent = 0,
                percent_daily_trading_volume = 0,
        )
        """

    def testMarketMakingOrderBookDepth(self):
        """Test MarketMakingOrderBookDepth"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
