# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.edit_exchange_config_configuration import EditExchangeConfigConfiguration

class TestEditExchangeConfigConfiguration(unittest.TestCase):
    """EditExchangeConfigConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EditExchangeConfigConfiguration:
        """Test EditExchangeConfigConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EditExchangeConfigConfiguration`
        """
        model = EditExchangeConfigConfiguration()
        if include_optional:
            return EditExchangeConfigConfiguration(
                action_type = 'automation_create',
                id = '',
                configuration = octobot_protocol.models.exchange_config.ExchangeConfig(
                    id = '', 
                    name = '', 
                    exchange = '', 
                    sandboxed = True, 
                    url = '', 
                    dex_config = octobot_protocol.models.dex_config.DEXConfig(
                        chain_id = '', 
                        dex_id = '', 
                        base_token_addresses = [
                            ''
                            ], 
                        quote_token_addresses = [
                            ''
                            ], ), )
            )
        else:
            return EditExchangeConfigConfiguration(
                action_type = 'automation_create',
                id = '',
        )
        """

    def testEditExchangeConfigConfiguration(self):
        """Test EditExchangeConfigConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
