# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.order import Order

class TestOrder(unittest.TestCase):
    """Order unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Order:
        """Test Order
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Order`
        """
        model = Order()
        if include_optional:
            return Order(
                id = '',
                symbol = '',
                price = 1.337,
                quantity = 1.337,
                filled = 1.337,
                exchange_id = '',
                side = 'buy',
                type = 'limit',
                trigger_above = True,
                reduce_only = True,
                is_active = True,
                status = 'pending_creation',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                entries = [
                    ''
                    ],
                update_with_triggering_order_fees = True,
                order_group = octobot_protocol.models.order_group.OrderGroup(
                    id = '', 
                    type = 'BalancedTakeProfitAndStopOrderGroup', 
                    active_order_swap_strategy = octobot_protocol.models.active_order_swap_strategy.ActiveOrderSwapStrategy(
                        type = 'StopFirstActiveOrderSwapStrategy', 
                        trigger_price_configuration = octobot_protocol.models.trigger_price_configuration.trigger_price_configuration(), 
                        timeout = 1.337, ), ),
                trailing_profile = octobot_protocol.models.trailing_profile.TrailingProfile(
                    type = 'filled_take_profit', 
                    specifics = octobot_protocol.models.trigger_price_configuration.trigger_price_configuration(), ),
                cancel_policy = octobot_protocol.models.cancel_policy.CancelPolicy(
                    type = 'ExpirationTimeOrderCancelPolicy', 
                    specifics = octobot_protocol.models.trigger_price_configuration.trigger_price_configuration(), ),
                chained_orders = [
                    octobot_protocol.models.order.Order(
                        id = '', 
                        symbol = '', 
                        price = 1.337, 
                        quantity = 1.337, 
                        filled = 1.337, 
                        exchange_id = '', 
                        side = 'buy', 
                        type = 'limit', 
                        trigger_above = True, 
                        reduce_only = True, 
                        is_active = True, 
                        status = 'pending_creation', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        entries = [
                            ''
                            ], 
                        update_with_triggering_order_fees = True, 
                        order_group = octobot_protocol.models.order_group.OrderGroup(
                            id = '', 
                            active_order_swap_strategy = octobot_protocol.models.active_order_swap_strategy.ActiveOrderSwapStrategy(
                                type = 'StopFirstActiveOrderSwapStrategy', 
                                trigger_price_configuration = octobot_protocol.models.trigger_price_configuration.trigger_price_configuration(), 
                                timeout = 1.337, ), ), 
                        trailing_profile = octobot_protocol.models.trailing_profile.TrailingProfile(
                            type = 'filled_take_profit', 
                            specifics = octobot_protocol.models.trigger_price_configuration.trigger_price_configuration(), ), 
                        cancel_policy = octobot_protocol.models.cancel_policy.CancelPolicy(
                            type = 'ExpirationTimeOrderCancelPolicy', 
                            specifics = octobot_protocol.models.trigger_price_configuration.trigger_price_configuration(), ), 
                        chained_orders = [
                            octobot_protocol.models.order.Order(
                                id = '', 
                                symbol = '', 
                                price = 1.337, 
                                quantity = 1.337, 
                                filled = 1.337, 
                                exchange_id = '', 
                                side = 'buy', 
                                type = 'limit', 
                                trigger_above = True, 
                                reduce_only = True, 
                                is_active = True, 
                                status = 'pending_creation', 
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                update_with_triggering_order_fees = True, )
                            ], )
                    ]
            )
        else:
            return Order(
                id = '',
                symbol = '',
                price = 1.337,
                quantity = 1.337,
                filled = 1.337,
                exchange_id = '',
                side = 'buy',
                type = 'limit',
                status = 'pending_creation',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testOrder(self):
        """Test Order"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
