# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.debug import Debug

class TestDebug(unittest.TestCase):
    """Debug unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Debug:
        """Test Debug
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Debug`
        """
        model = Debug()
        if include_optional:
            return Debug(
                automations = [
                    octobot_protocol.models.automation_state.AutomationState(
                        id = '', 
                        status = 'pending', 
                        error = '', 
                        error_message = '', 
                        metadata = octobot_protocol.models.automation_metadata.AutomationMetadata(
                            name = '', 
                            description = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                        actions = [
                            octobot_protocol.models.action.Action(
                                id = '', 
                                action_type = '', 
                                status = 'pending', 
                                dsl = '', 
                                configuration = { }, 
                                result = '', 
                                error = '', 
                                completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                            ], 
                        priority_actions = [
                            octobot_protocol.models.action.Action(
                                id = '', 
                                action_type = '', 
                                status = , 
                                dsl = '', 
                                result = '', 
                                error = '', 
                                completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                            ], 
                        exchanges = [
                            ''
                            ], 
                        exchange_account_ids = [
                            ''
                            ], 
                        assets = [
                            octobot_protocol.models.detailed_assets_for_trading_type.DetailedAssetsForTradingType(
                                trading_type = 'spot', 
                                assets = [
                                    octobot_protocol.models.detailed_asset.DetailedAsset(
                                        symbol = '', 
                                        total = 1.337, 
                                        available = 1.337, )
                                    ], )
                            ], 
                        orders = [
                            octobot_protocol.models.order_summary.OrderSummary(
                                id = '', 
                                symbol = '', )
                            ], 
                        trades = [
                            octobot_protocol.models.trade_summary.TradeSummary(
                                id = '', 
                                symbol = '', )
                            ], 
                        positions = [
                            octobot_protocol.models.position_summary.PositionSummary(
                                id = '', 
                                symbol = '', )
                            ], )
                    ],
                user_actions = [
                    octobot_protocol.models.user_action.UserAction(
                        id = '', 
                        status = 'pending', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        configuration = null, 
                        result = null, )
                    ],
                accounts = [
                    octobot_protocol.models.account.Account(
                        id = '', 
                        name = '', 
                        is_simulated = True, 
                        description = '', 
                        state = octobot_protocol.models.account_state.AccountState(
                            permissions = [
                                'read'
                                ], 
                            status = 'valid', 
                            message = 'pending_validation', ), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        authentication_id = '', 
                        assets = [
                            octobot_protocol.models.detailed_assets_for_trading_type.DetailedAssetsForTradingType(
                                trading_type = 'spot', 
                                assets = [
                                    octobot_protocol.models.detailed_asset.DetailedAsset(
                                        symbol = '', 
                                        total = 1.337, 
                                        available = 1.337, )
                                    ], )
                            ], 
                        specifics = null, )
                    ],
                exchange_configs = [
                    octobot_protocol.models.exchange_config.ExchangeConfig(
                        id = '', 
                        name = '', 
                        exchange = '', 
                        sandboxed = True, 
                        url = '', )
                    ],
                account_tradings = [
                    octobot_protocol.models.account_trading_with_account_id.AccountTradingWithAccountId(
                        account_id = '', 
                        account_trading = octobot_protocol.models.account_trading.AccountTrading(
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            orders = [
                                octobot_protocol.models.order.Order(
                                    id = '', 
                                    symbol = '', 
                                    price = 1.337, 
                                    quantity = 1.337, 
                                    filled = 1.337, 
                                    exchange_id = '', 
                                    side = 'buy', 
                                    type = 'limit', 
                                    trigger_above = True, 
                                    reduce_only = True, 
                                    is_active = True, 
                                    status = 'pending_creation', 
                                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    entries = [
                                        ''
                                        ], 
                                    update_with_triggering_order_fees = True, 
                                    order_group = octobot_protocol.models.order_group.OrderGroup(
                                        id = '', 
                                        active_order_swap_strategy = octobot_protocol.models.active_order_swap_strategy.ActiveOrderSwapStrategy(
                                            type = 'StopFirstActiveOrderSwapStrategy', 
                                            trigger_price_configuration = octobot_protocol.models.trigger_price_configuration.trigger_price_configuration(), 
                                            timeout = 1.337, ), ), 
                                    trailing_profile = octobot_protocol.models.trailing_profile.TrailingProfile(
                                        type = 'filled_take_profit', 
                                        specifics = octobot_protocol.models.trigger_price_configuration.trigger_price_configuration(), ), 
                                    cancel_policy = octobot_protocol.models.cancel_policy.CancelPolicy(
                                        type = 'ExpirationTimeOrderCancelPolicy', 
                                        specifics = octobot_protocol.models.trigger_price_configuration.trigger_price_configuration(), ), 
                                    chained_orders = [
                                        octobot_protocol.models.order.Order(
                                            id = '', 
                                            symbol = '', 
                                            price = 1.337, 
                                            quantity = 1.337, 
                                            filled = 1.337, 
                                            exchange_id = '', 
                                            side = 'buy', 
                                            type = 'limit', 
                                            trigger_above = True, 
                                            reduce_only = True, 
                                            is_active = True, 
                                            status = 'pending_creation', 
                                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                            update_with_triggering_order_fees = True, )
                                        ], )
                                ], 
                            trades = [
                                octobot_protocol.models.trade.Trade(
                                    id = '', 
                                    trade_id = '', 
                                    type = , 
                                    symbol = '', 
                                    side = , 
                                    quantity = 1.337, 
                                    price = 1.337, 
                                    status = , 
                                    executed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                ], 
                            positions = [
                                octobot_protocol.models.position.Position(
                                    id = '', 
                                    symbol = '', 
                                    side = , 
                                    quantity = 1.337, 
                                    entry_price = 1.337, 
                                    mark_price = 1.337, 
                                    liquidation_price = 1.337, 
                                    status = 'open', )
                                ], ), )
                    ],
                local_strategies = [
                    octobot_protocol.models.strategy.Strategy(
                        id = '', 
                        version = '', 
                        name = '', 
                        description = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        reference_market = '', 
                        configuration = null, )
                    ]
            )
        else:
            return Debug(
                automations = [
                    octobot_protocol.models.automation_state.AutomationState(
                        id = '', 
                        status = 'pending', 
                        error = '', 
                        error_message = '', 
                        metadata = octobot_protocol.models.automation_metadata.AutomationMetadata(
                            name = '', 
                            description = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                        actions = [
                            octobot_protocol.models.action.Action(
                                id = '', 
                                action_type = '', 
                                status = 'pending', 
                                dsl = '', 
                                configuration = { }, 
                                result = '', 
                                error = '', 
                                completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                            ], 
                        priority_actions = [
                            octobot_protocol.models.action.Action(
                                id = '', 
                                action_type = '', 
                                status = , 
                                dsl = '', 
                                result = '', 
                                error = '', 
                                completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                            ], 
                        exchanges = [
                            ''
                            ], 
                        exchange_account_ids = [
                            ''
                            ], 
                        assets = [
                            octobot_protocol.models.detailed_assets_for_trading_type.DetailedAssetsForTradingType(
                                trading_type = 'spot', 
                                assets = [
                                    octobot_protocol.models.detailed_asset.DetailedAsset(
                                        symbol = '', 
                                        total = 1.337, 
                                        available = 1.337, )
                                    ], )
                            ], 
                        orders = [
                            octobot_protocol.models.order_summary.OrderSummary(
                                id = '', 
                                symbol = '', )
                            ], 
                        trades = [
                            octobot_protocol.models.trade_summary.TradeSummary(
                                id = '', 
                                symbol = '', )
                            ], 
                        positions = [
                            octobot_protocol.models.position_summary.PositionSummary(
                                id = '', 
                                symbol = '', )
                            ], )
                    ],
                user_actions = [
                    octobot_protocol.models.user_action.UserAction(
                        id = '', 
                        status = 'pending', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        configuration = null, 
                        result = null, )
                    ],
        )
        """

    def testDebug(self):
        """Test Debug"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
