# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.grid_configuration import GridConfiguration

class TestGridConfiguration(unittest.TestCase):
    """GridConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GridConfiguration:
        """Test GridConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GridConfiguration`
        """
        model = GridConfiguration()
        if include_optional:
            return GridConfiguration(
                configuration_type = 'market_making',
                symbol = '',
                spread = 0,
                increment = 0,
                buy_count = 1,
                sell_count = 1,
                enable_trailing_up = True,
                enable_trailing_down = True,
                order_by_order_trailing = True
            )
        else:
            return GridConfiguration(
                configuration_type = 'market_making',
                symbol = '',
                spread = 0,
                increment = 0,
                buy_count = 1,
                sell_count = 1,
                enable_trailing_up = True,
                enable_trailing_down = True,
                order_by_order_trailing = True,
        )
        """

    def testGridConfiguration(self):
        """Test GridConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
