# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.strategies_state import StrategiesState

class TestStrategiesState(unittest.TestCase):
    """StrategiesState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StrategiesState:
        """Test StrategiesState
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StrategiesState`
        """
        model = StrategiesState()
        if include_optional:
            return StrategiesState(
                version = '',
                strategies = [
                    octobot_protocol.models.strategy.Strategy(
                        id = '', 
                        version = '', 
                        name = '', 
                        description = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        configuration = null, )
                    ]
            )
        else:
            return StrategiesState(
                version = '',
                strategies = [
                    octobot_protocol.models.strategy.Strategy(
                        id = '', 
                        version = '', 
                        name = '', 
                        description = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        configuration = null, )
                    ],
        )
        """

    def testStrategiesState(self):
        """Test StrategiesState"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
