# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.portfolio_historical_values_state import PortfolioHistoricalValuesState

class TestPortfolioHistoricalValuesState(unittest.TestCase):
    """PortfolioHistoricalValuesState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PortfolioHistoricalValuesState:
        """Test PortfolioHistoricalValuesState
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PortfolioHistoricalValuesState`
        """
        model = PortfolioHistoricalValuesState()
        if include_optional:
            return PortfolioHistoricalValuesState(
                version = '',
                history = octobot_protocol.models.portfolio_historical_values.PortfolioHistoricalValues(
                    unit = '', 
                    values = [
                        octobot_protocol.models.portfolio_historical_value.PortfolioHistoricalValue(
                            timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            total = 1.337, 
                            assets = [
                                octobot_protocol.models.historical_assets_for_trading_type.HistoricalAssetsForTradingType(
                                    trading_type = 'spot', 
                                    assets = [
                                        octobot_protocol.models.historical_asset_value.HistoricalAssetValue(
                                            symbol = '', 
                                            holdings = 1.337, 
                                            value = 1.337, )
                                        ], )
                                ], )
                        ], )
            )
        else:
            return PortfolioHistoricalValuesState(
                version = '',
        )
        """

    def testPortfolioHistoricalValuesState(self):
        """Test PortfolioHistoricalValuesState"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
