# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.dca_configuration import DCAConfiguration

class TestDCAConfiguration(unittest.TestCase):
    """DCAConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DCAConfiguration:
        """Test DCAConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DCAConfiguration`
        """
        model = DCAConfiguration()
        if include_optional:
            return DCAConfiguration(
                configuration_type = 'DCAConfiguration',
                symbols = [
                    ''
                    ],
                buy_orders_count = 1,
                percent_amount_per_buy_order = 0,
                profit_target_percent = 0,
                buy_order_price_discount_percent = 0,
                enable_stop_loss = True,
                stop_loss_price_discount_percent = 0,
                trigger_mode = 'Maximum evaluators signals based',
                use_init_entry_orders = True,
                time_frames = [
                    '1m'
                    ],
                evaluators = [
                    octobot_protocol.models.evaluator_configuration.EvaluatorConfiguration(
                        configuration = null, )
                    ]
            )
        else:
            return DCAConfiguration(
                configuration_type = 'DCAConfiguration',
                symbols = [
                    ''
                    ],
                buy_orders_count = 1,
                percent_amount_per_buy_order = 0,
                profit_target_percent = 0,
                buy_order_price_discount_percent = 0,
                enable_stop_loss = True,
                stop_loss_price_discount_percent = 0,
                trigger_mode = 'Maximum evaluators signals based',
                use_init_entry_orders = True,
                time_frames = [
                    '1m'
                    ],
                evaluators = [
                    octobot_protocol.models.evaluator_configuration.EvaluatorConfiguration(
                        configuration = null, )
                    ],
        )
        """

    def testDCAConfiguration(self):
        """Test DCAConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
