# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.generic_workflow_configuration import GenericWorkflowConfiguration

class TestGenericWorkflowConfiguration(unittest.TestCase):
    """GenericWorkflowConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenericWorkflowConfiguration:
        """Test GenericWorkflowConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenericWorkflowConfiguration`
        """
        model = GenericWorkflowConfiguration()
        if include_optional:
            return GenericWorkflowConfiguration(
                configuration_type = 'market_making',
                actions = [
                    octobot_protocol.models.action.Action(
                        id = '', 
                        action_type = '', 
                        status = 'pending', 
                        dsl = '', 
                        configuration = { }, 
                        result = '', 
                        error = '', 
                        completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return GenericWorkflowConfiguration(
                configuration_type = 'market_making',
                actions = [
                    octobot_protocol.models.action.Action(
                        id = '', 
                        action_type = '', 
                        status = 'pending', 
                        dsl = '', 
                        configuration = { }, 
                        result = '', 
                        error = '', 
                        completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testGenericWorkflowConfiguration(self):
        """Test GenericWorkflowConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
