# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.user_actions_state import UserActionsState

class TestUserActionsState(unittest.TestCase):
    """UserActionsState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserActionsState:
        """Test UserActionsState
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserActionsState`
        """
        model = UserActionsState()
        if include_optional:
            return UserActionsState(
                version = '',
                user_actions = [
                    octobot_protocol.models.user_action.UserAction(
                        id = '', 
                        status = 'pending', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        configuration = null, 
                        result = null, )
                    ]
            )
        else:
            return UserActionsState(
                version = '',
        )
        """

    def testUserActionsState(self):
        """Test UserActionsState"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
