# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.traded_pair_volume import TradedPairVolume

class TestTradedPairVolume(unittest.TestCase):
    """TradedPairVolume unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TradedPairVolume:
        """Test TradedPairVolume
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TradedPairVolume`
        """
        model = TradedPairVolume()
        if include_optional:
            return TradedPairVolume(
                base_volume = 1.337,
                quote_volume = 1.337
            )
        else:
            return TradedPairVolume(
        )
        """

    def testTradedPairVolume(self):
        """Test TradedPairVolume"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
