# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.automation_state import AutomationState

class TestAutomationState(unittest.TestCase):
    """AutomationState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AutomationState:
        """Test AutomationState
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AutomationState`
        """
        model = AutomationState()
        if include_optional:
            return AutomationState(
                id = '',
                status = 'pending',
                metadata = octobot_protocol.models.automation_metadata.AutomationMetadata(
                    name = '', 
                    description = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                actions = [
                    octobot_protocol.models.action.Action(
                        id = '', 
                        action_type = '', 
                        status = 'pending', 
                        dsl = '', 
                        configuration = { }, 
                        result = '', 
                        error = '', 
                        completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                priority_actions = [
                    octobot_protocol.models.action.Action(
                        id = '', 
                        action_type = '', 
                        status = 'pending', 
                        dsl = '', 
                        configuration = { }, 
                        result = '', 
                        error = '', 
                        completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                exchanges = [
                    ''
                    ],
                exchange_account_ids = [
                    ''
                    ],
                assets = [
                    octobot_protocol.models.detailed_asset.DetailedAsset(
                        symbol = '', 
                        total = 1.337, 
                        available = 1.337, )
                    ],
                orders = [
                    octobot_protocol.models.order_summary.OrderSummary(
                        id = '', 
                        symbol = '', )
                    ],
                trades = [
                    octobot_protocol.models.trade_summary.TradeSummary(
                        id = '', 
                        symbol = '', )
                    ],
                positions = [
                    octobot_protocol.models.position_summary.PositionSummary(
                        id = '', 
                        symbol = '', )
                    ]
            )
        else:
            return AutomationState(
                id = '',
                status = 'pending',
                metadata = octobot_protocol.models.automation_metadata.AutomationMetadata(
                    name = '', 
                    description = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
        )
        """

    def testAutomationState(self):
        """Test AutomationState"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
