# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.side import Side

class TestSide(unittest.TestCase):
    """Side unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSide(self):
        """Test Side"""
        # inst = Side()

if __name__ == '__main__':
    unittest.main()
