# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.exchange_availability import ExchangeAvailability

class TestExchangeAvailability(unittest.TestCase):
    """ExchangeAvailability unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExchangeAvailability:
        """Test ExchangeAvailability
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExchangeAvailability`
        """
        model = ExchangeAvailability()
        if include_optional:
            return ExchangeAvailability(
                internal_name = '',
                name = '',
                logo = '',
                available_trading_types = [
                    'spot'
                    ],
                support_type = 'officially_supported',
                sandboxable = True,
                broker_enabled = True,
                register_url = '',
                api_url = ''
            )
        else:
            return ExchangeAvailability(
                internal_name = '',
                name = '',
                available_trading_types = [
                    'spot'
                    ],
        )
        """

    def testExchangeAvailability(self):
        """Test ExchangeAvailability"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
