# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.strategy_configuration import StrategyConfiguration

class TestStrategyConfiguration(unittest.TestCase):
    """StrategyConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StrategyConfiguration:
        """Test StrategyConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StrategyConfiguration`
        """
        model = StrategyConfiguration()
        if include_optional:
            return StrategyConfiguration(
                configuration_type = 'market_making',
                pair_settings = [
                    octobot_protocol.models.market_making_symbol_configuration.MarketMakingSymbolConfiguration(
                        trading_pair = '', 
                        reference_price = [
                            octobot_protocol.models.market_making_reference_pair.MarketMakingReferencePair(
                                exchange = '', 
                                pair = '', 
                                weight = 1.337, 
                                formula = '', 
                                time_frame = '1m', )
                            ], 
                        min_spread = 0, 
                        max_spread = 0, 
                        order_book_depth = octobot_protocol.models.market_making_order_book_depth.MarketMakingOrderBookDepth(
                            cumulated_volume_percent = 0, 
                            percent_daily_trading_volume = 0, ), 
                        scheduled_volume = octobot_protocol.models.market_making_scheduled_volume.MarketMakingScheduledVolume(
                            min_amount = 0, 
                            max_amount = 0, 
                            min_interval_seconds = 0, 
                            max_interval_seconds = 0, ), 
                        stop_conditions = octobot_protocol.models.market_making_stop_conditions.MarketMakingStopConditions(
                            min_base_holding = 0, 
                            min_quote_holding = 0, 
                            max_positive_percent_price_change = 0, 
                            max_negative_percent_price_change = 0, 
                            average_price_counted_minutes = 1, ), 
                        bids_count = 1, 
                        asks_count = 1, 
                        orders_distribution = 'linear', 
                        funds_distribution = 'flat', 
                        exchange = '', 
                        max_base_budget = 0, 
                        max_quote_budget = 0, 
                        min_base_budget = 0, 
                        min_quote_budget = 0, 
                        hedging_engine = octobot_protocol.models.market_making_hedging_engine.MarketMakingHedgingEngine(
                            average_price_counted_minutes = 1, 
                            hedging_engine_type = 'spot', 
                            hedging_exchange = '', 
                            hedging_max_loss_threshold = 0, 
                            hedging_profit_threshold = 0, 
                            max_negative_percent_price_change = 0, 
                            max_positive_percent_price_change = 0, ), )
                    ],
                name = '',
                config = { },
                symbols = [
                    ''
                    ],
                strategies = [
                    octobot_protocol.models.strategy_evaluator_configuration.StrategyEvaluatorConfiguration(
                        name = '', 
                        config = { }, 
                        time_frames = [
                            '1m'
                            ], )
                    ],
                evaluators = [
                    octobot_protocol.models.evaluator_configuration.EvaluatorConfiguration(
                        name = '', 
                        config = { }, 
                        symbols = [
                            ''
                            ], 
                        include_in_construction_candle = True, )
                    ],
                strategy_id = '',
                profile_data = octobot_protocol.models.profile_data.profile_data(),
                actions = [
                    octobot_protocol.models.action.Action(
                        id = '', 
                        action_type = '', 
                        status = 'pending', 
                        dsl = '', 
                        configuration = { }, 
                        result = '', 
                        error = '', 
                        completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return StrategyConfiguration(
                configuration_type = 'market_making',
                pair_settings = [
                    octobot_protocol.models.market_making_symbol_configuration.MarketMakingSymbolConfiguration(
                        trading_pair = '', 
                        reference_price = [
                            octobot_protocol.models.market_making_reference_pair.MarketMakingReferencePair(
                                exchange = '', 
                                pair = '', 
                                weight = 1.337, 
                                formula = '', 
                                time_frame = '1m', )
                            ], 
                        min_spread = 0, 
                        max_spread = 0, 
                        order_book_depth = octobot_protocol.models.market_making_order_book_depth.MarketMakingOrderBookDepth(
                            cumulated_volume_percent = 0, 
                            percent_daily_trading_volume = 0, ), 
                        scheduled_volume = octobot_protocol.models.market_making_scheduled_volume.MarketMakingScheduledVolume(
                            min_amount = 0, 
                            max_amount = 0, 
                            min_interval_seconds = 0, 
                            max_interval_seconds = 0, ), 
                        stop_conditions = octobot_protocol.models.market_making_stop_conditions.MarketMakingStopConditions(
                            min_base_holding = 0, 
                            min_quote_holding = 0, 
                            max_positive_percent_price_change = 0, 
                            max_negative_percent_price_change = 0, 
                            average_price_counted_minutes = 1, ), 
                        bids_count = 1, 
                        asks_count = 1, 
                        orders_distribution = 'linear', 
                        funds_distribution = 'flat', 
                        exchange = '', 
                        max_base_budget = 0, 
                        max_quote_budget = 0, 
                        min_base_budget = 0, 
                        min_quote_budget = 0, 
                        hedging_engine = octobot_protocol.models.market_making_hedging_engine.MarketMakingHedgingEngine(
                            average_price_counted_minutes = 1, 
                            hedging_engine_type = 'spot', 
                            hedging_exchange = '', 
                            hedging_max_loss_threshold = 0, 
                            hedging_profit_threshold = 0, 
                            max_negative_percent_price_change = 0, 
                            max_positive_percent_price_change = 0, ), )
                    ],
                name = '',
                config = { },
                strategy_id = '',
                profile_data = octobot_protocol.models.profile_data.profile_data(),
                actions = [
                    octobot_protocol.models.action.Action(
                        id = '', 
                        action_type = '', 
                        status = 'pending', 
                        dsl = '', 
                        configuration = { }, 
                        result = '', 
                        error = '', 
                        completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testStrategyConfiguration(self):
        """Test StrategyConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
