# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.market_making_hedging_engine import MarketMakingHedgingEngine

class TestMarketMakingHedgingEngine(unittest.TestCase):
    """MarketMakingHedgingEngine unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarketMakingHedgingEngine:
        """Test MarketMakingHedgingEngine
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarketMakingHedgingEngine`
        """
        model = MarketMakingHedgingEngine()
        if include_optional:
            return MarketMakingHedgingEngine(
                average_price_counted_minutes = 1,
                hedging_engine_type = 'spot',
                hedging_exchange = '',
                hedging_max_loss_threshold = 0,
                hedging_profit_threshold = 0,
                max_negative_percent_price_change = 0,
                max_positive_percent_price_change = 0
            )
        else:
            return MarketMakingHedgingEngine(
        )
        """

    def testMarketMakingHedgingEngine(self):
        """Test MarketMakingHedgingEngine"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
