# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.traded_pairs_by_exchange import TradedPairsByExchange

class TestTradedPairsByExchange(unittest.TestCase):
    """TradedPairsByExchange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TradedPairsByExchange:
        """Test TradedPairsByExchange
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TradedPairsByExchange`
        """
        model = TradedPairsByExchange()
        if include_optional:
            return TradedPairsByExchange(
            )
        else:
            return TradedPairsByExchange(
        )
        """

    def testTradedPairsByExchange(self):
        """Test TradedPairsByExchange"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
