# coding: utf-8

"""
    OctoBot protocol types

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from octobot_protocol.models.order_group import OrderGroup

class TestOrderGroup(unittest.TestCase):
    """OrderGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderGroup:
        """Test OrderGroup
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderGroup`
        """
        model = OrderGroup()
        if include_optional:
            return OrderGroup(
                id = '',
                type = 'BalancedTakeProfitAndStopOrderGroup',
                active_order_swap_strategy = octobot_protocol.models.active_order_swap_strategy.ActiveOrderSwapStrategy(
                    type = 'StopFirstActiveOrderSwapStrategy', 
                    trigger_price_configuration = octobot_protocol.models.trigger_price_configuration.trigger_price_configuration(), 
                    timeout = 1.337, )
            )
        else:
            return OrderGroup(
                id = '',
        )
        """

    def testOrderGroup(self):
        """Test OrderGroup"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
