import json

import octobot_trading.personal_data as personal_data
import octobot_trading.storage as trading_storage


async def get_full_sol_usdt_open_orders(exchange_manager) -> list[personal_data.Order]:
    order_data = json.loads(FULL_SOL_USDT_OPEN_ORDERS_DATA)
    pending_groups = {}
    orders = []
    for o in order_data:
        orders.append(await personal_data.create_order_from_order_storage_details(
            trading_storage.orders_storage.from_order_document(o), exchange_manager, pending_groups
        ))
    return orders



FULL_SOL_USDT_OPEN_ORDERS_DATA = """
[
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.236395,
            "exchange_id": "5f72d5ab-e6d7-468f-9161-7d3c3150329a",
            "fee": null,
            "filled": 0,
            "id": "e2d61a49-f184-4cc8-9a1b-d1e2570346c5",
            "is_active": true,
            "price": 149.093,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "sell",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362439.478,
            "triggerAbove": true,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.24154,
            "exchange_id": "7b010951-d6e5-4bb2-9494-df1ad09c8931",
            "fee": null,
            "filled": 0,
            "id": "b66efc84-a7ac-40a0-9504-8c6e1c6286f1",
            "is_active": true,
            "price": 149.436,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "sell",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362439.993,
            "triggerAbove": true,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.246685,
            "exchange_id": "6d6e907b-33d6-4d54-b0cf-fa17b5e75ff9",
            "fee": null,
            "filled": 0,
            "id": "293e61bc-24b8-4dc1-a717-62137c66e2b2",
            "is_active": true,
            "price": 149.779,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "sell",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362440.537,
            "triggerAbove": true,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.25183,
            "exchange_id": "55acfd16-05b0-4992-bd14-66214aaa5be0",
            "fee": null,
            "filled": 0,
            "id": "4afd159e-9ba2-4fd6-85ea-378be6610d9d",
            "is_active": true,
            "price": 150.122,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "sell",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362441.365,
            "triggerAbove": true,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.256975,
            "exchange_id": "9f3c2566-2c27-46bf-8e6d-7fb20ec12269",
            "fee": null,
            "filled": 0,
            "id": "a5e1f296-92b0-4908-bd55-83022affb484",
            "is_active": true,
            "price": 150.465,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "sell",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362442.069,
            "triggerAbove": true,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.26212,
            "exchange_id": "c6264220-3ab7-4d24-96c5-727c8634965c",
            "fee": null,
            "filled": 0,
            "id": "acbb27bd-8de6-4f5b-b53d-e2a529acceeb",
            "is_active": true,
            "price": 150.808,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "sell",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362442.74,
            "triggerAbove": true,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.267265,
            "exchange_id": "bce0b649-e629-4f2c-90f7-83d4e5424653",
            "fee": null,
            "filled": 0,
            "id": "a7170333-1b62-40cc-b4e7-0acdc607c211",
            "is_active": true,
            "price": 151.151,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "sell",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362443.241,
            "triggerAbove": true,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.272425,
            "exchange_id": "0527e79c-86bc-4721-9af6-e3d51af2ed00",
            "fee": null,
            "filled": 0,
            "id": "1733285b-6a7e-470e-b429-64751300bd81",
            "is_active": true,
            "price": 151.495,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "sell",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362443.768,
            "triggerAbove": true,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.27757,
            "exchange_id": "56ba40bd-f94d-4d9b-8d72-1edea1ee5903",
            "fee": null,
            "filled": 0,
            "id": "34c8004b-0dbf-4930-97cf-ea369844ba1a",
            "is_active": true,
            "price": 151.838,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "sell",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362444.591,
            "triggerAbove": true,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.282715,
            "exchange_id": "cbde43d2-c98b-4c6d-982c-653bdfd3b2ed",
            "fee": null,
            "filled": 0,
            "id": "1bdad673-d4c8-4d7b-973a-ac406e613433",
            "is_active": true,
            "price": 152.181,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "sell",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362445.101,
            "triggerAbove": true,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.28786,
            "exchange_id": "023d3cf7-3e0b-41c5-b39d-bbce2070810e",
            "fee": null,
            "filled": 0,
            "id": "b0d75c90-ccc6-4e6f-9d3c-be89c7391239",
            "is_active": true,
            "price": 152.524,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "sell",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362445.6,
            "triggerAbove": true,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.293005,
            "exchange_id": "26cd9f3e-63c4-40ff-a5a7-7d07fe2b1e9a",
            "fee": null,
            "filled": 0,
            "id": "4f40a061-cc2c-4bd5-a587-311064fbd886",
            "is_active": true,
            "price": 152.867,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "sell",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362446.093,
            "triggerAbove": true,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.29815,
            "exchange_id": "3b158e17-5957-4f06-95e0-70dcf0e41fc8",
            "fee": null,
            "filled": 0,
            "id": "997fc0f4-6d1f-4549-9c49-6fc4ddeb1f3e",
            "is_active": true,
            "price": 153.21,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "sell",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362446.587,
            "triggerAbove": true,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.303295,
            "exchange_id": "75bd9860-211f-4654-a699-0429c646c5ac",
            "fee": null,
            "filled": 0,
            "id": "160ff3c9-9c36-4f7e-a244-903bc07ceb77",
            "is_active": true,
            "price": 153.553,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "sell",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362447.177,
            "triggerAbove": true,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.30844,
            "exchange_id": "64c40497-14f9-47f7-a1cd-52561d7b8e43",
            "fee": null,
            "filled": 0,
            "id": "72494344-7783-4bea-86d2-7def01b6943c",
            "is_active": true,
            "price": 153.896,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "sell",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362447.668,
            "triggerAbove": true,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.313585,
            "exchange_id": "2dfd619b-0348-4510-bbfb-5d0a13ff7092",
            "fee": null,
            "filled": 0,
            "id": "33021a88-fc36-41c0-8bac-1ba7f5f41054",
            "is_active": true,
            "price": 154.239,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "sell",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362448.162,
            "triggerAbove": true,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.31873,
            "exchange_id": "371c2f07-c976-4f43-a8e8-b55f5c6e6b56",
            "fee": null,
            "filled": 0,
            "id": "bc398948-e494-46ee-ac54-ce0321d73661",
            "is_active": true,
            "price": 154.582,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "sell",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362452.3,
            "triggerAbove": true,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.32389,
            "exchange_id": "27ea1b0e-f4b7-4926-833c-0fe4aa1384a0",
            "fee": null,
            "filled": 0,
            "id": "028481c6-e2dd-4d27-b7ad-e8ac8948065b",
            "is_active": true,
            "price": 154.926,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "sell",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362453.138,
            "triggerAbove": true,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.329035,
            "exchange_id": "449f2062-ff20-4343-b349-ef7bb5e0b463",
            "fee": null,
            "filled": 0,
            "id": "85565926-e992-41dd-a922-5528e9dc3cd6",
            "is_active": true,
            "price": 155.269,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "sell",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362453.65,
            "triggerAbove": true,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.33418,
            "exchange_id": "0f3b10d0-9843-47fa-b9f8-0865bc3b1387",
            "fee": null,
            "filled": 0,
            "id": "c25e0844-f26e-4ab3-ae00-61d26310a9b6",
            "is_active": true,
            "price": 155.612,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "sell",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362454.145,
            "triggerAbove": true,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.339325,
            "exchange_id": "74f4555d-5fe3-40e4-a0a4-6d7c9b3cd317",
            "fee": null,
            "filled": 0,
            "id": "fb8011f2-5ff4-4033-920f-d347c235050b",
            "is_active": true,
            "price": 155.955,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "sell",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362454.64,
            "triggerAbove": true,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.34447,
            "exchange_id": "bf533d78-4f40-4626-aeab-fea7a4d1849e",
            "fee": null,
            "filled": 0,
            "id": "be9643ca-bb77-47e7-9ac4-b0b686dfa5d2",
            "is_active": true,
            "price": 156.298,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "sell",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362455.132,
            "triggerAbove": true,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.349615,
            "exchange_id": "66613fa4-4d2c-4e6e-8908-05eda8ae8183",
            "fee": null,
            "filled": 0,
            "id": "ae535faa-e4dd-4702-81f3-520a35059f41",
            "is_active": true,
            "price": 156.641,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "sell",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362455.629,
            "triggerAbove": true,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.35476,
            "exchange_id": "644cb5f8-dc8e-4ec0-a709-1d94901a2ac1",
            "fee": null,
            "filled": 0,
            "id": "ae1ba3d9-bdbd-404e-9d15-ba97670ec8a7",
            "is_active": true,
            "price": 156.984,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "sell",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362456.128,
            "triggerAbove": true,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.359905,
            "exchange_id": "ce2d07d4-dde3-442b-923c-6490eeb5607d",
            "fee": null,
            "filled": 0,
            "id": "b597f05a-11bf-4cf4-80ae-942b9dae6284",
            "is_active": true,
            "price": 157.327,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "sell",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362456.625,
            "triggerAbove": true,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.22567,
            "exchange_id": "cad8be3a-23ed-4d5e-ac4f-880123393a42",
            "fee": null,
            "filled": 0,
            "id": "5c2eb7aa-49ac-4af5-b95b-f66d60f93197",
            "is_active": true,
            "price": 148.378,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "buy",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362457.121,
            "triggerAbove": false,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.015,
            "broker_applied": false,
            "cost": 2.220525,
            "exchange_id": "19dc8ee4-0dbb-4d39-ae65-400fcde7c5d2",
            "fee": null,
            "filled": 0,
            "id": "bffaec37-383e-4fe1-ad9a-1514e23ee0a9",
            "is_active": true,
            "price": 148.035,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "buy",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362457.628,
            "triggerAbove": false,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.016,
            "broker_applied": false,
            "cost": 2.363072,
            "exchange_id": "d77e3751-55cf-4769-ab86-14a855fd0993",
            "fee": null,
            "filled": 0,
            "id": "e885a482-4a5c-4b23-90eb-6ba44cea132f",
            "is_active": true,
            "price": 147.692,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "buy",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362458.122,
            "triggerAbove": false,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.016,
            "broker_applied": false,
            "cost": 2.357584,
            "exchange_id": "debe8041-2485-4f95-b1ca-13ed5f398933",
            "fee": null,
            "filled": 0,
            "id": "3998e406-1f08-4c9b-9678-fb1bc256469a",
            "is_active": true,
            "price": 147.349,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "buy",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362458.623,
            "triggerAbove": false,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.016,
            "broker_applied": false,
            "cost": 2.352096,
            "exchange_id": "0148bdf1-088c-4d69-8d70-be4d0785ae62",
            "fee": null,
            "filled": 0,
            "id": "3afaa44d-fba4-449a-9b1a-14b0cd2a654b",
            "is_active": true,
            "price": 147.006,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "buy",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362459.14,
            "triggerAbove": false,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.016,
            "broker_applied": false,
            "cost": 2.346608,
            "exchange_id": "a9ff2a8e-b9b8-48c3-9813-e5b592c4e0e3",
            "fee": null,
            "filled": 0,
            "id": "c26fd512-b6c0-4bd4-90fd-3564e1c8f32c",
            "is_active": true,
            "price": 146.663,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "buy",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362459.638,
            "triggerAbove": false,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.016,
            "broker_applied": false,
            "cost": 2.34112,
            "exchange_id": "039e1b2a-b531-420a-8057-dcc4323ed63e",
            "fee": null,
            "filled": 0,
            "id": "d0b68aea-521f-4019-9d71-554ccf3032a8",
            "is_active": true,
            "price": 146.32,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "buy",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362460.135,
            "triggerAbove": false,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.016,
            "broker_applied": false,
            "cost": 2.335616,
            "exchange_id": "3e907299-7cf3-47c1-bcb3-9b047453e917",
            "fee": null,
            "filled": 0,
            "id": "dcdca84c-7636-4b4f-a32c-7c2f5f45ec10",
            "is_active": true,
            "price": 145.976,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "buy",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362460.624,
            "triggerAbove": false,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.016,
            "broker_applied": false,
            "cost": 2.330128,
            "exchange_id": "0eaad5e3-5158-4c90-b002-1a01b3d55704",
            "fee": null,
            "filled": 0,
            "id": "172139ab-0841-4a02-b92a-6002fc31ba08",
            "is_active": true,
            "price": 145.633,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "buy",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362462.833,
            "triggerAbove": false,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.016,
            "broker_applied": false,
            "cost": 2.32464,
            "exchange_id": "696abfb4-df1c-44cc-93c2-6512fd787feb",
            "fee": null,
            "filled": 0,
            "id": "cf223507-c436-4e65-94de-174e379d661d",
            "is_active": true,
            "price": 145.29,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "buy",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362463.354,
            "triggerAbove": false,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.016,
            "broker_applied": false,
            "cost": 2.319152,
            "exchange_id": "ba69fedb-623b-40a1-be23-f2ba1037e77a",
            "fee": null,
            "filled": 0,
            "id": "2a9e57ed-531a-4649-a880-dff4513d9097",
            "is_active": true,
            "price": 144.947,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "buy",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362463.864,
            "triggerAbove": false,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.016,
            "broker_applied": false,
            "cost": 2.313664,
            "exchange_id": "cf9b9e19-ff79-4800-b81d-a0eaa44b1e2c",
            "fee": null,
            "filled": 0,
            "id": "6473cef5-0f83-431d-9f7c-b7353456a484",
            "is_active": true,
            "price": 144.604,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "buy",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362464.381,
            "triggerAbove": false,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.016,
            "broker_applied": false,
            "cost": 2.308176,
            "exchange_id": "77a8433a-6ff7-4b2d-a640-b5e4f592eb3e",
            "fee": null,
            "filled": 0,
            "id": "a0407fb5-599f-4d88-ae08-2d678ca375cb",
            "is_active": true,
            "price": 144.261,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "buy",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362464.869,
            "triggerAbove": false,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.016,
            "broker_applied": false,
            "cost": 2.302688,
            "exchange_id": "0f9a422f-7f69-4c8a-8649-f451441d588f",
            "fee": null,
            "filled": 0,
            "id": "b8668c80-b436-4551-91b1-669fae2996e9",
            "is_active": true,
            "price": 143.918,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "buy",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362465.362,
            "triggerAbove": false,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.016,
            "broker_applied": false,
            "cost": 2.2972,
            "exchange_id": "9f558a98-44c3-49d3-bb16-a75e5d294c24",
            "fee": null,
            "filled": 0,
            "id": "c6b4abd4-e419-424e-8726-5541856b7a8f",
            "is_active": true,
            "price": 143.575,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "buy",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362465.858,
            "triggerAbove": false,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.016,
            "broker_applied": false,
            "cost": 2.291712,
            "exchange_id": "5c6a4c92-b7b3-425c-a37c-1ab16e85d955",
            "fee": null,
            "filled": 0,
            "id": "a1c1cf06-c020-4304-9f7c-f9c0c28938fc",
            "is_active": true,
            "price": 143.232,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "buy",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362466.351,
            "triggerAbove": false,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.016,
            "broker_applied": false,
            "cost": 2.286224,
            "exchange_id": "868e5035-1cb9-413c-a8f8-5d08d2b97e77",
            "fee": null,
            "filled": 0,
            "id": "5960d7d7-f290-4a43-aa6c-16eaca5da57d",
            "is_active": true,
            "price": 142.889,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "buy",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362466.848,
            "triggerAbove": false,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.016,
            "broker_applied": false,
            "cost": 2.28072,
            "exchange_id": "3c4ead8c-162a-4d70-ad75-a22ff8df2cdf",
            "fee": null,
            "filled": 0,
            "id": "4d3c13b0-6b6b-4aa4-b293-f9871b1acdb1",
            "is_active": true,
            "price": 142.545,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "buy",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362467.354,
            "triggerAbove": false,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.016,
            "broker_applied": false,
            "cost": 2.275232,
            "exchange_id": "231ccb05-af47-4b39-a636-fe5dd8366421",
            "fee": null,
            "filled": 0,
            "id": "aa27b90c-cbbe-4a2a-a916-8e4302df21f4",
            "is_active": true,
            "price": 142.202,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "buy",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362467.873,
            "triggerAbove": false,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.016,
            "broker_applied": false,
            "cost": 2.269744,
            "exchange_id": "99d4e79d-9dd5-49bd-ab2d-96e577e328e2",
            "fee": null,
            "filled": 0,
            "id": "5a1289dd-574b-445d-9d66-64761532be12",
            "is_active": true,
            "price": 141.859,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "buy",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362468.366,
            "triggerAbove": false,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.016,
            "broker_applied": false,
            "cost": 2.264256,
            "exchange_id": "47751ce1-6a9b-4952-b334-5a08a791752c",
            "fee": null,
            "filled": 0,
            "id": "351587f1-cc99-43e0-9cf3-36d05ccb7ddc",
            "is_active": true,
            "price": 141.516,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "buy",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362468.856,
            "triggerAbove": false,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.016,
            "broker_applied": false,
            "cost": 2.258768,
            "exchange_id": "00d8a607-ac35-4f09-a650-d8edbb7f9881",
            "fee": null,
            "filled": 0,
            "id": "a6f3b844-69bc-4fdc-beb7-26485fc055b8",
            "is_active": true,
            "price": 141.173,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "buy",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362469.344,
            "triggerAbove": false,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.016,
            "broker_applied": false,
            "cost": 2.25328,
            "exchange_id": "9f0b79e3-8296-48d5-ad94-8ce4ddbce87e",
            "fee": null,
            "filled": 0,
            "id": "8c8437f0-b714-4963-8ed6-00017f83389c",
            "is_active": true,
            "price": 140.83,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "buy",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362469.84,
            "triggerAbove": false,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.016,
            "broker_applied": false,
            "cost": 2.247792,
            "exchange_id": "2e028d69-8a07-4ba6-9da9-ef8b343a1d51",
            "fee": null,
            "filled": 0,
            "id": "4be47863-7c6a-4c87-8cd6-d8a20cb17870",
            "is_active": true,
            "price": 140.487,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "buy",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362470.333,
            "triggerAbove": false,
            "type": "limit"
          }
        },
        {
          "origin_value": {
            "amount": 0.016,
            "broker_applied": false,
            "cost": 2.242304,
            "exchange_id": "cfc91ba9-6440-4c4c-addf-a2973425e4cf",
            "fee": null,
            "filled": 0,
            "id": "bfc8bb3a-72e7-4572-9ebc-ffb43067a17b",
            "is_active": true,
            "price": 140.144,
            "quantity_currency": "SOL",
            "reduceOnly": false,
            "self-managed": false,
            "side": "buy",
            "status": "open",
            "symbol": "SOL/USDT",
            "tag": null,
            "takerOrMaker": "maker",
            "timestamp": 1751362470.852,
            "triggerAbove": false,
            "type": "limit"
          }
        }
      ]
"""