import React, {type ReactNode} from 'react';
import Link from '@docusaurus/Link';
import Translate, {translate} from '@docusaurus/Translate';
import {
  LandingLayout,
  Hero,
  Section,
  FAQ,
  CTABand,
  TradingViewWidget,
} from '@site/src/components/landing';
import {
  FaqJsonLd,
  BreadcrumbsJsonLd,
  type FaqJsonLdItem,
} from '@site/src/components/seo';
import GlassCard from '@site/src/components/GlassCard';
import Badge from '@site/src/components/Badge';
import type {Cryptocurrency} from '../types';
import shared from '../styles.module.css';

/*
 * AI price prediction — programmatic route /<symbol>-prediction.
 *
 * Generated by the octobot-programmatic-pages plugin. Migrated from the
 * Astrolab (programmatic)/[slug] Crypto prediction page. The live ChatGPT
 * signal is not available at build time, so the page links out to the live
 * predictions tool instead of rendering a stale signal.
 */

const CLOUD = 'https://www.octobot.cloud';
const PREDICTIONS_TOOL = '/tools/crypto-prediction';

interface CryptoPredictionData {
  crypto: Cryptocurrency;
}

export default function CryptoPrediction({
  data,
}: {
  data: CryptoPredictionData;
}): ReactNode {
  const {crypto} = data;
  const faqItems: FaqJsonLdItem[] = (crypto.faq ?? []).map((entry) => ({
    question: entry.question,
    answer: entry.answer,
  }));
  const title = translate(
    {
      id: 'programmatic.cryptoPrediction.layout.title',
      message: '{name} AI prediction',
      description: 'Page title; {name} is the cryptocurrency name',
    },
    {name: crypto.name},
  );

  return (
    <LandingLayout
      title={title}
      description={translate(
        {
          id: 'programmatic.cryptoPrediction.layout.description',
          message:
            'Discover the latest {name} ({symbol}) AI predictions from ChatGPT, with price history and key metrics.',
          description:
            'Page meta description; {name} is the cryptocurrency name, {symbol} its ticker',
        },
        {name: crypto.name, symbol: crypto.symbol},
      )}>
      <FaqJsonLd items={faqItems} />
      <BreadcrumbsJsonLd
        trail={[{name: title, path: `/${crypto.symbol.toLowerCase()}-prediction`}]}
      />
      <div className={shared.gridVeil} aria-hidden="true" />

      <Hero
        eyebrow={translate({
          id: 'programmatic.cryptoPrediction.hero.eyebrow',
          message: 'AI prediction',
          description: 'Hero eyebrow',
        })}
        title={
          <Translate
            id="programmatic.cryptoPrediction.hero.title"
            description="Hero title; {name} is the cryptocurrency name, {accent} is a styled span"
            values={{
              name: crypto.name,
              accent: (
                <span className="ng-text-gradient">
                  <Translate
                    id="programmatic.cryptoPrediction.hero.titleAccent"
                    description="Hero title accent">
                    price prediction.
                  </Translate>
                </span>
              ),
            }}>
            {'{name} {accent}'}
          </Translate>
        }
        subtitle={translate(
          {
            id: 'programmatic.cryptoPrediction.hero.subtitle',
            message:
              'AI-generated {symbol} predictions from ChatGPT — refreshed continuously on OctoBot Cloud.',
            description: 'Hero subtitle; {symbol} is the ticker',
          },
          {symbol: crypto.symbol},
        )}
        actions={[
          {
            label: translate({
              id: 'programmatic.cryptoPrediction.hero.action.live',
              message: 'See live predictions',
              description: 'Hero CTA label',
            }),
            to: PREDICTIONS_TOOL,
          },
          {
            label: translate(
              {
                id: 'programmatic.cryptoPrediction.hero.action.trade',
                message: 'Trade {symbol}',
                description: 'Hero secondary CTA label; {symbol} is the ticker',
              },
              {symbol: crypto.symbol},
            ),
            to: CLOUD,
            variant: 'ghost',
          },
        ]}
        meta={[
          {label: crypto.symbol, dot: true},
          {
            label: translate({
              id: 'programmatic.cryptoPrediction.hero.meta.signal',
              message: 'ChatGPT signal',
              description: 'Hero meta label',
            }),
          },
          {
            label: translate({
              id: 'programmatic.cryptoPrediction.hero.meta.updated',
              message: 'Updated continuously',
              description: 'Hero meta label',
            }),
          },
        ]}
      />

      <Section
        eyebrow={translate({
          id: 'programmatic.cryptoPrediction.signal.eyebrow',
          message: 'Latest signal',
          description: 'Section eyebrow',
        })}
        title={translate(
          {
            id: 'programmatic.cryptoPrediction.signal.title',
            message: '{name} AI prediction',
            description:
              'Section title; {name} is the cryptocurrency name',
          },
          {name: crypto.name},
        )}>
        <GlassCard variant="hero" padded className={shared.predictionCard}>
          <span className={shared.predictionLabel}>
            <Translate
              id="programmatic.cryptoPrediction.signal.label"
              description="Prediction card label; {name} is the cryptocurrency name"
              values={{name: crypto.name}}>
              {'Last AI prediction for {name}'}
            </Translate>
          </span>
          <Badge tone="frost" dot>
            <Translate
              id="programmatic.cryptoPrediction.signal.badge"
              description="Prediction card badge label">
              Live on OctoBot Cloud
            </Translate>
          </Badge>
          <p className={shared.prose}>
            <Translate
              id="programmatic.cryptoPrediction.signal.prose"
              description="Prediction card body text; {symbol} is the ticker"
              values={{symbol: crypto.symbol}}>
              {
                'The newest {symbol} prediction is generated on the live predictions tool — signals move with the market and are not frozen into this page.'
              }
            </Translate>
          </p>
          <Link className="ng-btn ng-btn--primary" to={PREDICTIONS_TOOL}>
            <Translate
              id="programmatic.cryptoPrediction.signal.action"
              description="Prediction card CTA; {symbol} is the ticker"
              values={{symbol: crypto.symbol}}>
              {'View {symbol} prediction'}
            </Translate>
          </Link>
        </GlassCard>
      </Section>

      <Section
        eyebrow={translate({
          id: 'programmatic.cryptoPrediction.price.eyebrow',
          message: 'Price',
          description: 'Section eyebrow',
        })}
        title={translate(
          {
            id: 'programmatic.cryptoPrediction.price.title',
            message: '{name} price history',
            description:
              'Section title; {name} is the cryptocurrency name',
          },
          {name: crypto.name},
        )}
        lead={translate(
          {
            id: 'programmatic.cryptoPrediction.price.lead',
            message: 'The live {symbol}/USDT market, charted.',
            description: 'Section lead; {symbol} is the ticker',
          },
          {symbol: crypto.symbol},
        )}>
        <div className={shared.chart}>
          <TradingViewWidget symbol={`BINANCE:${crypto.symbol}USDT`} />
        </div>
      </Section>

      {faqItems.length > 0 && (
        <Section
          eyebrow={translate({
            id: 'programmatic.cryptoPrediction.faq.eyebrow',
            message: 'FAQ',
            description: 'Section eyebrow',
          })}
          title={translate(
            {
              id: 'programmatic.cryptoPrediction.faq.title',
              message: '{name} FAQ',
              description:
                'Section title; {name} is the cryptocurrency name',
            },
            {name: crypto.name},
          )}>
          <FAQ items={faqItems} />
        </Section>
      )}

      <CTABand
        title={
          <Translate
            id="programmatic.cryptoPrediction.cta.title"
            description="CTA band title; {accent} is a styled span"
            values={{
              accent: (
                <span className="ng-text-frost">
                  <Translate
                    id="programmatic.cryptoPrediction.cta.titleAccent"
                    description="CTA band title accent">
                    not the noise.
                  </Translate>
                </span>
              ),
            }}>
            {'Trade the prediction, {accent}'}
          </Translate>
        }
        description={translate(
          {
            id: 'programmatic.cryptoPrediction.cta.description',
            message:
              'Turn {name} AI signals into automated trades on OctoBot Cloud.',
            description:
              'CTA band description; {name} is the cryptocurrency name',
          },
          {name: crypto.name},
        )}
        actions={[
          {
            label: translate({
              id: 'programmatic.cryptoPrediction.cta.action.start',
              message: 'Start on OctoBot Cloud',
              description: 'CTA band label',
            }),
            to: CLOUD,
          },
          {
            label: translate({
              id: 'programmatic.cryptoPrediction.cta.action.all',
              message: 'All predictions',
              description: 'CTA band secondary label',
            }),
            to: PREDICTIONS_TOOL,
            variant: 'ghost',
          },
        ]}
      />
    </LandingLayout>
  );
}
