[package]
name = "octobot_evaluators_py"
version = "1.10.1"
edition = "2021"

[lib]
name = "octobot_evaluators_py"
crate-type = ["cdylib", "rlib"]

[dependencies]
octobot_evaluators = { path = "../octobot_evaluators" }
async_channel = { path = "../async_channel" }
async_channel_py = { path = "../async_channel_py" }
pyo3_bridge = { path = "../pyo3_bridge" }
pyo3 = { version = "0.28", features = ["extension-module"] }
pyo3-async-runtimes = { version = "0.28", features = ["tokio-runtime"] }
tokio = { version = "1", features = ["rt", "rt-multi-thread"] }
uuid = { version = "1", features = ["v4"] }
