/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccountTrading : AccountTrading
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountTrading {
    #[serde(rename = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "orders", skip_serializing_if = "Option::is_none")]
    pub orders: Option<Vec<models::Order>>,
    #[serde(rename = "trades", skip_serializing_if = "Option::is_none")]
    pub trades: Option<Vec<models::Trade>>,
    #[serde(rename = "positions", skip_serializing_if = "Option::is_none")]
    pub positions: Option<Vec<models::Position>>,
}

impl AccountTrading {
    /// AccountTrading
    pub fn new(updated_at: chrono::DateTime<chrono::FixedOffset>) -> AccountTrading {
        AccountTrading {
            updated_at,
            orders: None,
            trades: None,
            positions: None,
        }
    }
}

