/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccountState : AccountState
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountState {
    #[serde(rename = "status")]
    pub status: models::AccountStatus,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<models::AccountStatusMessage>,
}

impl AccountState {
    /// AccountState
    pub fn new(status: models::AccountStatus) -> AccountState {
        AccountState {
            status,
            message: None,
        }
    }
}

