/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccountAuthentication : AccountAuthentication
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountAuthentication {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "api_key", skip_serializing_if = "Option::is_none")]
    pub api_key: Option<String>,
    #[serde(rename = "api_secret", skip_serializing_if = "Option::is_none")]
    pub api_secret: Option<String>,
    #[serde(rename = "api_passphrase", skip_serializing_if = "Option::is_none")]
    pub api_passphrase: Option<String>,
    #[serde(rename = "public_key", skip_serializing_if = "Option::is_none")]
    pub public_key: Option<String>,
    #[serde(rename = "private_key", skip_serializing_if = "Option::is_none")]
    pub private_key: Option<String>,
    #[serde(rename = "seed_phrase", skip_serializing_if = "Option::is_none")]
    pub seed_phrase: Option<String>,
}

impl AccountAuthentication {
    /// AccountAuthentication
    pub fn new(id: String) -> AccountAuthentication {
        AccountAuthentication {
            id,
            updated_at: None,
            api_key: None,
            api_secret: None,
            api_passphrase: None,
            public_key: None,
            private_key: None,
            seed_phrase: None,
        }
    }
}

