/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccountTradingState : AccountTradingState
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountTradingState {
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "account_trading")]
    pub account_trading: Box<models::AccountTrading>,
}

impl AccountTradingState {
    /// AccountTradingState
    pub fn new(version: String, account_trading: models::AccountTrading) -> AccountTradingState {
        AccountTradingState {
            version,
            account_trading: Box::new(account_trading),
        }
    }
}

