/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccountType : Account category discriminator.
/// Account category discriminator.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccountType {
    #[serde(rename = "generic")]
    Generic,
    #[serde(rename = "exchange")]
    Exchange,
    #[serde(rename = "blockchain")]
    Blockchain,

}

impl std::fmt::Display for AccountType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Generic => write!(f, "generic"),
            Self::Exchange => write!(f, "exchange"),
            Self::Blockchain => write!(f, "blockchain"),
        }
    }
}

impl Default for AccountType {
    fn default() -> AccountType {
        Self::Generic
    }
}

