/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccountsAuthenticationState : AccountsAuthenticationState
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountsAuthenticationState {
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "account_authentication")]
    pub account_authentication: Vec<models::AccountAuthentication>,
}

impl AccountsAuthenticationState {
    /// AccountsAuthenticationState
    pub fn new(version: String, account_authentication: Vec<models::AccountAuthentication>) -> AccountsAuthenticationState {
        AccountsAuthenticationState {
            version,
            account_authentication,
        }
    }
}

