/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionConfigurationType : ActionConfigurationType
/// ActionConfigurationType
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ActionConfigurationType {
    #[serde(rename = "market_making")]
    MarketMaking,
    #[serde(rename = "dca")]
    Dca,
    #[serde(rename = "index")]
    Index,
    #[serde(rename = "grid")]
    Grid,
    #[serde(rename = "copy")]
    Copy,
    #[serde(rename = "generic_process")]
    GenericProcess,
    #[serde(rename = "generic_workflow")]
    GenericWorkflow,

}

impl std::fmt::Display for ActionConfigurationType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::MarketMaking => write!(f, "market_making"),
            Self::Dca => write!(f, "dca"),
            Self::Index => write!(f, "index"),
            Self::Grid => write!(f, "grid"),
            Self::Copy => write!(f, "copy"),
            Self::GenericProcess => write!(f, "generic_process"),
            Self::GenericWorkflow => write!(f, "generic_workflow"),
        }
    }
}

impl Default for ActionConfigurationType {
    fn default() -> ActionConfigurationType {
        Self::MarketMaking
    }
}

