/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AutomationSignalType : AutomationSignalType
/// AutomationSignalType
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AutomationSignalType {
    #[serde(rename = "actions")]
    Actions,
    #[serde(rename = "trading_signal")]
    TradingSignal,
    #[serde(rename = "forced_trigger")]
    ForcedTrigger,

}

impl std::fmt::Display for AutomationSignalType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Actions => write!(f, "actions"),
            Self::TradingSignal => write!(f, "trading_signal"),
            Self::ForcedTrigger => write!(f, "forced_trigger"),
        }
    }
}

impl Default for AutomationSignalType {
    fn default() -> AutomationSignalType {
        Self::Actions
    }
}

