/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AutomationConfiguration : AutomationConfiguration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutomationConfiguration {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "strategy")]
    pub strategy: Box<models::StrategyReference>,
    #[serde(rename = "accounts")]
    pub accounts: Vec<models::AccountReference>,
}

impl AutomationConfiguration {
    /// AutomationConfiguration
    pub fn new(name: String, created_at: chrono::DateTime<chrono::FixedOffset>, strategy: models::StrategyReference, accounts: Vec<models::AccountReference>) -> AutomationConfiguration {
        AutomationConfiguration {
            name,
            description: None,
            created_at,
            updated_at: None,
            strategy: Box::new(strategy),
            accounts,
        }
    }
}

