/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CopiedAsset : CopiedAsset
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CopiedAsset {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "total")]
    pub total: f64,
    #[serde(rename = "available")]
    pub available: f64,
    #[serde(rename = "ratio")]
    pub ratio: f64,
}

impl CopiedAsset {
    /// CopiedAsset
    pub fn new(name: String, total: f64, available: f64, ratio: f64) -> CopiedAsset {
        CopiedAsset {
            name,
            total,
            available,
            ratio,
        }
    }
}

