/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateAutomationConfiguration : CreateAutomationConfiguration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAutomationConfiguration {
    /// automation_create
    #[serde(rename = "action_type")]
    pub action_type: models::UserActionType,
    #[serde(rename = "configuration")]
    pub configuration: Box<models::AutomationConfiguration>,
}

impl CreateAutomationConfiguration {
    /// CreateAutomationConfiguration
    pub fn new(action_type: models::UserActionType, configuration: models::AutomationConfiguration) -> CreateAutomationConfiguration {
        CreateAutomationConfiguration {
            action_type,
            configuration: Box::new(configuration),
        }
    }
}

