/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DcaConfiguration : DCAConfiguration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DcaConfiguration {
    /// dca
    #[serde(rename = "configuration_type")]
    pub configuration_type: models::ActionConfigurationType,
    #[serde(rename = "symbols")]
    pub symbols: Vec<String>,
    #[serde(rename = "buy_orders_count")]
    pub buy_orders_count: f64,
    #[serde(rename = "percent_amount_per_buy_order")]
    pub percent_amount_per_buy_order: f64,
    #[serde(rename = "profit_target_percent")]
    pub profit_target_percent: f64,
    #[serde(rename = "buy_order_price_discount_percent")]
    pub buy_order_price_discount_percent: f64,
    #[serde(rename = "enable_stop_loss")]
    pub enable_stop_loss: bool,
    #[serde(rename = "stop_loss_price_discount_percent")]
    pub stop_loss_price_discount_percent: f64,
    #[serde(rename = "trigger_mode")]
    pub trigger_mode: TriggerMode,
    #[serde(rename = "use_init_entry_orders")]
    pub use_init_entry_orders: bool,
    #[serde(rename = "time_frames")]
    pub time_frames: Vec<models::TimeFrame>,
    #[serde(rename = "evaluators")]
    pub evaluators: Vec<models::EvaluatorConfiguration>,
}

impl DcaConfiguration {
    /// DCAConfiguration
    pub fn new(configuration_type: models::ActionConfigurationType, symbols: Vec<String>, buy_orders_count: f64, percent_amount_per_buy_order: f64, profit_target_percent: f64, buy_order_price_discount_percent: f64, enable_stop_loss: bool, stop_loss_price_discount_percent: f64, trigger_mode: TriggerMode, use_init_entry_orders: bool, time_frames: Vec<models::TimeFrame>, evaluators: Vec<models::EvaluatorConfiguration>) -> DcaConfiguration {
        DcaConfiguration {
            configuration_type,
            symbols,
            buy_orders_count,
            percent_amount_per_buy_order,
            profit_target_percent,
            buy_order_price_discount_percent,
            enable_stop_loss,
            stop_loss_price_discount_percent,
            trigger_mode,
            use_init_entry_orders,
            time_frames,
            evaluators,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TriggerMode {
    #[serde(rename = "Maximum evaluators signals based")]
    MaximumEvaluatorsSignalsBased,
    #[serde(rename = "Time based")]
    TimeBased,
}

impl Default for TriggerMode {
    fn default() -> TriggerMode {
        Self::MaximumEvaluatorsSignalsBased
    }
}

