/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeleteStrategyConfiguration : DeleteStrategyConfiguration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteStrategyConfiguration {
    /// strategy_delete
    #[serde(rename = "action_type")]
    pub action_type: models::UserActionType,
    #[serde(rename = "id")]
    pub id: String,
}

impl DeleteStrategyConfiguration {
    /// DeleteStrategyConfiguration
    pub fn new(action_type: models::UserActionType, id: String) -> DeleteStrategyConfiguration {
        DeleteStrategyConfiguration {
            action_type,
            id,
        }
    }
}

