/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DetailedAsset : DetailedAsset
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DetailedAsset {
    #[serde(rename = "symbol")]
    pub symbol: String,
    #[serde(rename = "total")]
    pub total: f64,
    #[serde(rename = "available")]
    pub available: f64,
}

impl DetailedAsset {
    /// DetailedAsset
    pub fn new(symbol: String, total: f64, available: f64) -> DetailedAsset {
        DetailedAsset {
            symbol,
            total,
            available,
        }
    }
}

