/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EditAutomationConfiguration : EditAutomationConfiguration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditAutomationConfiguration {
    #[serde(rename = "id")]
    pub id: String,
    /// automation_edit
    #[serde(rename = "action_type")]
    pub action_type: models::UserActionType,
    #[serde(rename = "configuration")]
    pub configuration: Box<models::AutomationConfiguration>,
}

impl EditAutomationConfiguration {
    /// EditAutomationConfiguration
    pub fn new(id: String, action_type: models::UserActionType, configuration: models::AutomationConfiguration) -> EditAutomationConfiguration {
        EditAutomationConfiguration {
            id,
            action_type,
            configuration: Box::new(configuration),
        }
    }
}

