/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EditStrategyConfiguration : EditStrategyConfiguration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditStrategyConfiguration {
    /// strategy_edit
    #[serde(rename = "action_type")]
    pub action_type: models::UserActionType,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "configuration")]
    pub configuration: Box<models::Strategy>,
}

impl EditStrategyConfiguration {
    /// EditStrategyConfiguration
    pub fn new(action_type: models::UserActionType, id: String, configuration: models::Strategy) -> EditStrategyConfiguration {
        EditStrategyConfiguration {
            action_type,
            id,
            configuration: Box::new(configuration),
        }
    }
}

