/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EditExchangeConfigConfiguration : EditExchangeConfigConfiguration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditExchangeConfigConfiguration {
    /// exchange_config_edit
    #[serde(rename = "action_type")]
    pub action_type: models::UserActionType,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "configuration", skip_serializing_if = "Option::is_none")]
    pub configuration: Option<Box<models::ExchangeConfig>>,
}

impl EditExchangeConfigConfiguration {
    /// EditExchangeConfigConfiguration
    pub fn new(action_type: models::UserActionType, id: String) -> EditExchangeConfigConfiguration {
        EditExchangeConfigConfiguration {
            action_type,
            id,
            configuration: None,
        }
    }
}

