/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EmaMomentumEvaluatorConfiguration : EMAMomentumEvaluatorConfiguration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmaMomentumEvaluatorConfiguration {
    /// EMAMomentumEvaluator
    #[serde(rename = "configuration_type")]
    pub configuration_type: models::EvaluatorType,
    #[serde(rename = "period_length")]
    pub period_length: f64,
    #[serde(rename = "price_threshold_percent")]
    pub price_threshold_percent: f64,
    #[serde(rename = "reverse_signal")]
    pub reverse_signal: bool,
}

impl EmaMomentumEvaluatorConfiguration {
    /// EMAMomentumEvaluatorConfiguration
    pub fn new(configuration_type: models::EvaluatorType, period_length: f64, price_threshold_percent: f64, reverse_signal: bool) -> EmaMomentumEvaluatorConfiguration {
        EmaMomentumEvaluatorConfiguration {
            configuration_type,
            period_length,
            price_threshold_percent,
            reverse_signal,
        }
    }
}

