/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "configuration_type")]
pub enum EvaluatorConfigurationConfiguration {
    #[serde(rename="RSIMomentumEvaluator")]
    RsiMomentumEvaluator(Box<models::RsiMomentumEvaluatorConfiguration>),
    #[serde(rename="EMAMomentumEvaluator")]
    EmaMomentumEvaluator(Box<models::EmaMomentumEvaluatorConfiguration>),
}

impl Default for EvaluatorConfigurationConfiguration {
    fn default() -> Self {
        Self::RsiMomentumEvaluator(Default::default())
    }
}


