/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EvaluatorType : EvaluatorType
/// EvaluatorType
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EvaluatorType {
    #[serde(rename = "RSIMomentumEvaluator")]
    RsiMomentumEvaluator,
    #[serde(rename = "EMAMomentumEvaluator")]
    EmaMomentumEvaluator,

}

impl std::fmt::Display for EvaluatorType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RsiMomentumEvaluator => write!(f, "RSIMomentumEvaluator"),
            Self::EmaMomentumEvaluator => write!(f, "EMAMomentumEvaluator"),
        }
    }
}

impl Default for EvaluatorType {
    fn default() -> EvaluatorType {
        Self::RsiMomentumEvaluator
    }
}

