/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EvaluatorConfiguration : EvaluatorConfiguration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EvaluatorConfiguration {
    #[serde(rename = "configuration")]
    pub configuration: Box<models::EvaluatorConfigurationConfiguration>,
}

impl EvaluatorConfiguration {
    /// EvaluatorConfiguration
    pub fn new(configuration: models::EvaluatorConfigurationConfiguration) -> EvaluatorConfiguration {
        EvaluatorConfiguration {
            configuration: Box::new(configuration),
        }
    }
}

