/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GenericWorkflowConfiguration : GenericWorkflowConfiguration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenericWorkflowConfiguration {
    /// generic_workflow
    #[serde(rename = "configuration_type")]
    pub configuration_type: models::ActionConfigurationType,
    #[serde(rename = "actions")]
    pub actions: Vec<models::Action>,
}

impl GenericWorkflowConfiguration {
    /// GenericWorkflowConfiguration
    pub fn new(configuration_type: models::ActionConfigurationType, actions: Vec<models::Action>) -> GenericWorkflowConfiguration {
        GenericWorkflowConfiguration {
            configuration_type,
            actions,
        }
    }
}

