/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GridConfiguration : GridConfiguration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GridConfiguration {
    /// grid
    #[serde(rename = "configuration_type")]
    pub configuration_type: models::ActionConfigurationType,
    #[serde(rename = "symbol")]
    pub symbol: String,
    /// Price difference between the closest buy and sell orders. Denominated in the quote currency (600 for a 600 USDT spread on BTC/USDT).
    #[serde(rename = "spread")]
    pub spread: f64,
    /// Price difference between two orders of the same side. Denominated in the quote currency (200 for a 200 USDT spread on BTC/USDT).
    #[serde(rename = "increment")]
    pub increment: f64,
    /// Number of initial buy orders to create. Make sure to have enough funds to create that many orders.
    #[serde(rename = "buy_count")]
    pub buy_count: f64,
    /// Number of initial sell orders to create. Make sure to have enough funds to create that many orders.
    #[serde(rename = "sell_count")]
    pub sell_count: f64,
    #[serde(rename = "enable_trailing_up")]
    pub enable_trailing_up: bool,
    #[serde(rename = "enable_trailing_down")]
    pub enable_trailing_down: bool,
    #[serde(rename = "order_by_order_trailing")]
    pub order_by_order_trailing: bool,
}

impl GridConfiguration {
    /// GridConfiguration
    pub fn new(configuration_type: models::ActionConfigurationType, symbol: String, spread: f64, increment: f64, buy_count: f64, sell_count: f64, enable_trailing_up: bool, enable_trailing_down: bool, order_by_order_trailing: bool) -> GridConfiguration {
        GridConfiguration {
            configuration_type,
            symbol,
            spread,
            increment,
            buy_count,
            sell_count,
            enable_trailing_up,
            enable_trailing_down,
            order_by_order_trailing,
        }
    }
}

