/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HistoricalAssetValue : HistoricalAssetValue
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HistoricalAssetValue {
    #[serde(rename = "symbol")]
    pub symbol: String,
    #[serde(rename = "holdings")]
    pub holdings: f64,
    #[serde(rename = "value")]
    pub value: f64,
}

impl HistoricalAssetValue {
    /// HistoricalAssetValue
    pub fn new(symbol: String, holdings: f64, value: f64) -> HistoricalAssetValue {
        HistoricalAssetValue {
            symbol,
            holdings,
            value,
        }
    }
}

