/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MarketMakingOrderBookDepth : Order book depth parameters (cumulated volume and daily volume fraction).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarketMakingOrderBookDepth {
    #[serde(rename = "cumulated_volume_percent")]
    pub cumulated_volume_percent: f64,
    #[serde(rename = "percent_daily_trading_volume")]
    pub percent_daily_trading_volume: f64,
}

impl MarketMakingOrderBookDepth {
    /// Order book depth parameters (cumulated volume and daily volume fraction).
    pub fn new(cumulated_volume_percent: f64, percent_daily_trading_volume: f64) -> MarketMakingOrderBookDepth {
        MarketMakingOrderBookDepth {
            cumulated_volume_percent,
            percent_daily_trading_volume,
        }
    }
}

