/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MarketMakingHedgingEngine : Optional cross-exchange hedging configuration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarketMakingHedgingEngine {
    #[serde(rename = "average_price_counted_minutes", skip_serializing_if = "Option::is_none")]
    pub average_price_counted_minutes: Option<f64>,
    #[serde(rename = "hedging_engine_type", skip_serializing_if = "Option::is_none")]
    pub hedging_engine_type: Option<HedgingEngineType>,
    #[serde(rename = "hedging_exchange", skip_serializing_if = "Option::is_none")]
    pub hedging_exchange: Option<String>,
    #[serde(rename = "hedging_max_loss_threshold", skip_serializing_if = "Option::is_none")]
    pub hedging_max_loss_threshold: Option<f64>,
    #[serde(rename = "hedging_profit_threshold", skip_serializing_if = "Option::is_none")]
    pub hedging_profit_threshold: Option<f64>,
    #[serde(rename = "max_negative_percent_price_change", skip_serializing_if = "Option::is_none")]
    pub max_negative_percent_price_change: Option<f64>,
    #[serde(rename = "max_positive_percent_price_change", skip_serializing_if = "Option::is_none")]
    pub max_positive_percent_price_change: Option<f64>,
}

impl MarketMakingHedgingEngine {
    /// Optional cross-exchange hedging configuration.
    pub fn new() -> MarketMakingHedgingEngine {
        MarketMakingHedgingEngine {
            average_price_counted_minutes: None,
            hedging_engine_type: None,
            hedging_exchange: None,
            hedging_max_loss_threshold: None,
            hedging_profit_threshold: None,
            max_negative_percent_price_change: None,
            max_positive_percent_price_change: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HedgingEngineType {
    #[serde(rename = "spot")]
    Spot,
    #[serde(rename = "perpetual_futures")]
    PerpetualFutures,
}

impl Default for HedgingEngineType {
    fn default() -> HedgingEngineType {
        Self::Spot
    }
}

