/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderSummary : OrderSummary
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderSummary {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "symbol")]
    pub symbol: String,
}

impl OrderSummary {
    /// OrderSummary
    pub fn new(id: String, symbol: String) -> OrderSummary {
        OrderSummary {
            id,
            symbol,
        }
    }
}

