/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderGroupType : Order group class name (mirrors persisted OrderGroup.__name__ in octobot_trading).
/// Order group class name (mirrors persisted OrderGroup.__name__ in octobot_trading).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OrderGroupType {
    #[serde(rename = "BalancedTakeProfitAndStopOrderGroup")]
    BalancedTakeProfitAndStopOrderGroup,
    #[serde(rename = "TrailingOnFilledTPBalancedOrderGroup")]
    TrailingOnFilledTpBalancedOrderGroup,
    #[serde(rename = "OneCancelsTheOtherOrderGroup")]
    OneCancelsTheOtherOrderGroup,

}

impl std::fmt::Display for OrderGroupType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::BalancedTakeProfitAndStopOrderGroup => write!(f, "BalancedTakeProfitAndStopOrderGroup"),
            Self::TrailingOnFilledTpBalancedOrderGroup => write!(f, "TrailingOnFilledTPBalancedOrderGroup"),
            Self::OneCancelsTheOtherOrderGroup => write!(f, "OneCancelsTheOtherOrderGroup"),
        }
    }
}

impl Default for OrderGroupType {
    fn default() -> OrderGroupType {
        Self::BalancedTakeProfitAndStopOrderGroup
    }
}

