/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderType : Exchange order type.
/// Exchange order type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OrderType {
    #[serde(rename = "limit")]
    Limit,
    #[serde(rename = "market")]
    Market,
    #[serde(rename = "stop_loss")]
    StopLoss,
    #[serde(rename = "stop_loss_limit")]
    StopLossLimit,
    #[serde(rename = "take_profit")]
    TakeProfit,
    #[serde(rename = "take_profit_limit")]
    TakeProfitLimit,

}

impl std::fmt::Display for OrderType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Limit => write!(f, "limit"),
            Self::Market => write!(f, "market"),
            Self::StopLoss => write!(f, "stop_loss"),
            Self::StopLossLimit => write!(f, "stop_loss_limit"),
            Self::TakeProfit => write!(f, "take_profit"),
            Self::TakeProfitLimit => write!(f, "take_profit_limit"),
        }
    }
}

impl Default for OrderType {
    fn default() -> OrderType {
        Self::Limit
    }
}

