/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PortfolioHistoricalValuesState : PortfolioHistoricalValuesState
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PortfolioHistoricalValuesState {
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "history", skip_serializing_if = "Option::is_none")]
    pub history: Option<Box<models::PortfolioHistoricalValues>>,
}

impl PortfolioHistoricalValuesState {
    /// PortfolioHistoricalValuesState
    pub fn new(version: String) -> PortfolioHistoricalValuesState {
        PortfolioHistoricalValuesState {
            version,
            history: None,
        }
    }
}

