/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PortfolioHistoricalValue : PortfolioHistoricalValue
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PortfolioHistoricalValue {
    #[serde(rename = "timestamp")]
    pub timestamp: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "total")]
    pub total: f64,
    #[serde(rename = "assets", skip_serializing_if = "Option::is_none")]
    pub assets: Option<Vec<models::HistoricalAssetsForTradingType>>,
}

impl PortfolioHistoricalValue {
    /// PortfolioHistoricalValue
    pub fn new(timestamp: chrono::DateTime<chrono::FixedOffset>, total: f64) -> PortfolioHistoricalValue {
        PortfolioHistoricalValue {
            timestamp,
            total,
            assets: None,
        }
    }
}

