/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RefreshAccountsConfiguration : RefreshAccountsConfiguration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RefreshAccountsConfiguration {
    /// accounts_refresh
    #[serde(rename = "action_type")]
    pub action_type: models::UserActionType,
    #[serde(rename = "account_ids", skip_serializing_if = "Option::is_none")]
    pub account_ids: Option<Vec<String>>,
}

impl RefreshAccountsConfiguration {
    /// RefreshAccountsConfiguration
    pub fn new(action_type: models::UserActionType) -> RefreshAccountsConfiguration {
        RefreshAccountsConfiguration {
            action_type,
            account_ids: None,
        }
    }
}

