/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StopAutomationConfiguration : StopAutomationConfiguration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StopAutomationConfiguration {
    #[serde(rename = "id")]
    pub id: String,
    /// automation_stop
    #[serde(rename = "action_type")]
    pub action_type: models::UserActionType,
}

impl StopAutomationConfiguration {
    /// StopAutomationConfiguration
    pub fn new(id: String, action_type: models::UserActionType) -> StopAutomationConfiguration {
        StopAutomationConfiguration {
            id,
            action_type,
        }
    }
}

