/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "configuration_type")]
pub enum StrategyConfiguration {
    #[serde(rename="MarketMakingConfiguration")]
    MarketMakingConfiguration(Box<models::MarketMakingConfiguration>),
    #[serde(rename="DCAConfiguration")]
    DcaConfiguration(Box<models::DcaConfiguration>),
    #[serde(rename="IndexConfiguration")]
    IndexConfiguration(Box<models::IndexConfiguration>),
    #[serde(rename="GridConfiguration")]
    GridConfiguration(Box<models::GridConfiguration>),
    #[serde(rename="CopyConfiguration")]
    CopyConfiguration(Box<models::CopyConfiguration>),
    #[serde(rename="GenericProcessConfiguration")]
    GenericProcessConfiguration(Box<models::GenericProcessConfiguration>),
    #[serde(rename="GenericWorkflowConfiguration")]
    GenericWorkflowConfiguration(Box<models::GenericWorkflowConfiguration>),
}

impl Default for StrategyConfiguration {
    fn default() -> Self {
        Self::MarketMakingConfiguration(Default::default())
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TriggerMode {
    #[serde(rename = "Maximum evaluators signals based")]
    MaximumEvaluatorsSignalsBased,
    #[serde(rename = "Time based")]
    TimeBased,
}

impl Default for TriggerMode {
    fn default() -> TriggerMode {
        Self::MaximumEvaluatorsSignalsBased
    }
}

