/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StrategiesState : StrategiesState
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StrategiesState {
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "strategies")]
    pub strategies: Vec<models::Strategy>,
}

impl StrategiesState {
    /// StrategiesState
    pub fn new(version: String, strategies: Vec<models::Strategy>) -> StrategiesState {
        StrategiesState {
            version,
            strategies,
        }
    }
}

