/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Strategy : Strategy
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Strategy {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "reference_market")]
    pub reference_market: String,
    #[serde(rename = "configuration")]
    pub configuration: Box<models::StrategyConfiguration>,
}

impl Strategy {
    /// Strategy
    pub fn new(id: String, version: String, reference_market: String, configuration: models::StrategyConfiguration) -> Strategy {
        Strategy {
            id,
            version,
            name: None,
            description: None,
            created_at: None,
            updated_at: None,
            reference_market,
            configuration: Box::new(configuration),
        }
    }
}

