/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TrailingProfileType : Trailing profile discriminator (mirrors octobot_trading TrailingProfileTypes values).
/// Trailing profile discriminator (mirrors octobot_trading TrailingProfileTypes values).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TrailingProfileType {
    #[serde(rename = "filled_take_profit")]
    FilledTakeProfit,

}

impl std::fmt::Display for TrailingProfileType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::FilledTakeProfit => write!(f, "filled_take_profit"),
        }
    }
}

impl Default for TrailingProfileType {
    fn default() -> TrailingProfileType {
        Self::FilledTakeProfit
    }
}

