/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "action_type")]
pub enum UserActionConfiguration {
    #[serde(rename="automation_create")]
    AutomationCreate(Box<models::CreateAutomationConfiguration>),
    #[serde(rename="automation_edit")]
    AutomationEdit(Box<models::EditAutomationConfiguration>),
    #[serde(rename="automation_stop")]
    AutomationStop(Box<models::StopAutomationConfiguration>),
    #[serde(rename="automation_signal")]
    AutomationSignal(Box<models::SignalAutomationConfiguration>),
    #[serde(rename="account_create")]
    AccountCreate(Box<models::CreateAccountConfiguration>),
    #[serde(rename="account_edit")]
    AccountEdit(Box<models::EditAccountConfiguration>),
    #[serde(rename="account_delete")]
    AccountDelete(Box<models::DeleteAccountConfiguration>),
    #[serde(rename="exchange_config_create")]
    ExchangeConfigCreate(Box<models::CreateExchangeConfigConfiguration>),
    #[serde(rename="exchange_config_edit")]
    ExchangeConfigEdit(Box<models::EditExchangeConfigConfiguration>),
    #[serde(rename="exchange_config_delete")]
    ExchangeConfigDelete(Box<models::DeleteExchangeConfigConfiguration>),
    #[serde(rename="accounts_refresh")]
    AccountsRefresh(Box<models::RefreshAccountsConfiguration>),
    #[serde(rename="strategy_create")]
    StrategyCreate(Box<models::CreateStrategyConfiguration>),
    #[serde(rename="strategy_edit")]
    StrategyEdit(Box<models::EditStrategyConfiguration>),
    #[serde(rename="strategy_delete")]
    StrategyDelete(Box<models::DeleteStrategyConfiguration>),
    #[serde(rename="account_auth_create")]
    AccountAuthCreate(Box<models::CreateAccountAuthConfiguration>),
    #[serde(rename="account_auth_edit")]
    AccountAuthEdit(Box<models::EditAccountAuthConfiguration>),
    #[serde(rename="account_auth_delete")]
    AccountAuthDelete(Box<models::DeleteAccountAuthConfiguration>),
}

impl Default for UserActionConfiguration {
    fn default() -> Self {
        Self::AutomationCreate(Default::default())
    }
}


