/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserAction : UserAction
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserAction {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::UserActionStatus>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "configuration", skip_serializing_if = "Option::is_none")]
    pub configuration: Option<Box<models::UserActionConfiguration>>,
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::UserActionResult>>,
}

impl UserAction {
    /// UserAction
    pub fn new(id: String) -> UserAction {
        UserAction {
            id,
            status: None,
            created_at: None,
            updated_at: None,
            configuration: None,
            result: None,
        }
    }
}

