/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserActionType : UserActionType
/// UserActionType
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UserActionType {
    #[serde(rename = "automation_create")]
    AutomationCreate,
    #[serde(rename = "automation_edit")]
    AutomationEdit,
    #[serde(rename = "automation_stop")]
    AutomationStop,
    #[serde(rename = "automation_signal")]
    AutomationSignal,
    #[serde(rename = "account_create")]
    AccountCreate,
    #[serde(rename = "account_edit")]
    AccountEdit,
    #[serde(rename = "account_delete")]
    AccountDelete,
    #[serde(rename = "accounts_refresh")]
    AccountsRefresh,
    #[serde(rename = "exchange_config_create")]
    ExchangeConfigCreate,
    #[serde(rename = "exchange_config_edit")]
    ExchangeConfigEdit,
    #[serde(rename = "exchange_config_delete")]
    ExchangeConfigDelete,
    #[serde(rename = "strategy_create")]
    StrategyCreate,
    #[serde(rename = "strategy_edit")]
    StrategyEdit,
    #[serde(rename = "strategy_delete")]
    StrategyDelete,
    #[serde(rename = "account_auth_create")]
    AccountAuthCreate,
    #[serde(rename = "account_auth_edit")]
    AccountAuthEdit,
    #[serde(rename = "account_auth_delete")]
    AccountAuthDelete,

}

impl std::fmt::Display for UserActionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AutomationCreate => write!(f, "automation_create"),
            Self::AutomationEdit => write!(f, "automation_edit"),
            Self::AutomationStop => write!(f, "automation_stop"),
            Self::AutomationSignal => write!(f, "automation_signal"),
            Self::AccountCreate => write!(f, "account_create"),
            Self::AccountEdit => write!(f, "account_edit"),
            Self::AccountDelete => write!(f, "account_delete"),
            Self::AccountsRefresh => write!(f, "accounts_refresh"),
            Self::ExchangeConfigCreate => write!(f, "exchange_config_create"),
            Self::ExchangeConfigEdit => write!(f, "exchange_config_edit"),
            Self::ExchangeConfigDelete => write!(f, "exchange_config_delete"),
            Self::StrategyCreate => write!(f, "strategy_create"),
            Self::StrategyEdit => write!(f, "strategy_edit"),
            Self::StrategyDelete => write!(f, "strategy_delete"),
            Self::AccountAuthCreate => write!(f, "account_auth_create"),
            Self::AccountAuthEdit => write!(f, "account_auth_edit"),
            Self::AccountAuthDelete => write!(f, "account_auth_delete"),
        }
    }
}

impl Default for UserActionType {
    fn default() -> UserActionType {
        Self::AutomationCreate
    }
}

