/*
 * OctoBot protocol types
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserActionsState : UserActionsState
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserActionsState {
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "user_actions", skip_serializing_if = "Option::is_none")]
    pub user_actions: Option<Vec<models::UserAction>>,
}

impl UserActionsState {
    /// UserActionsState
    pub fn new(version: String) -> UserActionsState {
        UserActionsState {
            version,
            user_actions: None,
        }
    }
}

