import React, {type ReactNode} from 'react';
import {
  LandingLayout,
  Hero,
  Section,
  FAQ,
  CTABand,
  TradingViewWidget,
  type FAQItem,
} from '@site/src/components/landing';
import GlassCard from '@site/src/components/GlassCard';
import type {Cryptocurrency} from '../types';
import shared from '../styles.module.css';

/*
 * "What is <crypto>" explainer — programmatic route /what-is-<slug>.
 *
 * Generated by the octobot-programmatic-pages plugin from the OctoBot Cloud
 * endpoint payload. Migrated from the Astrolab (programmatic)/[slug] Crypto
 * page into the Neo Glass Dark landing toolkit.
 */

const CLOUD = 'https://www.octobot.cloud';

interface WhatIsCryptoData {
  crypto: Cryptocurrency;
}

export default function WhatIsCrypto({
  data,
}: {
  data: WhatIsCryptoData;
}): ReactNode {
  const {crypto} = data;
  const faqItems: FAQItem[] = (crypto.faq ?? []).map((entry) => ({
    question: entry.question,
    answer: entry.answer,
  }));

  return (
    <LandingLayout
      title={`What is ${crypto.name}?`}
      description={`What is the ${crypto.name} (${crypto.symbol}) cryptocurrency: purpose, technology, fundamentals and price history.`}>
      <div className={shared.gridVeil} aria-hidden="true" />

      <Hero
        eyebrow="Cryptocurrency"
        title={
          <>
            What is{' '}
            <span className="ng-text-gradient">{crypto.name}?</span>
          </>
        }
        subtitle={`Understand what makes ${crypto.name} (${crypto.symbol}) unique — its purpose, technology and key metrics.`}
        actions={[
          {label: `Invest in ${crypto.symbol}`, to: CLOUD},
          {
            label: 'Price converter',
            to: `/tools/converter/${crypto.symbol.toLowerCase()}/usd`,
            variant: 'ghost',
          },
        ]}
        meta={[
          {label: crypto.symbol, dot: true},
          {label: 'Fundamentals'},
          {label: 'Live price chart'},
        ]}
      />

      <Section eyebrow="Overview" title={`What is ${crypto.name}?`}>
        <GlassCard variant="strong" padded className={shared.panel}>
          <p className={shared.prose}>{crypto.whatIs}</p>
        </GlassCard>
      </Section>

      <Section
        eyebrow="Price"
        title={`${crypto.name} price history`}
        lead={`The live ${crypto.symbol}/USDT market, charted.`}>
        <div className={shared.chart}>
          <TradingViewWidget symbol={`BINANCE:${crypto.symbol}USDT`} />
        </div>
      </Section>

      {faqItems.length > 0 && (
        <Section eyebrow="FAQ" title={`${crypto.name} FAQ`}>
          <FAQ items={faqItems} />
        </Section>
      )}

      <CTABand
        title={
          <>
            Put your {crypto.symbol}{' '}
            <span className="ng-text-frost">to work.</span>
          </>
        }
        description={`Automate a ${crypto.name} strategy on OctoBot Cloud, or convert it first.`}
        actions={[
          {label: 'Start on OctoBot Cloud', to: CLOUD},
          {
            label: `${crypto.symbol} converter`,
            to: `/tools/converter/${crypto.symbol.toLowerCase()}/usd`,
            variant: 'ghost',
          },
        ]}
      />
    </LandingLayout>
  );
}
