import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guides: [
    {
      type: 'autogenerated',
      dirName: 'guides',
    },
  ],
  investing: [
    {
      type: 'autogenerated',
      dirName: 'investing',
    },
  ],
  developers: [
    'developers/getting-started',
    {
      type: 'category',
      label: 'Architecture',
      items: [{type: 'autogenerated', dirName: 'developers/architecture'}],
    },
    {
      type: 'category',
      label: 'Developer Environment',
      items: [{type: 'autogenerated', dirName: 'developers/environment'}],
    },
    {
      type: 'category',
      label: 'Tentacles Development',
      items: [{type: 'autogenerated', dirName: 'developers/tentacles-dev'}],
    },
    {
      type: 'category',
      label: 'Scripting',
      items: [{type: 'autogenerated', dirName: 'developers/scripting'}],
    },
    {
      type: 'category',
      label: 'SDK',
      items: [{type: 'autogenerated', dirName: 'developers/sdk'}],
    },
    {
      type: 'category',
      label: 'Packages',
      link: {type: 'doc', id: 'developers/packages/overview'},
      items: [{type: 'autogenerated', dirName: 'developers/packages'}],
    },
'developers/contributing',
    'developers/changelog',
  ],
};

export default sidebars;
