name: OctoBot-Tentacles-Preview-Close
on:
  pull_request:
    types: [ closed ]

jobs:
  okteto_preview-close:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Destroy preview environment
      uses: okteto/destroy-preview@master
      with:
        name: pr-${{ github.event.number }}-octobot-drakkarsoftware
